- README.md
>  fix: link syntax@README

- ios/RNSScreenContainer.m
With this change in the screens that are being transitioned get detach+attach events similarily to how it is done in UINavigationController. This allows views underneath to get notified that the transition is started and react to it when necessary (e.g. hide keyboard)
> Trigger moveToWindow:nil call when screen animation starts to mimick UINavController behavior

- ios/RNScreens.xcodeproj/project.pbxproj
I added a RNScreens-tvOS Target. It doesn't have anything that doesn't work on tvOS.
it's working in our project now.
> Add tvOS target

- src/screens.native.js
If screens are not used, linking shouldn't be required.
> Add lazy requiring screens components

- README.md
https://github.com/kmagiera/react-native-screens/issues/7#issuecomment-508294742
> [trivial] Update README.md - ReactFragmentActivity

- ios/RNScreens.xcodeproj/project.pbxproj
fix wrong `RNSScreen.m` path in project.pbxproj
> fix project.pbxproj

- android/build.gradle
- android/gradle.properties
In new version gradle of react and android x, has message of deprecated items. 
when use this update, fix the problem
> Fix deprecated items

- android/build.gradle
- android/gradle.properties
This reverts commit 5a9b3d1408a839a8635bfe0abaafaf87b191f25e.
Closes #207
> Revert "Fix deprecated items (#156)"

- ios/RNSScreenStackHeaderConfig.m
Fixes https://github.com/kmagiera/react-native-screens/pull/195#issuecomment-549146288
> Fix compile error on xcode 10

- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfigViewManager.java
- ios/RNSScreen.m
- ios/RNSScreenStackHeaderConfig.h
- ios/RNSScreenStackHeaderConfig.m
When some of config props change or new header items are added we need to perform a header update. This diff adds logic to trigger updating header props when that happens.
> Fix updating stack config props.

- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
This change fixes two issues related to stack nesting on Android.
First one being the fact that root and nested fragments were relying on the same fragment manager as opposed to using nested fragment manager structure (via getChildFragmentManager). This resulted in an unprodictable behavior when displaying the top screen. This commit changes this behavior by correctly returning child fragment manager or root fragment manager depending on the containers hierarchy.
Second issue was related to back stack handling and resulted in always the root fragment manager interacting. Instead we want the bottommost active stack to handle back presses. This has been addressed by adding `setPrimaryNavigationFragment` when creating back stack entries.
> Fix stack nesting on Android.

- android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
This change fixes the problem when there are changes being made to the stack while the hosting activity is in paused state (e.g. an activity-based dialog from google play services). In such a case it is not allowed to do any changes which can affect fragment manager's state (e.g. updating backstack). For other changes we use `commitAllowingStatLoss` to indicate we are not interested in fragment manager handling their restoration and hence we can perform most operations. Unfortunately installing back handler is not allowed without state change and we need to wait until the fragment host is resumed before we install it.
> Avoid changing back stack when fragment manager is not resumed.

- src/screens.d.ts
This issue closes #261 
Added typescript definitions for `<ScreenStack>` and `<ScreenStackHeaderConfig>`
> Add missing types

- ios/RNSScreenStack.m
This change fixes a problem in modal dismiss logic. The problem would occur when we had a nested stack that both have screens pushed and presented modally. In such case when we only wanted to pop one of the screens pushed (even though the screen was obscured by the one presented modally) we'd still run setModalViewControllers method. As a result that method could've find the navigato that is presenting the screens modally and trigger dismiss on them. This was the case because we used to only check in that method whether the top-most unchanged screen is presenting modals. We shouldn't only be checking whether the screen is presenting because it may be presenting modals that belong to a different stack that did not change.
To prevent the issue from happening we make sure that we run dismiss …
> Fix bug in modal dismiss logic.

- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
- android/src/main/java/com/swmansion/rnscreens/ScreenFragment.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java
Fix #259 
**Issue**
Screen doesn't update when switching between tabs.
**Problem**
When `ScreenContainer` re-added. `mFragmentManager` is destroyed.
> [Android] Bottom tab not update

- ios/RNSScreenStackHeaderConfig.m
This fixes a problem when image attribute of image view would get reset and we wouldn't be able to access it even in release mode. This could happen when the app is backgrounded as at that point image views release their resources. Another case that was quite frequent was that the image would start loading before the image view frame was properly set. The solution is to trigger image reload in cases when image is missing and to force the image view frame to match the size of an image.
This change also fixes a problem on iOS pre 13 where we were updating back indicator inside of the method which would run during the transition. Turns out updating this property isn't supported during animation and so we moved it out such that it is updated before the transition starts.
> Force reload back indicator image view when image is nil.

- ios/RNSScreenStack.m
This update changes the logic of how we present modals. Previously presentedModals array could get out of sync with the actual app state because in case when parent VC is not mounted, presenting a modal would silently fail. In order to handle that we added additional update trigger from where the screen stack is mounted to a window. Second change that we added here addresses a problem of concurrent calls to update modals. As we cannot update presentedModals array synchrounously (all presentation callbacks are async even when no animation is involved), we need to block future updates unless the previous batch of updates is done. To do that we added a flag that prevents method re-entry. The flag is reset when all the presentation animations are over.
> Update iOS native modals presenting logic to be more resilient

- ios/RNSScreenStack.m
This change addresses two problem. First was related to header subviews that were not laid out properly before we installed them in the header. This was causing occasional bugs where the header subviews were misplaced. The fix was to enforce container update run after layout is done (we enqueue update on ui thread directly from didUpdateReactSubviews).
The second problem was related to UINavController nlifecycle methods not triggering correctly in case when updates are being made to the nav controller which isn't mounted. Previously we fixed similar issue for modal controllers where because of the fact container wasn't mounted we couldn't run modal screen updates. With push controllers the problem is very similar however the VC do update just stop getting proper lifecycle updates and …
> Fix updating push native stack to avoid mid-transition related bugs

- ios/RNSScreen.m
After exaiming memory graph it turned out that screens for which we access presentationController property ends up leaking, likely because of some issue in UIKit. This turns out not to affect screens that are actually being presented as modals (when presentationController is required). This change updates presentation mode setter to avoid accessing presentationController for push screens and also warns if the prop ever switches from modal to push (in which case we cannot reverse the leak source).
> Fix memory leak related to access of presentationController.

- native-stack/views/NativeStackView.tsx
Fixes #356 
<div style="display: flex;">
</div>
> fix: remove background when stackPresentation is transparentModal

- ios/RNSScreenStack.m
This change fixes a problem with modal updating logic. First issue we are addressing here is the re-entry problem. We need to avoid re-entry to setModalViewControllers method as it relies on keeping reactSubviews and _presentedModals in sync. Previously we had a re-entry check added but it was a bit too late in the method code. The re-entry check should be added before we access _presentedModals. We've been testing if the list of controllers vs _presentedModals differes at the very beggining. However, if the transition is already running the _presentedModals may be out of sync and that check may fail even though it shouldn't. Placing it after re-entry check guarantees that we will execute it after the syncing process is complete.
The second problem was related to nested stack herarchies …
> Fix modal update logic

- README.md
According to #397, we don't need those dependencies anymore.
> [docs] Remove unnecessary gradle dependencies

- native-stack/types.tsx
- native-stack/views/HeaderConfig.tsx
- src/screens.d.ts
Add props added in #333 to native-stack.
> Expose new largeTitleBackgroundColor and largeTitleHideShadow props to native-stack

- README.md
Added the new Software Mansion logo to README file
> Add new Software Mansion logo

- .gitattributes
- Example/.flowconfig
- Example/.gitignore
- Example/android/app/build.gradle
- Example/android/app/src/main/AndroidManifest.xml
- Example/android/app/src/main/java/com/swmansion/rnscreens/example/MainApplication.java
- Example/android/app/src/main/java/com/swmansion/rnscreens/example/ReactNativeFlipper.java
- Example/android/build.gradle
- Example/android/gradle.properties
- Example/android/gradle/wrapper/gradle-wrapper.properties
- Example/android/gradlew
- Example/android/gradlew.bat
- Example/ios/Podfile
- Example/ios/Podfile.lock
- Example/ios/ScreensExample.xcodeproj/project.pbxproj
- Example/ios/ScreensExample.xcodeproj/xcshareddata/xcschemes/ScreensExample-tvOS.xcscheme
- Example/ios/ScreensExample.xcodeproj/xcshareddata/xcschemes/ScreensExample.xcscheme
- Example/ios/ScreensExample/AppDelegate.h
- Example/ios/ScreensExample/AppDelegate.m
- Example/ios/ScreensExample/main.m
- Example/ios/ScreensExampleTests/ScreensExampleTests.m
- Example/package.json
- Example/yarn.lock
> feat: upgrade Example to RN 0.62

- src/screens.d.ts
Currently this isn't being exported by typescript
> Export ScreenStackHeaderCenterView

- package.json
- yarn.lock
Add release-it to make releases easier.
Also added script checking for changes in ios/ and android/ dirs, so release changing native code won't be a patch release (expo convention).
> Add release-it

- README.md
- native-stack/README.md
- src/index.d.ts
- src/native-stack/types.tsx
Added missing types for modal `stackPresentation` prop. PR based on work of @pvinis.
> feat: add modal types

- src/native-stack/navigators/createNativeStackNavigator.tsx
- src/native-stack/views/HeaderConfig.tsx
Fixed regression introduced in 2.10.0.
> fix: remove regression

- package.json
Changed release-it script with help of @jakub-gonet
> feat: change release-it

- package.json
Removed release-it hook since it does not work properly.
> feat: remove release-it hook

- android/src/main/java/com/swmansion/rnscreens/ScreenFragment.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java
Added information about restoring `Fragments` and link to the workaround.
> feat: add info about restoring fragments

- Example/nativeStack.js
- Example/navigationTabsAndStack.js
- Example/stack.js
- Example/tabs.js
Fixed some warnings from eslint
> fix: eslint warnings

- .eslintrc.js
Added option for using `ts-ignore` when provided description.
> feat: silence eslint ts-ignore warnings

- Example/ios/Podfile.lock
- Example/ios/ScreensExample/AppDelegate.m
- Example/ios/ScreensExample/Info.plist
- Example/nativeNavigation.js
- ios/RNSScreen.h
- ios/RNSScreen.m
- ios/RNSScreenContainer.h
- ios/RNSScreenContainer.m
- ios/RNSScreenStack.h
- ios/RNSScreenStack.m
- ios/RNSScreenStackHeaderConfig.h
- ios/RNSScreenStackHeaderConfig.m
- ios/UIViewController+RNScreens.h
- ios/UIViewController+RNScreens.m
- native-stack/README.md
- src/index.d.ts
- src/native-stack/types.tsx
- src/native-stack/views/HeaderConfig.tsx
- src/native-stack/views/NativeStackView.tsx
Added status bar management on iOS based on the VCs. The user must apply change described in README to `AppDelegate.m` and to the project's `Info.plist` in order for the new props to work.
> feat: add status bar managment

- createNativeStackNavigator/README.md
- src/createNativeStackNavigator.js
Added new props and documentation to older version of native-stack
> feat: add status bar management to v4

- package.json
Reverted the change of version in package.json
> fix: revert release commit

- .github/ISSUE_TEMPLATE/---bug-report.md
- .github/ISSUE_TEMPLATE/---feature-request.md
- .github/ISSUE_TEMPLATE/-question.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/main.yml
- Example/ios/Podfile.lock
- package.json
- src/createNativeStackNavigator.js
- src/index.d.ts
- src/native-stack/types.tsx
- yarn.lock
Added first look on GH actions.
> feat: add first look on GH actions

- TestsExample/App.js
Small PR adding the `Test648` test case, not included in the PR.
> fix: add missing Test648 in App.js

- src/index.js
Export all components from `index.d.ts` in `index.js` (web implementation). Should fix #729.
Updated `index.js`.
> fix: export all components from index.d.ts

- .github/workflows/main.yml
- package.json
Removed `yarn test:unit` on commit since there are no tests so it makes the `precommit` longer without a reason.
> feat: remove testing on commit

- package.json
Added `android/src/main/res` to files included in the project package. Should fix #744. 
Include `react-native-screens` in your project and run Android app.
> fix: add res to published files

- TestsExample/App.js
- TestsExample/ios/Podfile.lock
- TestsExample/ios/TestsExample/Info.plist
- TestsExample/src/Test642.js
Added test example for status bar management.
Added `Test642.js`.
> feat: add statusBar example

- src/index.d.ts
Added missing `ScreenOrientationTypes` type in `index.d.ts`.
Updated `index.d.ts`.
> fix: add ScreenOrientationTypes

- RNScreens.podspec
this PR update links in `RNScreens.podspec`
Updated `RNScreens.podspec` file
> update links in RNScreens.podspec

- ios/RNSScreen.m
PR adding #712 and #772 to `2.15.0` for patch release of Expo SDK 40.
> Apply #712 and #772 on top of 2.15.0

- ios/RNSScreenContainer.m
Removed disabling interaction during transition. It should remove the delay of the ability to interact with new screen, but also introduce the ability to click on the transitioning screens. Requested in #95.
Removed code responsible for user interaction during transitioning.
> feat: enable interaction during transition

- README.md
Updated a typo in the readme from insured to ensured
Updated a typo in the readme from insured to ensured
Updated a typo in readme.md
> Update README TYPO

- TestsExample/App.js
- TestsExample/src/Test861.tsx
- src/native-stack/views/NativeStackView.tsx
`containedTransparentModal` has default backgroundColor but should be transparent.
> fix: make containedTransparentModal transparent

- README.md
Add branded header image to project's README
> Add branded header image to README

- Example/yarn.lock
- yarn.lock
PR merging 3 PRs of dependabot into one.
> chore(deps): bump hosted-git-info, ua-parser-js (#919)

- ios/RNSScreen.m
- ios/RNSScreenStack.m
- ios/RNSScreenStackHeaderConfig.m
- ios/RNSScreenWindowTraits.h
- ios/RNSSearchBar.m
PR made on top of #984 adding checks for tvOS.
Compiling project for tvOS target.
> fix: tvOS compiling

- TestsExample/ios/Podfile.lock
- TestsExample/src/Test999.tsx
- ios/RNSScreenStack.m
PR fixing weird animation of native back button when replacing screen with push animation on iOS. 
`Test999.tsx` in `TestsExample` project.
> fix: back button in push replace animation

- android/src/main/java/com/swmansion/rnscreens/ScreenFragment.java
Clean up event dispatching code on Android.
`Test593.tsx` see that events dispatching doesn't change after PR.
> feat: clean event dispatching on Android

- README.md
- package.json
Add `windows` directory to list of files published to npm. Updated README with installation instructions.
Add `windows` directory to list of files published to npm. Updated README with installation instructions.
> Add windows Directory to NPM Publish

- android/src/main/java/com/swmansion/rnscreens/LifecycleHelper.kt
- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenContainerViewManager.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenFragment.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfigViewManager.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderSubview.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderSubviewManager.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackViewManager.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt
Removed all `!!` from kotlin files and resolved all of warnings that could be resolved easily.
> feat: enforce null safety in kotlin files

- TestsExample/App.js
- TestsExample/ios/Podfile.lock
PR fixing deleted by mistake files from #890 and updating `Podfile.lock` of `TestsExample`.
> fix: restore deleted tests and update TestsExample

- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt
This PR brings a line of code we missed while converting Java code to Kotlin.
> fix: bring back transition progress in simple animations

- README.md
This PR adds to main README information about platforms supported by `react-native-screens`.
> docs: add supported platforms info

- TVOSExample/android/build.gradle
Add mavenCentral in TVOSExample
> Add mavenCentral in TVOSExample

- .eslintrc.js
- package.json
- src/reanimated/ReanimatedNativeStackScreen.tsx
- src/reanimated/ReanimatedScreen.tsx
- src/reanimated/ReanimatedScreenProvider.tsx
- src/reanimated/index.tsx
- yarn.lock
Adds plugin for checking hooks
> chore: Adds eslint hook plugin and fixes hooks errors

- native-stack/README.md
Fix `searchBar` only for `iOS`.
> docs: fix search bar only for iOS

- src/types.tsx
Fixes order of comments to much props in search bar
Fixes order of comments to much props in search bar
> fix: incorrect prop descriptions in types.tsx

- FabricExample/src/HeaderDemo.js
- ios/RNSScreenStackHeaderConfigComponentView.mm
- src/fabric/ScreenStackHeaderSubviewNativeComponent.js
This PR fixes compilation on iOS and behavior of headerTitle and title props on Fabric.
FabricExample/ project
> fix: headerTitle & title props on Fabric

- FabricExample/package.json
- FabricExample/yarn.lock
This PR removes an unused `patch-package` package from FabricExample.
> fix: remove patch-package from FabricExample

- package.json
> fix: add .mm files to lint-staged

- .github/ISSUE_TEMPLATE/bug-report.md
Added option to specify affected architectures in issue template.
As stated above
Try to file a new issue.
> chore: add architecture list to issue template

- ios/RNSScreenStackHeaderSubview.h
Fixes #1505
Changed the import from `<react/..` to `<React/...` since this breaks on case sensitive file systems.
- [] Included code example that can be used to test this change
- [] Updated TS types
> fix: update import for case-sensitive file systems

- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- android/src/paper/java/com/swmansion/rnscreens/FabricEnabledViewGroup.kt
This PR reformats code in the repository. 
```sh
yarn format
yarn lint
```
> chore: format android code

- RNScreens.podspec
- ios/RCTImageComponentView+RNSScreenStackHeaderConfig.h
- ios/RCTImageComponentView+RNSScreenStackHeaderConfig.mm
- ios/RNSConvert.h
- ios/RNSConvert.mm
- ios/RNSFullWindowOverlay.h
- ios/RNSFullWindowOverlay.mm
- ios/RNSScreen.h
- ios/RNSScreen.mm
- ios/RNSScreenContainer.h
- ios/RNSScreenContainer.mm
- ios/RNSScreenNavigationContainer.mm
- ios/RNSScreenStack.h
- ios/RNSScreenStack.mm
- ios/RNSScreenStackHeaderConfig.h
- ios/RNSScreenStackHeaderConfig.mm
- ios/RNSScreenStackHeaderSubview.h
- ios/RNSScreenStackHeaderSubview.mm
- ios/RNSSearchBar.h
- ios/RNSSearchBar.mm
Changed `RN_FABRIC_ENABLED` to `RCT_NEW_ARCH_ENABLED` since it is the current standard for this flag.
> chore: change fabric flag

- android/build.gradle
Correct spelling.
Improve readability by correcting spelling.
I have made these changes in customized builds of React Native and not encountered any issues.
> chore: fix typo in build script

- FabricExample/yarn.lock
- FabricTestExample/yarn.lock
- TestsExample/yarn.lock
Aggregating dependabot PRs
* https://github.com/software-mansion/react-native-screens/pull/1806
* https://github.com/software-mansion/react-native-screens/pull/1805 
* https://github.com/software-mansion/react-native-screens/pull/1804
> chore(deps): update selected deps in examples

- guides/GUIDE_FOR_LIBRARY_AUTHORS.md
> chore: fix typo in docs

- Example/yarn.lock
- FabricExample/yarn.lock
- FabricTestExample/yarn.lock
- TVOSExample/yarn.lock
- TestsExample/yarn.lock
- yarn.lock
Just aggregating dependabot PRs
* https://github.com/software-mansion/react-native-screens/pull/1833
* https://github.com/software-mansion/react-native-screens/pull/1836
* https://github.com/software-mansion/react-native-screens/pull/1838
* https://github.com/software-mansion/react-native-screens/pull/1837
* https://github.com/software-mansion/react-native-screens/pull/1839
* https://github.com/software-mansion/react-native-screens/pull/1840
> chore(deps): update `word-wrap`

- src/native-stack/types.tsx
- src/types.tsx
Just fixing a typo I've noticed while doing other things.
> chore: fix typo in docs on `sheetCornerRadius`

- .github/workflows/android-e2e-test.yml
- .github/workflows/ios-e2e-test.yml
Changes in JS may impact components behaviour -> e2e tests should be triggered
Added a trigger event to e2e CI spec
-
> chore(CI): trigger e2e tests on JS-only changes

- Example/yarn.lock
- FabricExample/yarn.lock
- FabricTestExample/yarn.lock
- TVOSExample/yarn.lock
- TestsExample/yarn.lock
- yarn.lock
* https://github.com/software-mansion/react-native-screens/pull/1928/
* https://github.com/software-mansion/react-native-screens/pull/1927/
* https://github.com/software-mansion/react-native-screens/pull/1926/
* https://github.com/software-mansion/react-native-screens/pull/1925/
* https://github.com/software-mansion/react-native-screens/pull/1924/
* https://github.com/software-mansion/react-native-screens/pull/1923/
> chore(deps): update `@babel/traverse` from 7.21.0 to 7.23.2

- src/components/Screen.tsx
PR fixing the app freezes due to `react-freeze` 😄
> fix: handle setting `display` for `_viewConfig` attribute

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- FabricExample/yarn.lock
- FabricTestExample/ios/Podfile.lock
- TVOSExample/ios/Podfile.lock
- TestsExample/ios/Podfile.lock
- package.json
> Release 3.31.0-rc.0

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- FabricTestExample/ios/Podfile.lock
- TestsExample/ios/Podfile.lock
- package.json
> Release 3.31.0-rc.1

- README.md
This PR adds a "Hire us" section to the README with a link to the contact form.
> chore: add hire us section to readme

- Example/yarn.lock
- FabricExample/yarn.lock
- FabricTestExample/yarn.lock
- TestsExample/yarn.lock
- android/src/main/java/com/swmansion/rnscreens/RNScreensPackage.kt
- yarn.lock
Aggregating the PRs here, because dependabot opens another, just after the previous is merged, leading to ton of its PRs...
Dependabot PRs:
* #2198 
* #2203
* #2204
* #2205
* #2206
There are still some dependabot PRs pending, however they can not be applied right now cause they require major version changes, thus we'll need to wait for downstream updates.
Example applications should work just fine.
> chore(deps): aggreated updates from dependabot

- android/build.gradle
We support RN >= 0.72 so this code is no longer needed.
> chore: remove unused code for finding rn version

- .github/workflows/docs-check.yml
- docs/src/components/Overview/Multiplatform/index.tsx
Just a correction for invalid import for SVG file.
- Changed `TV.svg` import to `tv.svg`
> docs: Resolve correctly missing tv.svg file

- docs/src/components/Hero/ScreenSequence/styles.module.css
- docs/src/components/Hero/StartScreen/styles.module.css
> docs: Fix placement of Hero on big screens

- README.md
Update path for FullWindowOverlay example
- Updated `README.md` docs
> docs(readme): update FullWindowOverlay example path

- src/components/ScreenContentWrapper.web.tsx
Missing stubs for web.
See the changes, no additional description is needed.
- [-] Ensured that CI passes
> feat: add stub implementations for `ScreenContentWrapper` for web

- src/components/ScreenContentWrapper.web.tsx
- src/components/ScreenFooter.web.tsx
Adding stub implmentation for web.
See files. No more description needed.
- [-] Ensured that CI passes
> feat: add stub implementations for `ScreenFooter` for web

- src/components/Screen.tsx
- src/types.tsx
Verify the invariant specified in `sheetAllowedDetents` prop documentation in dev mode.
`Test1649`
> feat: assert that detents array is sorted in dev mode

- src/native-stack/views/NativeStackView.tsx
> chore: remove unnecessary logs from native-stack v5

- src/fabric/ModalScreenNativeComponent.ts
Sync ScreenNative and ModalScreenNative props.
> refactor: sync props

- apps/src/tests/index.ts
This PR removed leftover test import
> fix: removed leftover test import after cherry-picking from main

- FabricExample/Gemfile.lock
- TVOSExample/yarn.lock
- docs/yarn.lock
Aggregate updates from dependabot:
* #2457
* #2451
* #2452
- [-] Ensured that CI passes
> chore(deps): aggregate updates from dependabot

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
> chore(examples): update lock files after release

- apps/App.tsx
Accidentally committed changes to apps/App.tsx
Restore old contents.
CI
> chore: retore apps/App.tsx

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
Update lockfiles after 4.2.0 release
> chore: update lockfiles after release

- README.md
> chore(readme): update supported react-native versions

- .github/workflows/check-archs-consistency.yml
- android/src/paper/java/com/swmansion/rnscreens/NativeScreensModuleSpec.java
It is a 3rd time in like two weeks I need to fixup main because the consistency check didn't run on PR.
The check CI should now trigger on PRs which might affect it.
This PR should trigger the check.
> chore: trigger consistency-check workflow when editing related scripts + fixup

- README.md
Updated README.
- added to README - version 3.36.0+ for Paper with support for RN 0.73.0+
- added to README - version 3.36.0+ for Fabric with support for RN 0.77.0+
> docs: update README for new library version release

- apps/Example.tsx
Adding test screens to the example application so that we can automate regression testing where-ever feasible.
Currently the test screens are always visible, but we could limit it in the future to CI only.
Just run the `FabricExample` app and scroll down.
> chore: add test examples do example app

- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.kt
Aligning with other callback methods.
Just as in the PR title.
N/A
> refactor(Android): rename `notifyChildUpdated` -> `onChildUpdated`

- Example/yarn.lock
- FabricExample/package.json
- FabricExample/yarn.lock
- docs/yarn.lock
Most likely #2833 unblocked dependabot & it has opened more PRs.
* #2835 
* #2836 
* #2837 
* #2834
build
> chore(deps): aggregate updates from dependabot - another round

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
It's annoying to do this everytime I change the branch.
> chore(examples): update lock files after release 4.11.0-beta.1

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- package.json
> release: 4.11.0-beta.2

- src/components/Screen.tsx
- src/components/helpers/sheet.tsx
Doing some code cleanup.
Moved all sheet specific functions & constants to separate module.
Refactor / behavior should be unaffected. CI should pass & e2e should pass.
I did some sanity checks, whether haven't broken anything by accident & sheet seems to keep working 
exactly the way they did before.
> refactor: move sheet specific helper functions to separate module

- docs/package.json
- docs/yarn.lock
Practically nothing changes, it was done to keep screens docs up-to-date.
Bump `@swmansion/t-rex-ui` to `1.0.0`
> docs: Bump t-rex to stable with Docusaurus 3.7

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- TVOSExample/ios/Podfile.lock
- package.json
Release 4.11.1, bump lockfiles.
> release: 4.11.1

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- package.json
Release of 4.12.0
Bump podfiles
> release: 4.12.0

- ios/bottom-tabs/RNSTabBarAppearanceCoordinator.mm
Fixes https://github.com/software-mansion/react-native-screens-labs/issues/321.
- change method name, fixing the typo
Run TestBottomTabs.
> fix(iOS, Tabs): fix typo in Appearance Coordinator

- .eslintrc.js
This resolves linter issues in native component specs, which we can not
really fix.
Basically the issue is as follows:
Lint CI should pass.
> fix(lint): prevent eslint from failing by updating eslint rules

- ios/RNSScreenStack.mm
- ios/utils/UINavigationBar+RNSUtility.mm
See particular commits for explanation
> review: 3093

- android/src/paper/java/com/facebook/react/viewmanagers/RNSSearchBarManagerDelegate.java
As the PR title states - it is outdated.
Ran `yarn sync-architectures` & commited the output.
Example should build fine (CI should pass).
> fix(Android,Paper): fix codegened interface for RNSSearchBarManagerDelegate

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- package.json
Release 4.14.0 + lock files update after release
> release: 4.14.0

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- package.json
Release 4.14.1 + lock files update after release
> release: 4.14.1

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- package.json
Release 4.15.0 + lock files update after release
> release: 4.15.0

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- package.json
Release 4.15.4 + lock files update after release
> release: 4.15.4

- apps/src/tests/TestSplitView/SplitViewPerfApp.tsx
- apps/src/tests/TestSplitView/index.tsx
Adding an example with some heavier components for testing whether the transitions are working smoothly.
- Added example
https://github.com/user-attachments/assets/3255edc3-d666-4599-82a4-ceab666362d9
Tested changes with the new example and https://github.com/software-mansion/react-native-screens/pull/3285
> test(iOS, SplitView): Add example for testing performance
