- package.json
I do not see any specific features (maybe I missed something), but it seems reasonable to go for every `react` and `react-native` version if `react-navigation` does.
resolves #4
> Resolve unmet peer dependencies

- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.java
setActive method will receive double type,Double cannot be cast to java.lang.Integer
> fixes setActive method when the param is not int type in Android

- package.json
- src/screens.d.ts
Only type I'm worried about is `onComponentRef`. It's a callback that takes an instance of a `React.Component`, but that instance is typed as `any` within here.
> Add typescript definitions

- src/screens.js
Such as web and windows. `requireNativeComponent` is undefined on web.
This lives as a patch on [DailyScrum](https://github.com/Minishlink/DailyScrum/commit/3d6b5c45ae8ad4bf75cf61719c059bb6b1a42fa4) - web version.
> Minimal support for other platforms

- ios/RNSScreenContainer.m
It works anyway but causes a warning in xcode.
> Fix typo in updateContainer method definition

- android/src/main/java/com/swmansion/rnscreens/RNScreensPackage.java
- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
- android/src/main/java/com/swmansion/rnscreens/ScreenContainerViewManager.java
As discussed on slack, 
From @kmagiera 
> Definitely a typo, when strayed the project i named it screen (no s) but some time later realized that name's been taken on npm and elsewhere
PLEASE warn users as this is breaking and they need to change MainApplication.java to add *s*
> Rename RNScreen to RNScreens to stay consistent

- src/screens.native.js
https://github.com/facebook/react-native/commit/aac7c4d5d24787f46ad1745204748c533554489e#diff-2527fb9fd9c4888767c90b634276a93b deprecates `UIManager['${moduleName}']` and adds `getViewManagerConfig`. This uses this method when available to preserve backwards compatibility. We can remove the compat method when we stop supporting RN < 0.58.
> Use `getViewManagerConfig` when available to remove warning

- README.md
Updating a really minor typo in the readme: `s/enojy/enjoy`.
Here it is in context:
```markdown
3. That's all 🎉 – enjoy faster navigation in your Expo app. Keep in mind screens are in pretty early phase so please report if you discover some issues.
```
> Fixing a minor typo

- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
This fixes a crash I saw in production on Android `java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState`. The fix is based on the comment here https://stackoverflow.com/questions/7575921/illegalstateexception-can-not-perform-this-action-after-onsaveinstancestate-wit.
The crash stopped happening since deploying this fix.
Fixes #20
> Use `commitAllowingStateLoss` instead of `commit`

- ios/RNSScreen.h
- ios/RNSScreen.m
- ios/RNSScreenContainer.m
This change automates first responder restoring when screen is deactivated and the activated back (e.g. when we push new screen on top and then go back). In addition we disable pointerEvent setting for the Screen component as changes made to that prop would cause underlying views to resign responder before we can remember it. Because of that we add an automatic handling for pointer events for the Screen component that disables all touch interactions when screen is transitioning.
> Restore first responder of view controller when screen reactivates

- ios/RNSScreen.m
This is a follow up to #48 which makes Screen component ignore setting of pointerEvents. As it turns out react-navigation tries to set this setting and in addition to handling it manually we also need to prevent it to be set via React prop.
> Ignore pointerEvent set via react props

- android/src/main/java/com/swmansion/rnscreens/Screen.java
- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
- src/screens.native.js
This change adds an ability for screen container on Android to apply the correct mechanism for transparent layer blending. This is specifically important as screens are usually a complex views that may displays many layers and while transitioning often opacity is used to animate these. When we detect screen transitioning we (a) turn on offscreen alpha compositing (which makes the opacity being applied for the whole screen layer at once instead of making all the children semi-transparent) and also (b) turn on hardware layer that makes offscreen compositing render to GPU (which is both faster and consumes only GPU memory).
In addition to that change we also need to disable wrapping Screen's children with View, as in such a case opacity is applied on the underlying View instead of a Screen. …
> Android alpha compositing

- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
This change makes us reach to fragment manager only when screen container is attached to window (and therefore we are sure that the current activity is react one). The problem reported in #33 was due to the fact we'd do that when container is instantiated which does not necessarily mean that react activity is in foreground. We didn't need to actually access fragment manager while not in foreground so this change removes fragmentManager as a member and we get it directly from context when needed.
Supposedly fixes #33
> Make sure we access fragment manager only when view is attached (activity is foregrounded)

- ios/RNSScreenContainer.m
Previously we weren't triggering transaction finish when going from none active screens to 1 active screen. This turns out to be the case in tab navigator where for a sub-frame moment the active state changes for the current screen to `NO` and then new screen isn't active yet.
Fixes #53
> Restore view interaction when container changes from 0 active to 1 active

- android/build.gradle
Add suport to gradle 4.10.1 or high!
The new version of android studio 3.3 recommendete to update gradle project to 4.10.1 
> To take advantage of the latest features, improvements, and security fixes, we strongly recommend that you update the Android Gradle plugin to version 3.3.0 and Gradle to version 4.10.1. [Release notes ](https://developer.android.com/studio/releases/gradle-plugin) 
>Android plugin 3.2.0 and higher now support building the Android App Bundle—a new upload format that defers APK generation and signing to compatible app stores, such as Google Play. With app bundles, you no longer have to build, sign, and manage multiple APKs, and users get smaller, more optimized downloads. [Learn more](https://developer.android.com/guide/app-bundle/?utm_source=android-studio)
but if …
> update to gradle 4.10.1 or high

- android/src/main/java/com/swmansion/rnscreens/Screen.java
I was getting the following compilation errors when I pulled in this repo.
```
error: unmappable character for encoding ASCII
```
The root cause seems to be the character below was not from the ASCII set.
> Fix non ascii character in comment

- package.json
- src/screens.web.js
- yarn.lock
[`react-navigation-stack`](https://github.com/react-navigation/react-navigation-stack/pull/105) relies on Screens to be removed when the active prop is falsey.
Set `display: none` when the `active` prop is `false` or an `Animated.Value` with a value of `0`.
Related: https://github.com/react-navigation/react-navigation-stack/pull/105
> [web] Added active prop

- src/screens.native.js
I was debugging why react-navigation-stack wasn't computing pointerEvents correctly. 
(https://github.com/react-navigation/react-navigation-
stack/blob/93470b4be8ab76558eda635069248ce1a74fe1d8/src/views/StackView/createPointerEventsContainer.js#L76)
Turns out (https://github.com/react-navigation/react-navigation-stack/blob/93470b4be8ab76558eda635069248ce1a74fe1d8/src/views/StackView/createPointerEventsContainer.js#L53) always bails as `this._component` is always null.
Turns out the callback passed to `<Screen>` is never called here (https://github.com/react-navigation/react-navigation-stack/blob/93470b4be8ab76558eda635069248ce1a74fe1d8/src/views/StackView/StackViewCard.js#L62)
This PR adds the missing ref if you're running RN version >= 0.57
With this change the callbacks are registered …
> Fix the missing setRef handler

- src/screens.d.ts
The TS definitions specify the prop as a boolean, but passing a boolean causes a crash.
> Fix type of active prop in typescript definitions

- android/build.gradle
- android/gradle.properties
- android/gradle/wrapper/gradle-wrapper.properties
- android/src/main/java/com/swmansion/rnscreens/LifecycleHelper.java
- android/src/main/java/com/swmansion/rnscreens/Screen.java
- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
This PR aims to upgrade from android support v4 to androidX.
> Upgrade from android support v4 to androidX

- android/src/main/java/com/swmansion/rnscreens/Screen.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
This PR fixes a problem with soft keyboard not always popping up when new screen is shown with an autoFocus inputtext.
The root cause is the mechanism used by autoFocus flag that uses `requestAnimationFrame` in which focus is called on a textinput component ref. Because of that RN may sometimes evaluate focus handler while the native view is not yet attached to view hierarchy. As a result InputMethodManager RN use to trigger soft keyboard may fail seeing a non attached input field. In this workaround we listed to onAttach events on screens and look for focused fields. If there is one it means the field has been focused before the transition ended. In that case we use `OnAttachStateChangeListener` that we plug to the textinput waiting for it to attach. The listener then triggers soft input …
> Fix issue with soft keyboard not showing from time to time on Android

- ios/RNSScreen.h
- ios/RNSScreen.m
- ios/RNSScreenStack.h
- ios/RNSScreenStack.m
On iOS by default modals show up in full-screen mode. This behavior can be customized and instead of mouting new screens in top level window they can be mounted under a given UINavController. We used to be relying on that behavior (see "CurrentContext" presentation mode). This, apparently wasn't matching the default functionality of the OS. This change is adding it as a default and keeping the old way under newly exposed presentation modes: containedModal and containedTransparentModal
Thanks to this change, iOS 13 modals can work properly.
Android support for the newly added presentation types is missing and will be added in follow up PR.
> Implement full screen modals on iOS

- ios/RNSScreen.m
- ios/RNSScreenStack.m
- ios/RNSScreenStackHeaderConfig.h
- ios/RNSScreenStackHeaderConfig.m
This change fixes the problem when header would update to the previous screen configuration as a result of starting swipe back gesture but never restore to the original one in case swipe back gets cancelled (e.g. user didn't swipe far enough). The problem was that as a result of swipe back we'd apply header config changes but after cancel there was no trigger to reset header to the previous state.
> Fix header config when navigating back gets cancelled.

- ios/RNSScreen.m
We observe that bounds are not updating at all. Method `updateBounds` is not called at all while transitioning.
As a result yoga reevaluation is not performed so content has bad size i.e. it's not possible to scroll to the very end in ScrollView because a component has a bad size in comparison to the parent (it should have the exact same height).   
It can be observed in navigation-ex and it works better after my fix: https://streamable.com/miun2
> Call update bounds after transition on iOS

- createNativeStackNavigator.js
> Remove usage of ScenesReducer

- Example/App.js
- Example/navigationTabsAndStack.js
- README.md
- src/screens.d.ts
- src/screens.native.js
- src/screens.web.js
This wants to be a small PR to improve the usability of the library, based on this conversation: https://twitter.com/grifotv/status/1127847192067215360.
Since the release of RNS there has been a new major player in the React game: hooks. And sadly `useScreens` recalls too closely Hooks, and this can lead to misunderstanding.
Changing it to `enableScreens` will make the difference clear, but at the same time it will be a BREAKING CHANGE for everyone using the lib.
So if we prefer to keep it around as useScreens I'm ok with it too, and we can close this.
Also, I did some tweaks to the README + fix some typos.
> Enhancement: change to useScreens to enableScreens

- Example/android/app/src/main/AndroidManifest.xml
- android/build.gradle
- android/src/main/java/com/swmansion/rnscreens/Screen.java
- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
- android/src/main/java/com/swmansion/rnscreens/ScreenFragment.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackViewManager.java
- ios/RNSScreen.m
Fixes to most of the issues listed in #153 – thanks @ferrannp for trying out native stack and for reporting these.
This PR fixes the issue when screen rendered under ScreenStack container would use invalid dimensions for layouting its children. On iOS we move the control over the size of that component to `UINavController` subclass which reports screen size back to RN's UIManager to let yoga layout subviews.
On Android we introduced an intermediate view hierarchy for each screen that uses `CoordinatorLayout` and `AppBarLayout`. We are not fully utilizing the power of these two native components and for now only rely on them to layout navbar and screen container. Similarity to iOS we then pass measured screen dimensions to yoga in order for react native to render children properly.
> Fix header rendering – layout and transparency

- ios/RNSScreen.m
Using alternative modal presentation styles like `transparentModal` is not working. This is because accessing `presentationController` before setting the `modalPresentationStyle` causes the presentation controller to be created and cannot be changed afterwards. This is documented https://developer.apple.com/documentation/uikit/uiviewcontroller/1621426-presentationcontroller?language=objc.
Yes very cool API
Tested via @react-navigation/native-stack using presentation: 'transparentModal'.
> Fix non-default modal presentation styles

- src/screens.native.js
When using RN from master the version is 0.0.0 so we can just check if minor is 0 (this code breaks if major gets bump already anyway).
> Fix RN version check when using master

- README.md
- createNativeStackNavigator.js
- ios/RNSScreenStackHeaderConfig.h
- ios/RNSScreenStackHeaderConfig.m
Currently on iOS when you set `titleColor` it is not applied to the `largeTitle`.
This PR will apply the `titleColor` and `titleFontFamily` to the `largeTitle`.
> Apply custom title font attributes to largeTitle

- ios/RNSScreen.m
Supporting fade in for modals can be done by using `modalTransitionStyle = UIModalTransitionStyleCrossDissolve`. For other type of animations we leave this as the default value.
Tested via `@react-navigation/native-stack` with `{ animation: 'fade', presentation: 'transparentModal' }`
> Support fade in animation for modals on iOS

- src/screens.native.js
There was a bug in PR that introduces enableScreens method to replace useScreens. The bug was that the method did not end up being exported (we use module.exports and not export syntax). On top of that I'm adding a deprecation warning to useScreens method as it interferes with some react hooks tooling.
> Fix useScreens -> enableScreens renaming

- android/src/main/java/com/swmansion/rnscreens/Screen.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfigViewManager.java
- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.java
A few bugs fixed with android native stack in this commit:
- fixed a problem with views not resizing when keyboard appears, the bug was due to onMeasure forwardin getHeight which was the old height of the container instead of the changed one
- fixed a problem with back button behavior not being consistent. Now back button is controlled by 'gestureEnabled' to emulate iOS behavior where there is no hw back button but you can swipe back instead.
- added compatibility for "contained" modal styles - for now we always render "containted" fragments on Android, plan to add a way to render in dialogs in the future
> Android native stack bugfixes.

- createNativeStackNavigator.js
Adding a few changes to react-navigation bindings to help with compatibility issues. Namely:
- allow for to just be a string in which case we update `headeOption.title` with it
- allow for all `header*` props to be either components or function
> Some compatibility adjustments for react-navigation bindings

- ios/RNSScreenStackHeaderConfig.m
- `@available` should not be used with other conditions (not sure if it breaks anything but it does trigger warnings in xcode)
- missing runtime check before using `modalInPresentation`, kept the precompiler instruction so it still builds on older xcodes.
> Fix iOS version runtime checks in RNSScreenStackHeaderConfig

- src/screens.native.js
Follow up of 4749405d641c11c0bf5a6193f75ec15552217d69, let's remove the es exports from this file to avoid confusion. It uses `module.export`.
> Remove es exports from screens.native.js

- ios/RNSScreenStackHeaderConfig.m
This change makes it possible for header customization options to use appearence API introduces in iOS 13. Thanks to this the default header setting will respect header translucency. Thanks to the appearence API we no longer need to set so many properties in setAnimatedConfig.
> iOS13 header customization updates.

- ios/RNSScreen.h
- ios/RNSScreen.m
- ios/RNSScreenStack.m
iOS navbar largeTitle setting allows the navbar to be automatically collapsed when scrolling. For that to work iOS expects scrollable component to be rendered in the screen view hierarchy as a first children (or just to be looked up on the ancestor path using first children when navigating down). On top of that in RN we should use contentInsetAdjustmentBehavior="automatic" for SV's contentInsets to adjust as expected when the header scrolls and to allow for the SV background to be present below the navigation bar.
This works pretty well w/o any changes. However when testing I disovered one issue with the navigation bar rendering in a collapsed state on the first render. After that you could've scroll down to reveal large title bar but the initial state would be collapsed. As on iOS it is …
> Make it possible for iOS largeTitle to collapse while scrolling.

- ios/RNSScreen.m
- ios/RNSScreenContainer.m
For native stack we introduced a new way of layouting screen controllers. We no longer rely on flexbox to layout them so that we can use native stack to provide a correct dimensions and safe area paddings. Unfortunately this change broke the old screen container. With this commit we are adapting layout change to old screen container that will now layout its direct children on the native side by making them take up the whole space of the container.
> Fix screen container after rnsscreen layout change.

- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
Before this change we'd rely on new androidx OnBackPressedCallback mechanism. It turns out not to work well in a few cases. The biggest problem with it was that when registered it'd never allow for the hw back button press to fallback to a system default behaviour and instead would always "still" that event. After several attempts of trying to make it work I decided to revert back to a FragmentManager's default solution.
This change adds an ability to use FragmentManager's back stack API. There are also a few problems with it we need to workaround though. One of the problem is the fact that we can not modify back stack history. What we do because of that is that we try to keep at most one item on the back stack and reset it each time our native stack updates. In order for that to work we …
> Use fragment manager back stack to handle hw back button presses on Android.

- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
- android/src/main/java/com/swmansion/rnscreens/ScreenContainerViewManager.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
This is a similar fix to the one already merged in #215 but for Android this time. We change default screen container to layout its direct children without using flexbox. This is to follow the same pattern as with native stack container.
> Fix screen container layout on Android.

- ios/RNSScreenStack.m
When more than one screen is initially mounted we were only installing the top navigator with UINavController. This was cauing the back-handling logic to not work properly.
> Fix iOS stack navigator restoring state.

- ios/RNSScreenStackHeaderConfig.m
After #184 we no longer were acconting for the size of navigation bar when laying out screens on the stack. This was causing elements to be drawn under a non-translucent bar unless SafeAreaView's been used. As this seem not to be desirable in most of the cases (there is no way of seeing items rendered underneath non-translucent header) this change brings back the previous behavior. Instead of using manual method of calculating top inset as it's been done before we rely on edgesForExtendedLayout property of the view controller.
> Fix screen layout with non-translucent header on iOS.

- android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
There was an issue with back stack listener being triggered after reload caused by the fact we weren't cleaning up stack manager's back stack on reload. As a result after reload listener would get triggered with and empty stack first and only then with a back stack with 1 item. Consequence of the first trigger was that we'd call dismiss and move back from the top screen which wasn't a desirable behavior.
> Fix issue with stack triggering back on reload on Android.

- README.md
- ios/RNSScreen.h
- ios/RNSScreen.m
- ios/RNSScreenStack.m
Add bindings for `UIModalTransitionStyleFlipHorizontal`. I also tried to get the page curl one working but it was glitchy and I don't really have the time to figure out why.
> [native-stack] Add flip transition on iOS

- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfigViewManager.java
This value should not be converted to pixels. `setTextSize` already expects a value in SP.
https://developer.android.com/reference/android/widget/TextView.html#setTextSize(float)
> Fix titleFontSize on Android

- android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
This change fixes the issue of handling transparent status bar. In such a case the navbar should became slightly bigger in order to fill the status bar space that now belongs to the window. In order for that to happen we use `setFitsSystemWindows` on main screen layout, on app bar layout and on toolbar (the toolbar is the view that gets bigger in the end).
Note that this currently only work if we use Android's native mechanism for changingthe status bar behavior and not using `StatusBar` module from RN. It is because `StausBar` module actually strips top insets from the event that gets delivered to the views. For the time being you can try the following to change status bar:
```
getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE | …
```
> Fix navbar window fitting on Android.

- ios/RNSScreenStackHeaderConfig.m
This fixes the problem when navbar settings update from ones that have header items (e.g. custom title object) to a config without such items. In such a case we'd set navbar items in the first go and never reset those items.
> Reset header navbar items when not set.

- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
Before this change, updates made to toolbar's subviwews weren't properly reflected. We'd only add new views to toolbar w/o removing stale ones.
> Fix Android's toolbar config update

- ios/RNSScreenStack.h
- ios/RNSScreenStack.m
The previous algorithm was buggy and did not handle the case when multiple VCs are being dismissed. Unfortunately I couldn't find a reliable way that'd allow for reshuffling modally presented VCs (inserting or deleting VCs not from the top) and so I added a special check that'd throw in the case someone attemted to do this.
> Fix modal controllers update algorithm.

- android/src/main/java/com/swmansion/rnscreens/ScreenAppearEvent.java
- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
- android/src/main/java/com/swmansion/rnscreens/ScreenFragment.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java
- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.java
- createNativeStackNavigator.js
- ios/RNSScreen.h
- ios/RNSScreen.m
Appear event is used by react-navigation to properly dispatch focus. It is important that appear is dispatched after dismissed event. The reverse order of actions would result in getting react-navigation stack in a weird state.
It is relatively streightforward to implement onAppear event on iOS where we hook into didAppear callback from UIViewController. It gets dispatched in the right moment, that is when the transition is fully over.
On Android however it is much more tricky. There is no standard way to be notified from the fragment level that fragment transition finished. One way that is frequently recommended is to override Fragment.onCreateAnimation. However, this only works when custom transitions are provided (e.g. if we set the transition to use fade animation). As we want the …
> Dispatch appear event for screens.

- createNativeStackNavigator.js
Previously when transparent card was requested we'd default to transparentModal stack presentation mode. However if user requests contained modal mode we should be using containedTransparentModal instead. This change fixes that behavior.
> Use containedTransparentModal in RNN wrapper when requested.

- ios/RNSScreen.m
fixes https://github.com/kmagiera/react-native-screens/issues/208
For stack overriding `reactSetFrame` for `active` does nothing because `active` is always `NO`, so there's no regression.
But it fixes in other cases (like stack navigation - not native one).
> Fix not displaying view in navigation

- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderSubview.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderSubviewManager.java
- createNativeStackNavigator.js
- ios/RNSScreenStackHeaderConfig.h
- ios/RNSScreenStackHeaderConfig.m
- src/screens.native.js
For customizing back button image we use platform native functionality that is: `setBackIndicatorImage` on iOS and `setHomeAsUpIndicator` on Android.
The reason we don't do that just by setting left item is that we get a couple of things for free such as handling RTL properly, working accessibility features, handling prop for hiding back button and a couple more.
Unfortunately there are some downsides to that approach too. We need to install the back button as an Image component from the JS side, and the extract the image payload on the native side to set it with the navigator. This is specifically problematic in DEV mode where images are loaded asynchronously over HTTP from the packager. In order for that to work we had to employ a few hacks (more comments on that in the code).
> Add support for customizing back button image.

- ios/RNSScreenStack.m
This issue is related to #92.
**Issue**
-------
I got issue when playing video with `react-native-video`. The video keep playing (still hear sound) when go back.
```
react-native: 0.61.5
react-native-screens: 2.0.0-alpha.22
```
**Solution**
-------
When controller popped, try to assign view to nil to break the cycle.
> [ios] release view from controller when popped from stack

- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
- android/src/main/java/com/swmansion/rnscreens/ScreenContainerViewManager.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfigViewManager.java
This change fixes the problem when header update would get triggered while the header config subviews are not yet fully unmounted. The root cause of this problem is kind of a mystery, I encouneter a crash when going back using back button from a screen that have custom back button image rendered. Turned out that after implementing removeAll schema the problem no longer occurs. I didn't have enough time to investigate it further but supporting removeAll schema is an improvement regardless so going with this solution for now.
> Fix detaching views rendered under header config component.

- ios/RNSScreenStack.m
- ios/RNSScreenStackHeaderConfig.m
https://github.com/kmagiera/react-native-screens/pull/254 without breaking changes
Instead of moving gestureEnabled to the screen we find the header config subview.
> Fix stack with gestureEnabled=false on iOS

- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfigViewManager.java
This change prevents toolbar from updating when there is a transition happening to the view. This fixes the issue where header subviews would disappear when going back from a given screen. The root cause was that the config view manager would trigger subviews removal and re-layout itself. As aresult if we had a custom back button that back button would get removed and the title would move into its place while the screen animation is running. In order to prevent that we hook into View Manager's onDropViewInstance to notify header config that it is about to be destroyed. This in turn prevents any updates to be made to the toolbar config.
> Fix header transition on Android.

- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
- android/src/main/java/com/swmansion/rnscreens/ScreenFragment.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java
Reverts kmagiera/react-native-screens#275
#275 has been merged prematurely. The PR did not provide any description on why the proposed changes make sense and they seem to be causing weird effects. We were aware of the issue with destroyed fragment manager and I believe #272 should properly address it. I'm going to revert #275 in favor of merging #272
> Revert "[Android] Bottom tab not update"

- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
Code to reproduce and test: https://snack.expo.io/@angelikaserwa/humiliated-bagel.
Switch to the Settings tab, then go back to the Home tab and press the details button. Nothing happens. It was because after re-attaching we were using a destroyed FragmentManager that was cached inside the ScreenContainer class. 
Then, when we go back from Details to Home screen, using a hardware back button, an exception occured: `The specified child already has a parent. You must call removeView() on the child's parent first`.
I fixed this by calling `removeAllViews()` when detaching container from window and forcing an update on re-attach.
> [android] Fix re-attaching ScreenContainer to window

- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
This PR fixes an issue when screen container does not get updated properly after being detached and re-attached on Android. An example where this bug surfaces is when we have a screens based tabs rendered inside stack container. When we push new screen on top of tabs the tabs container is detached, then after going back to that screen we don't get the selected tab displayed but instead we see an empty screen (issue reported in #272).
The root cause of the issue is that we clean all child views when container detaches but we don't clear `mActiveScreenFragments` array which keeps track on what fragments have been attached. After the container is re-attached it occurs to the container as if it has a screen already installed while all the children are removed. Clearing …
> [Android] update view when go back to previous screen

- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
This change fixes the issue when left item added to native stack header on Android would by default be shifted from the screen edge by some amount. This turned out to be the default config of the native toolbar which applies some padding on the left side. WIn this change we reset that padding to always be 0 to let the position be specified from react. Note that the setting we reset does not influence the position of the native back navigation button as Android does not apply the padding in case navigation back icon is rendered.
> Fix layout of header items on Android native stack.

- android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
This change fixes crash caused when nested stack is detached due to the parent stack being closed. As a result we may end up in a situation when fragment manager is not yet set despite onDetach callback being call. When fragment manager is not set we can also ignore the operations we should've performed in on detach. This change adds a null check before we call into fragment manager in on detach callback.
> Fix NPE on nested stack detach on Android.

- android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
This change fixes the issue with auto focusing text input fields inside native stack. Due to the fact we perform hide and show transactions in order to control back stack the hiding part would propagate visibility change event down the view hierarchy. As a result views would receive that visibility event and blur themselves resulting in textinput not getting the focus when the fragment mounts. It turns out however that for the back stack to function properly we don't need to run hide and show operation within the transaction because show is idempotent. So we change our back stack handling transaction to only call show.
> Fix focus events in native stack on Android.

- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderSubview.java
This change removes the behavior that's been added for an unclear reason. We may consider reverting this one, however I was unable to reproduce a problem when setting header title view layout measurements was necessary. To the contrary it was causing issues in the case when the title header view updates. In such a case we would never update width/height so the updated view might be cropped. In addition we are changing the way we schedule native layout updates. Previously we'd use handler.post but it was causing one frame delay so this change migrates us to use choreographer.
> Fix rendering title view in native header on Android.

- README.md
The prop is called `onDismissed` according to the code
https://github.com/kmagiera/react-native-screens/blob/e00a08a3dc8d96eabb391725d6af57f28d78e300/android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.java#L65
https://github.com/kmagiera/react-native-screens/blob/e00a08a3dc8d96eabb391725d6af57f28d78e300/ios/RNSScreen.h#L43
> Fix typo in `onDismissed` prop name

- ios/RNSScreenStackHeaderConfig.m
This change fixes a bug when header property updates happens during or at the same time of stack transition, e.g., when we both pop a screen and change parent VC header properties. When this happens we trigger header update code, but because we used to compare current VC to visibleViewController, which at that moment points to controller that we are transitioning away from, the update would've been prevented. With this change instead of using visibleViewController to compare with updated VC, we check if there is transition happening (using transitransitionCoordinator property), and in such case we use topController which points to the controller we are transitioning to.
> Fix updating native header on iOS while transition is ongoing.

- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderSubview.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderSubviewManager.java
- createNativeStackNavigator.js
- ios/RNSScreenStackHeaderConfig.m
- src/screens.native.js
This change removes ScreenStackHeaderTitleView component and code that used to handle title view scaling. There were multiple issues related to scaling toolbar title views and it is not a priority at the moment to us to work on addressing those. The most frequent usecase is to put a fixed-dimensions view (e.g. logo or text) which can be now handled w/o this extra code.
> Delete Title subview and code for handling title view scaling.

- ios/RNSScreenStackHeaderConfig.m
This change fixes the problem when navigation bar would not get properly updated for modal transitions. The problem was due to the fact that for modal transitions the animateAlongsideTransition block was not getting trriggered. This was noticeable on iOS versions before 13, as starting with iOS 13 we can use NavigationItem to specify most of the nav bar customization. On older versions however it is required that for a lot of navbar settings we need to update them durion animation. This wasn't the case for navigators presented modally. In case we show a modal we can update nav bar without animation because it actually renders a completely new navigation bar which isn't shared.
On top of that this PR fixes the problem with bridge not being set for header subviews.
> Fix updating navigation bar for modal transitions.

- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
This change allows for root screens of nested stack navigators on Android to display back button in the navigation bar. Navigating back is still possible using hw back because of the way hw back is handled by nested fragment containers. However, despite hw back functioning properly, before this change we would not allow for the soft back button to be rendered in the header. This change adds this possibility to keep software back consistent with the hw back button functionality. This behavior can still be disabled/adjusted using hideBackButton property of the header config component.
> Render Android back button for root screens of nested stack navigators.

- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
This change fixes a problem with native stack on Android where we'd display a sw back button on screens that are nested stack navigatodespite the fact those screens were the initial screens in the whole container stack. In #306 we introuced a change that would allow for displaying sw back in nested stacks, however that change did not handle the case where screen is a root screen of a container that is nested and placed as an initial screen in another container.
> Fix showing sw back button on nested stack on Android.

- android/src/main/java/com/swmansion/rnscreens/Screen.java
This change fixes the problem with missing text selection modals when text input component is rendered under screen container (reported in #205) . The reason turned out to be a problem with Android TextView implementation which expect the component to be attached to window at the moment when layout happens (see Editor.java#prepareCursorControllers and TextView.java$makeNewLayout). Apparently, within screens container layout will happen before the component of a given screen are attached (because attaching is managed by the fragment manager which delays the moment at which the screen is attached). As a result the textView component does not get a chance to fetch proper window layout params such that it can tell whether it should support selection mode or not. We workaround this issue by …
> Fix text selection inside screen container on Android.

- android/src/main/java/com/swmansion/rnscreens/Screen.java
We currently cannot take any adventage of saving and restoring fragment state because view hierarchy of the unmounted fragment is retained by RN core anyways. Skipping sabe/restore will allow us to avoid unnecessary serializiation/deserialization of the view hierarchy but will also help circumvent some bugs which comes from the side effects of restoring. One of the bugs have been reported in #162 and in that particular case restoring result in InputText change event being triggered with stale value. This was happening in the situation when we were going back to a screen with InputText component.
> Skip saving/restoring state for unmounted fragments.

- android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
The library would crash when the `mTopScreen` instance variable is null. This change checks if it null before calling the `getScreen()` method. It also marks the method as having a nullable return value. The only place this method is used is already setup to handle `null` responses.
> fix(android): NullPointerException crash due to null top screen

- android/src/main/java/com/swmansion/rnscreens/Screen.java
- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
- android/src/main/java/com/swmansion/rnscreens/ScreenFragment.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java
- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.java
- android/src/main/java/com/swmansion/rnscreens/StackFinishTransitioningEvent.java
- createNativeStackNavigator.js
- ios/RNSScreen.m
- ios/RNSScreenStack.h
- ios/RNSScreenStack.m
This change adds new event that gets dispatched from native stack when screen transitioning is finished.
The new event is used by react-navigation to update the library internal state that the triggered action has been finished. Previously we were relying solely on onAppear and onDisappear events, however those does not get triggered when new iOS 13 modals are used or when transparent modals are displayed. This is because with transparent modals the view below is still visible. We therefore needed another way of notifying the library that screen transition have finished despite the fact that disappear event couldn't be triggered.
As a part of this change I also refactored invalid ref cycle-break code on iOS which was ought to remove reference cycle between view and view controller. This …
> Trigger transition finish event from native stack

- android/build.gradle
- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
- android/src/main/java/com/swmansion/rnscreens/ScreenFragment.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
This change fixes two crashes related to fragment library. The first issue was a crash caused by return transaction started while the previous transaction was ongoing (e.g., quickly adding new screen on top of the stack and immediately dismissing it). The main fix was applied in the fragment library and therefore as a part of this change we update the dependency to fragment:1.2.1 which is the current latest stable version. As a result of the fragment library change we started observing other issue. The second issue was caused by the fact that under certain circumstances the view associated with a fragment couldn't been added despite it still being attached to a parent. This was resulting in a crash. This change adds a cleanup code that properly detaches the view: we do it in onCreateView …
> Fix several crashes in native stack related to fragment library

- createNativeStackNavigator.js
This change makes navigation screen wrapper to set absolute fill style for screen items wrendered within native stack. We obvserved an issue where screens are rendered with a versy small height when the initial style is not set properly on iOS. This change makes the screen default to full screen and only then be resized down in case navigation bars are set.
This is not an ideal solution and we likely want to come up with some solution that'd resolve issue with an additional layout passes for native screen and that does not depend on us relying on navigation wrapper but for now this fixes the problem for navigation wrapper consumers.
> Default to absolute fill for stack screen items.

- ios/RNSScreen.m
The previous condition was broken as under certain circumstances we would've receive a setReactFrame with no active screen rendered to only get the screen activate in a while. This resulted in the view dimention not being properly updated. This diff changes the condition and verifies whether a screen is mounted under UINavController or not. When not, we assume it is mounted under regular screen container and allow the frame to be adjusted from react.
> Fix condition that detected whether we should update screen frame on iOS

- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.java
- ios/RNSScreen.h
- ios/RNSScreen.m
- src/screens.d.ts
Allows you to choose additional modal presentation styles for iOS. It adds the ability to force a full screen modal or choose a "form sheet" style. This only affects iOS.
> feat: Add in additional modal types for iOS

- android/src/main/java/com/swmansion/rnscreens/ScreenFragment.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java
After fragment library upgrade we observed a regression caused by the screens that we navigate back to being invisible. This turned out to be a problem with view restore mechanism that we don't rely on. On native android the detached view state is dumped and then view's visibility is change to GONE after screen animated away. However, since we don't rely on view state restore and instead just reuse the whole view object, when navigating back we'd move to a view with visibility set to GONE. This change workarounds this problem in the method responsible for recycling views where we reset visibility flag back to VISIBLE.
> Android fix for invisible stack views after navigating back

- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
Fixes #343 
This change filters out non ScreenFragment instances when iterating through the list of installed fragments. The reason why other fragments can be added to the manager is that some libraries (e.g. glide) use fragment manager to store screen local data and attach to the screen lifecycle.
> check object instance of before calling detachScreen

- README.md
> docs: Replace `useScreens` with `enableScreens` for expo docs

- ios/RNSScreen.m
- ios/RNSScreenStackHeaderConfig.m
Since the config is only updated in the HeaderConfig view it will not get executed for stacks with no header. This fixes it by setting the prop directly in the Screen when the gestureEnabled prop is set.
> Fix gestureEnabled for modal with no header on iOS

- ios/RNSScreenContainer.m
- ios/RNSScreenStack.m
This change fixes the problem of container view controllers not being detached properly from its parent container VC. We fix this by detaching VC from didMoveToWindow. On top of that we also added a check to ensure the update of containers won't run unless JS batch is complete. This is to prevent partially updated headers.
> Fix detaching VC from parent VC.

- ios/RNSScreen.m
- ios/RNSScreenContainer.m
- ios/RNSScreenStack.m
This change fixes logic that we run when stack is moved to a window. Before we'd first attach stack to parent VC and then run updateContainer. This could've led to a buggy behavior in case the stack is mounted within other stack that is running a transition (e.g. dismissing a modal). In such a case setting initial push VCs would fail (because UIKit does not allow push to be modified while transitioning). Because of that stack would initialize with the dummy VC and the initial VC would get added to dismissedScreens (which is another side effect of the logic that keeps track of dismissed screens).
The fix was to add call to updateContainer before VC is added to parent. This makes it possible for push screens to be properly initialized (since VC is not yet added it does not know its parent …
> Fix didMoveToWindow logic.

- ios/RNSScreen.m
- ios/RNSScreenContainer.m
This chnage fixes the way we'd managed parent<>child VC relation. With this change in we hook child VC to parent in didMoveToWindow to match Stack behavior. We also wait with updating child view frame untill the child screen is attached. Finally we utilize RCTInvalidating interface to spot moments when screen controller is unmounted from react such that we can break reference cycle between screen and screen view (we don't do it in invalidate directly as sometimes we need to wait till transition end).
> Fix appear/disappear events for ScreenContainer and address memory leak issue

- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
This change fixes issue reported in #54. The issue was caused by the fragment transaction that run past the moment when container view is detached. This could happen when container is quickly added and removed as fragment transactions sometimes may take long time to execute. Unfortunately enqueued fragment transactions cannot be cancelled, so to make sure that transaction isn't run past container unmount we call executePendingTransactions right before the screen is detached.
> Fix no view found crash in fragment manager.

- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
This PR fixes an issue introduced by executePendingTransactions call added in #376
> Verify integrity of fragment manager before executePendingTransactions on detach.

- ios/RNSScreenContainer.m
Reverting that change as it turned out not to be necessary. At the moment of attaching screen we already have the frame set on the child VC. Updating it there again was cauinsg some visual glitches with old react-navigation screen container based implementation.
> Revert container frame update change from #354

- ios/RNSScreenContainer.m
UIkit calculated center of RCTView with transform offset. In order to avoid that we can use `reactSetFrame` method.
> Fix offset left after popping in JS stack on iOS

- ios/RNSScreenStack.m
- ios/RNSScreenStackHeaderConfig.h
- ios/RNSScreenStackHeaderConfig.m
This change fixes an issue when navigation header wasn't properly updated on mount time. The issue was due to us trying to animate transition while adding initial set of push VCs should never be animated. On top of that we observed that willShow delegate method wasn't getting triggered in some cases on old iOS devices. We added additional call to updating the header during mount time to workaround that.
> Properly update header for non-animated transitions and on old iOS devices

- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
Unders some conditions it is possible that back click listener is triggered after the fragment is already unmounted. This is due to the fact that the fragment lifecycle can be controlled from JS. We need to add extra null checks to prevent from crashing in this case. There is no need to handle this case separately as we cannot dismiss screen fragment that is already unmounted.
> Fix NPE crash in back click listener.

- ios/RNSScreenStack.m
Fixes a regression in https://github.com/software-mansion/react-native-screens/commit/f2caf02d8ce2ddd0c57e4efcb645c155fc1b104f. Not sure exactly why but we need to set `interactivePopGestureRecognizer.delegate` after adding the controller view or the swipe back gesture doesn't work. Probably just some UIKit oddity...
Fixes #385
> Fix back gesture for native stack on iOS

- createNativeStackNavigator.js
This change introduces REMOVE custom navigation command to be used for navigation wrapper. This command works similarily to POP however it does not pop views on top of the one passed as a key. It is important that when view is dismissed we only remove that screen from the stack and not accidently remove other views that might've been added on top in the meantime.
> Introduce custom remove action to cleanup dismissed screens.

- createNativeStackNavigator.js
Navigators in v4 need to import from 'react-navigation' package instead of '@react-navigation/xxx'.
> Fix wrong import for react-navigation in v4 stack

- Example/android/app/build.gradle
- android/build.gradle
Unfortunately we still need to require swipetorefresh as some of the material classes use it without listing swipetorefresh package as dependency. However it appears like we can put all the dependencies in the screen build.gradle and not require additional dependencies to be listed in the app's top level gradle.
> Reshuffle androidx dependencies not to require them being listed at the project level

- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
Previously we were resetting insets on Android while keeping default insets on iOS. This inconsistency was added to make both right and left side insets equal on Android in order to keep symmetry when both right and left icons are added. With this change we adapt default inset settings and apply it to the right end as well to keep symmetry. We also reset navigation start inset (distance between back button and title) in case title is not present. Thanks the latter change we get extra space for custom center subviews.
Fixes #332
> Use default insets for toolbar icons on Android to match iOS behavior

- android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
This change fixes a bug that made us determine enter animation based on the previous screen setting rather than the new screen being added.
> Fix enter animation on Android native stack

- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
Thi change fixes "fragment already added crash". The crash was caused by us calling onUpdate twice without fragment manager transaction queue getting flushed in between. This could've happened because in dismiss method we'd directly call onUpdate instead of going through markUpdated mechanism that enqueues onUpdate calls using choreographer and threfore guarantees that the method is called only once per frame. On top of changing dismiss behavior we also added call to flush fragment manager transactions queue in case there are some enqueued transactions at the point when onUpdate is called.
> Fix fragment added crash on Android native stack

- ios/RNSScreen.h
- ios/RNSScreen.m
- ios/RNSScreenStack.m
This change fixes an issue that was caused by us updating view controllers while there was an ongoing transition.
When changes to viewControllers where made during other transition, the navigation controller wouldn't update view controllers property immediately. As a result we could've get out of sync between stack subviews and ciewController property. And some of the stack logic relied on those two props being in sync. In particular, when we make a push transition we expected viewControllers to contain newly pushed item so that we won't push it again in the future. However, the item wouldn't be added immediately if the controller was running the transition.
To fix that there are two key changes introduced here:
1) when updating push controllers, we check if nav controller is already …
> Fix push updates during transition

- android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
This change fixes a bug which resulted in screens being kept in dismissed registry when dismissed using hw back button or the navigation back button. The problem was that we were removing Screen classes while adding ScreenFragments tothe registry. As a result the added entries where never being wiped.
> Remove screens from dismissed registry

- createNativeStackNavigator.js
This change fixes navigation state after native dismiss transition. We add 'immediate' flag to remove action as at the point dismiss event is triggered the transition has already completed.
> Fix focus events after native dismiss

- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java
If a screen has dynamic navigation options which changes from 'header: null' to be showing headers, the nav header is not appearing on Android platform. This PR aims to fix this issue.
> Fix nav header not showing after being hidden and unhidden on Android

- ios/RNSScreenContainer.m
Xcode Semantic Issue: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
> Xcode Semantic Issue: Block implicitly retains 'self'

- ios/RNSScreenStackHeaderConfig.h
- ios/RNSScreenStackHeaderConfig.m
- src/screens.d.ts
Currently you cannot set a different color to largeTitle then the one applied to the non large title. This PR adds `largeTitleColor` that allows setting the color for the largeTitle, following the existing `largeTitleFontFamily` and `largeTitleFontSize`.
> Apply custom color to largeTitle

- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
- android/src/main/java/com/swmansion/rnscreens/ScreenFragment.java
This change fixes the problem with the following crash noticed in the wild:
IllegalArgumentException No view found for id 0x1cb (unknown) for fragment ScreenStackFragment
After investigating we discovered the crash could occur under the following circumstances:
1. we have a stack with nested stack on the first screen
2. we push new screen on the top level stack
3. we immediately pop that screen and also remove the nested stack at the same time
4. the "immediate" action needs to be taken as we need to make sure the transition happens before the screen animaton is done
Under the above condition what'd happen is that the child fragment manager used for the nested stack will not move to "destroyed" state but instead will go from "detached" back to "attached" and will attempt to restore …
> Fix 'No view found for' exception on Android

- createNativeStackNavigator.js
- native-stack/types.tsx
- native-stack/views/HeaderConfig.tsx
Follow up PR to https://github.com/software-mansion/react-native-screens/pull/307. This PR allows native stack navigators to set the large title color as part of the `headerLargeTitleStyle` prop.
> Add large title color prop to native stack navigator's headerLargeTitleStyle

- ios/RNSScreenStackHeaderConfig.h
- ios/RNSScreenStackHeaderConfig.m
- package.json
- src/screens.d.ts
New props allowing to:
- define the background color 
- hide the shadow
of the header when the edge of any scrollable content reaches the matching edge of the navigation bar.
See [scrollEdgeAppearance](https://developer.apple.com/documentation/uikit/uinavigationitem/3198041-scrolledgeappearance)
> Implement largeTitle backgroundColor and hideShadow on iOS

- ios/RNSScreenStackHeaderConfig.m
This is a follow up to #333 with one formatting fix and also a change to avoid processing config twice in order to produce second appearance object.
> Minor updates for large title appearence handling

- ios/RNSScreenStack.m
Adding this check checks if the current window is not present outside of the container, which happens for `fullScreenModal` presentation type.
> fix: fullScreenModal presentation behavior

- ios/RNSScreenStackHeaderConfig.m
Fix a regression caused by #333
When `largeTitleBackgroundColor` we want to keep the current background color, setting to nil will cause it to become transparent.
Fixes #433 
Fixes #431
> Fix large header background when largeTitleBackgroundColor is not set

- ios/RNSScreenStackHeaderConfig.m
Changed UIFont to RCTFont in `headerTitle` and `largeHeaderTitle` for `expo-font` fonts to become available.
> feat: add RCTFont for expo-font integration

- README.md
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfigViewManager.java
- ios/RNSScreenStackHeaderConfig.h
- ios/RNSScreenStackHeaderConfig.m
- native-stack/README.md
- native-stack/types.tsx
- native-stack/views/HeaderConfig.tsx
- src/screens.d.ts
Added type definitions for `headerLeft` and `headerCenter` and an option allowing the custom left view to be rendered to the right of the back button requested in #445.
> feat: add types for header views and back button visibility prop

- ios/RNSScreenContainer.m
This change fixes RNSScreenContainer on iOS to prevent from reentering RN's event emitter which resulted in app not responding when used together with react-navigation v5.
The original issue coulv;e been reproduced when using simple react-navigation stack with two views and when attempting to swipe back from the detail view back to home. When that happened the app would go into a deadlock and stop responding.
The underlying issue was due to the fact that we'd trigger detach for screens that are going to be kept active just to make sure that screens are kept in the correct order. As a result, detach would trigger gesture handler to cancel swipe which as a result would attempt to generate an event. Since this whole process would already happen as a result of gesture handler event (during …
> Fix screen container to prevent event mutex lock

- package.json
- src/screens.web.js
- yarn.lock
Use `Animated.createComponent` on web instead of adding listeners manually. This means:
- No extra listeners
- One less dependency (`debounce`)
- Smaller component hierarchy since `Animated.View` used the HOC anyway
This also fixes some issues on web:
- Fix `NativeScreen` ignoring the `active` prop
- Fix `enableScreens(false)` not respected
- Fix custom `display` value not being respected since it was set to `flex`
- Fix view not re-appearing sometimes when `active` state changes
I couldn't find the reasoning for the previous implementation (https://github.com/software-mansion/react-native-screens/pull/88), so I assumed that it was an oversight. Lemme know if I'm missing something.
> Simplify the implementation on web

- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
When two `ScreenContainer`s have the same FragmentManager, which happens e.g. here #238, where Stack Navigator, which doesn't have screens enabled, has two screens, which both are Stack Navigators, so each has his own `ScreenContainer`, then, when performing an update or removing one of the `ScreenContainer`s, the other `ScreenContainer`s Screens will get removed due to current behavior in:
1. `performUpdate` detaches all Screens from FragmentManager that are not active or from the current `ScreenContainer`. In PR, we check if the Screens don't belong to any other `ScreenContainer`, and only then remove them. 
2. `removeMyFragments` removes all fragments from the FragmentManager of the `ScreenContainer` being removed. In PR, we remove only Screens from the current  `ScreenContainer`.
> feat: detach only screens from current container

- android/src/main/java/com/swmansion/rnscreens/Screen.java
- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
- android/src/main/java/com/swmansion/rnscreens/ScreenFragment.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java
This change attempts to fix a problem when screen fragment views aren't properly detached from their parents despite `recycleView` being invoked on them.
The final outcome of the issue was that the app would crash with an error that view it tries to attach already has a parent. We observed this issue happening in production but with no clear repro steps the problem appeared to be a bit cryptic. Our investigation shown that `recycleView` does not reset the parent because the view is not listed in `mDisappearingChildren` in `ViewGroup`'s implementation.
We suspect that the above was due to us triggering `clearDisappearingChildren` directly in `Screen` and hence this PR updates that. 
The second change we make here is that we no longer attempt to reuse the main fragment view (crated by …
> Proper container children cleanup

- Example/ios/Podfile.lock
- Example/package.json
- Example/yarn.lock
- native-stack/index.tsx
- package.json
- yarn.lock
Upgraded dependencies, from which the most crucial is @babel since the newer version is needed for React-Navigation to work (https://github.com/react-navigation/react-navigation/issues/7978#issuecomment-614766724). Also, used TS 3.8 syntax in native-stack to resolve #449.
> feat: upgrade dependencies and types

- ios/RNSScreenStack.m
In Expo client, which supports both light and dark styles, you can open an experience that has strict setting to light or dark mode. In that case experience's root view controller is set to the style specified by the user, however view controllers presented over it or added as a child have `overrideUserInterfaceStyle` set to `UIUserInterfaceStyleUnspecified` which causes the view controller to use the style that is set in system settings so we get some UIKit's views rendered with incorrect interface style 😞 This only affects view controllers presented modally, thus doing the same for pushed screens is not necessary.
@brentvatne prepared reproducible example: https://github.com/brentvatne/modal-example
Native stack's view controllers will inherit `overrideUserInterfaceStyle` from …
> Fix user interface style in native stack view controllers

- createNativeStackNavigator.js
Currently it was not possible to set a title color different than the tint color. This PR keeps the tintColor as the default header title color but also uses the headerStyle.color if defined.
> feat: support header title color

- ios/RNSScreenStack.m
Allows disabling modal animations via `stackAnimation: 'none'` on iOS. Android already handles this
Fixes #494
> Allow disabling modal animations

- createNativeStackNavigator.js
- native-stack/views/NativeStackView.tsx
If `ScreenStack`s of native-stack navigators have the same `FragmentManager` (because each of them is not under a different `Screen` component), changing a screen in one of the stacks pops one screen in the other stack because of the  https://github.com/software-mansion/react-native-screens/blob/master/android/src/main/java/com/swmansion/rnscreens/ScreenStack.java#L34 being called in both `ScreenStack`s by the `FragmentManager`. The workaround is to set `gestureEnabled` to false in `createNativeStackNavigator` on Android since React-Navigation handles hw back button and setting it will make the https://github.com/software-mansion/react-native-screens/blob/master/android/src/main/java/com/swmansion/rnscreens/ScreenStack.java#L283 not to be called because the screen is not dismissable …
> fix: disable gestures in native stack on Android

- src/screens.web.js
Remove the `defaultProps` since it is not necessary. Should fix #492.
> feat: remove default active prop on web

- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java
`mAppBarLayout` is created on every screen change so we need to check if the shadow shouldn't be disabled. This method is needed here since the if clause in `setToolbarShadowHidden` will return false e.g. when going back to the previous screen.
> fix: disable shadow if needed

- native-stack/types.tsx
- native-stack/views/HeaderConfig.tsx
backButtonImage prop is supported on the v4 native stack but is not exposed with v5 native stack. This PR brings that in the native-stack as well.
cc @WoLewicki @kmagiera @SRandazzo
> add support for back button image in native stack

- native-stack/types.tsx
- native-stack/views/NativeStackView.tsx
- src/screens.d.ts
`onFinishTransitioning` is actually implemented on the `ScreenStack` component and not `Screen`. I noticed since the event was never called in native-stack. I removed it since I don't think there is any infra for Stack based events and I doubt it was used anyway since it wasn't working at all.
> Fix type for onFinishTransitioning, remove event from native-stack

- native-stack/types.tsx
- native-stack/views/HeaderConfig.tsx
This PR will allow users to custom headerRight and headerLeft components using user's theme color.
For example, if I want a custom settings icon in headerRight to navigate to my settings page, I will be able to retrieve color from my custom theme. It's already available in ReactNavigation.
`colors.primary` is used by the back button so it makes sense to use it for headerRight and headerLeft.
The same logic may be applied to headerCenter (Imagine a custom TextComponent), we may apply colors.text in this case.
Let me know if you find this useful (or not), or if I can make it better to be integrated.
> Add props to headerLeft and headerRight

- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfigViewManager.java
- native-stack/README.md
- src/createNativeStackNavigator.js
- src/index.d.ts
- src/native-stack/types.tsx
- src/native-stack/views/HeaderConfig.tsx
Follow up from https://github.com/software-mansion/react-native-screens/pull/518 using @janicduplessis' suggested solution. The inset is applied by default to encourage developers to use translucent status bars on Android, which is typically a better experience for users and consistent with the iOS behavior.
> Add headerTopInsetEnabled prop that defaults to true to account for translucent status bars on Android

- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
This is mostly noticeable when using icons with ripple overflow.
Before
After
> Don't clip custom header subviews on Android

- ios/RNSScreenStackHeaderConfig.h
- ios/RNSScreenStackHeaderConfig.m
- src/createNativeStackNavigator.js
- src/index.d.ts
- src/native-stack/types.tsx
- src/native-stack/views/HeaderConfig.tsx
Added `appearance.backgroundEffect` options for blurring background in semi-transparent and transparent header.
PR also removes `configureWithDefaultBackground` option of appearance for translucent header since it applies `blurEffect` which causes problems (#520) and is not necessary since the prop for `blurEffect` will now be available.
> @wolewicki/add header blur effect

- ios/RNSScreenStack.m
According to https://developer.apple.com/library/archive/featuredarticles/ViewControllerPGforiPhoneOS/CustomizingtheTransitionAnimations.html, the final frame of the `toViewController`'s view should be set via `finalFrameForViewController:` method. It fixes the problem with the view, which we transition to, not respecting the header's height. Should resolve #326.
> fix: set final frame of fade animation

- ios/RNSScreenStackHeaderConfig.m
It is workaround for loading custom back icon when transitioning from a screen without header to the screen which has one. This action fails when navigating to the screen with header for the second time and loads default back button. It looks like changing the tint color of navbar triggers an update of the items belonging to it and it seems to load the custom back image so we change the tint color's alpha by a very small amount and then set it to the one it should have. Should resolve #550.
> fix: trigger color change on every update

- android/src/main/java/com/swmansion/rnscreens/Screen.java
- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
- android/src/main/java/com/swmansion/rnscreens/ScreenDisappearEvent.java
- android/src/main/java/com/swmansion/rnscreens/ScreenFragment.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java
- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.java
- android/src/main/java/com/swmansion/rnscreens/ScreenWillAppearEvent.java
- android/src/main/java/com/swmansion/rnscreens/ScreenWillDisappearEvent.java
- ios/RNSScreen.h
- ios/RNSScreen.m
- native-stack/README.md
- src/index.d.ts
- src/native-stack/types.tsx
- src/native-stack/views/NativeStackView.tsx
Implement [these](https://github.com/react-navigation/react-navigation/blob/bea14aa26fd5cbfebc7973733c5cf1f44fd323aa/packages/stack/src/types.tsx#L25) events in native stack, similar to the events available in js stack.
> [native-stack] Add transitionStart and transitionEnd events

- Example/App.js
- Example/ios/Podfile.lock
- Example/nativeNavigation.js
- Example/navigation/index.js
- Example/navigationTabsAndStack.js
- Example/package.json
- Example/yarn.lock
Not sure if we want to merge this (yet) since it replaces createNativeStackNavigator with the WIP native-stack.
I've tested all of the screens in the example and they work as expected. Not sure if we want to clean up the nesting of headers, but it does make navigating around and debugging simpler.
> Update example to react-navigation 5.x

- android/src/main/java/com/swmansion/rnscreens/Screen.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.java
- ios/RNSScreen.h
- ios/RNSScreen.m
- ios/RNSScreenStack.m
- src/createNativeStackNavigator.js
- src/index.d.ts
- src/native-stack/types.tsx
- src/native-stack/views/NativeStackView.tsx
Added animation options for `replace` action. At the update of the container, if the previous top screen is no longer on the stack and the new screen was not there before, it probably means that `replace` action was invoked, so we choose the animation of the new screen. Should close #394.
> feat: add replace animation

- android/src/main/java/com/swmansion/rnscreens/ScreenFragment.java
This PR fixes the problem with Android's soft keyboard staying open when going away from a screen with the focused text input.
The fix is to force keyboard to hide when the screen is detached.
The issue could've been reproduced on RN 62 on NativeStack example in the repo, but was only apparent on Android 5, while we haven't figured out a consistent way to reproduce on modern version of Android (we know the new versions were also intermittently affected). Repro steps:
1) Go to NativeStack example app on Android
2) Touch text field and see soft keyboard opens
3) Click "PUSH" button to navigate to the next screen – the keyboard would stay open despite the text field from the previous screen is gone
With this change in, the keybord is closed upon navigating away from the screen with the …
> Fix keyboard not hiding on RN 62+

- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
Overridded method that is called on the key event on which the developer menu on Android should be opened. Change added only for debug mode. Should resolve #276.
Clicking `cmd+m` on macOS in debug mode should open the developer menu on Android, but Action Bar wants to handle that key event in order to trigger `showOverflowMenu` on the Toolbar. We then override this method and call React's `showDevOptionsDialog` in it.
> feat: enable dev menu on Android

- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
- android/src/main/java/com/swmansion/rnscreens/ScreenFragment.java
This is a follow up fix after #592 where we attempted to fix the issue while introducing a regression in the way autoFocus is handled. That is, in case there was a text field with an auto focus in the next screen, the logic we added for screen dismissal would cause it to immediately lose focus.
This fix moves the logic responsible for keyboard force-dismiss to execute earlier – at the moment when we attempt to detach the previous screen. This way we can still rely on the focused child property to point to a correct children. Note that before, detaching a view would result in the child losing focus but the keyboard would stay open. We now use this fact and can verify that the focused children is the one being removed, and only in that case we ask system to hide the keyboard.
> Fix problem with keyboard staying open on Android after screen change

- ios/RNSScreenStack.m
Suggested by @kmagiera change that should resolve #432. 
We wait with adding to the parent controller until the stack is mounted and has its initial layout done. If we add it before layout, some of the items (specifically items from the navigation bar), won't be able to position properly. Also, the position and size of such items, even if it happens to change, won't be properly updated (this is perhaps some internal issue of UIKit). If we add it when the window is not attached, some of the view transitions will be blocked (i.e. modal transitions) and the internal view controller's state will get out of sync with what's on-screen without us knowing.
> fix: change update logic

- native-stack/README.md
Added info about measuring header's height on iOS. It can be helpful when using a translucent header. Should resolve #430.
> Add info about measuring header's height

- Example/ios/Podfile.lock
- README.md
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfigViewManager.java
- ios/RNSScreenStackHeaderConfig.h
- ios/RNSScreenStackHeaderConfig.m
- native-stack/README.md
- src/createNativeStackNavigator.js
- src/index.d.ts
- src/native-stack/types.tsx
- src/native-stack/views/HeaderConfig.tsx
Added RTL support for both platforms. In order to use `rtl` on Android, you have to add `android:supportsRtl="true"` in the manifest of your app.
On Android, if you set the above flag in the manifest, the orientation changes without the need to do it programmatically. On iOS, the direction defaults to `ltr`, and only way to change the direction is to do it programmatically. Should resolve #403.
> feat: add RTL support

- ios/RNSScreen.m
- ios/RNSScreenStack.m
- ios/RNSScreenStackHeaderConfig.m
Closes #493 with changes applied and the original author @hufkens credited. @WoLewicki let me know if this would be ok to merge, as we would be using screens on tvOS as well, and currently need `patch-package` for this. Additional flags by @gaborkajtar.
> Separate iOS specific code (Fix tvOS build)

- src/native-stack/views/NativeStackView.tsx
Following the implementation of `Modal` in `react-native`: https://github.com/facebook/react-native/blob/master/Libraries/Modal/Modal.js#L206, we attach each screen that is presented modally with an `AppContainer` that has a listener for `LogBox` and `ElementInspector`. This allows for these elements to pop up over the modal screen. There will be 2 `ElementInspectors` on the first screen due to 2 `AppContainer` components rendered in it. If we added check for if the `index === 0`, changing that index would unmount and remount screen content while calling e.g. `navigation.reset()`. Should resolve #268.
> fix: add appContainer to modal screens

- ios/RNSScreenStack.m
Followup of #600 changing the return condition. Should resolve #432.
> fix: change condition

- ios/RNSScreenContainer.m
We check if the screen is in modal since the method in the `if` clause will dismiss the modal screen when e.g. changing the screens in a bottom-tabs navigator nested in the modal.
> fix: check if in modal

- ios/RNSScreen.m
Based on https://github.com/wix/react-native-navigation/pull/1630 (since it fixes the same problem), we traverse the view in order to find ScrollViews and invoke `scrollViewDidEndDecelerating` on them. It is needed due to the situation where we start scrolling, and before the `ScrollView` stops decelerating, we move to another screen and as a result, the `scrollViewDidEndDecelerating` is not called on that `ScrollView`. Due to JS implementation of `ScrollView` (see https://github.com/software-mansion/react-native-screens/issues/102#issuecomment-638101039), it causes the elements of the `ScrollView` not to respond to touches after going back to that screen. 
More information can be seen in #102. It should also close #102.
> fix: scrollview behavior on transitioning between screens

- src/index.d.ts
- src/index.js
- src/index.native.js
Added `enabled` prop to give an option of enabling/disabling native `RNScreens` components per `ScreenContainer` and `Screen` (`Screen` must have the same value of `enabled` as its parent `ScreenContainer`).
> feat: add optional screens per navigator

- native-stack/README.md
`useSafeArea` hook is deprecated (replaced by [`useSafeAreaInsets`](https://github.com/th3rdwave/react-native-safe-area-context#usesafeareainsets)).
> Replace deprecated useSafeArea with useSafeAreaInsets in example

- RNScreens.podspec
Latest Xcode 12 fails to build while without a module to depend on `React-Core` directly hence this change is necessary for all native modules on iOS. This change requires React Native 0.60.2 or newer. For more details please check: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
> fix: Xcode 12 compatibility

- ios/RNSScreenStack.m
Change the update logic to include the case when the screen was mounted.
> fix: fullScreenModal

- android/src/main/java/com/swmansion/rnscreens/Screen.java
Added check for if there is WebView on the screen we are transitioning to. If there is, we don't change the layer type in stack navigator to avoid crash seen in #105.
> fix: webview in stack

- README.md
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfigViewManager.java
- native-stack/README.md
- src/index.d.ts
- src/native-stack/types.tsx
Currently, the `headerTranslucent = true` is only supported on iOS. With this PR the setting will also work on Android
> [Android] Add support for translucent header

- README.md
Related discussion: https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-700650097
> docs: note MainActivity.onCreate may need an override to avoid crashes

- src/createNativeStackNavigator.js
Added missing prop to the old version of `native-stack`. Based on #454 by @agarant.
> feat: add missing prop

- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfigViewManager.java
"#fff", "#ffffff" and `white` colors all have a value of "-1" on the native side, and `transparent` color has a value of "0", so using Integer and checking if it is `null` is the best option now.
> fix: remove check for background color

- Example/package.json
- Example/yarn.lock
- package.json
- src/native-stack/navigators/createNativeStackNavigator.tsx
- src/native-stack/types.tsx
- src/native-stack/views/NativeStackView.tsx
- yarn.lock
The PR updates the type annotations in native stack to match the following changes in React Navigation:
https://github.com/react-navigation/react-navigation/commit/7dc2f5832e371473f3263c01ab39824eb9e2057d
https://github.com/react-navigation/react-navigation/commit/f51086edea42f2382dac8c6914aac8574132114b
> fix: fix types for native stack to match latest react navigation

- src/native-stack/views/FontProcessor.expo.tsx
Added `@ts-ignore` and `eslint-disable-next-line import/no-unresolved` since `.expo.tsx` extension should be parsed only in Expo managed workflow, so `expo-font` should be always available there.
> fix: silence warning

- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java
Added a check for if `View` is a null. Should resolve #646.
> fix: check if view is not null

- ios/RNSScreenStackHeaderConfig.m
The font weight of the large title didn't match exactly to other common large titles in ios preinstalled apps.
> Fix system font weight for large title

- Example/ios/Podfile.lock
- android/src/main/java/com/swmansion/rnscreens/Screen.java
- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.java
- ios/RNSScreen.h
- ios/RNSScreen.m
- ios/RNSScreenContainer.m
- src/index.d.ts
- src/index.native.js
Changed the behavior of `active` prop to contain 3 options (values):
- 0: Screen is inactive
- 1: Screen is active, but is not visible and is not the first responder, or is transitioning
- 2: Screen is active and on top  
Added new prop `shouldUseActivityState` to differentiate between different implementations for other libraries to choose their implementation of JS side.
Should resolve #134, #120, #61. Should be also possible to use this as a workaround for #111. Should change the behavior described in #95 and probably resolve it. Should also close #130, #188 due to change of logic.
> feat: add optional navigators

- src/native-stack/types.tsx
Added change of types for stack actions in `native-stack`. Fixes #623.
Removed the explicit typings of `stack` router options and switched to `StackActionHelpers` which has all of them and `replace` action too.
> fix: add proper stack types

- Example/ios/Podfile.lock
- src/index.d.ts
- src/index.native.js
Updated the code by removing the deprecated method and code checking for unsupported RN versions (we support RN >= 0.60). It is a breaking change due to the removal of `useScreens`.
Removed `useScreens`, code checking for `UIManager[name]` and `Screen` implementation for RN < 0.57.
> feat: remove useScreens and outdated code

- ios/RNSScreenContainer.m
- ios/RNSScreenStack.m
This PR resolves an issue on iOS where we'd run a side-effect code in didMoveToWindow after the view has been invalidated (that is removed from the react-native tree). As a result we'd end up getting the following crash:
```
UIViewControllerHierarchyInconsistency child view controller:<UINavigationController: 0xREDACTED should have parent view controller:<RNSScreen: 0xREDACTED but requested parent is:<UINavigationController: 0xREDACTED>
```
The problem turned out to be related to the fact we've been attempting to reattach view to a different view controller than the one it's been previously attached to. However, the code that attaches it should not be run in the first place as the view has already been removed. After investigating it turned out that layout animations sometimes cause …
> Avoid running side-effects in didMoveToWin after invalidation

- ios/RNSScreen.m
This PR fixes a rarely occuring problem with a re-layout loop on header visibility change. The problem would surface in situation when we have a bottom tabs container inside of a stack, then we'd update header visibility such that it is hidden on some tabs and not on the other. As a result in some cases the screens code would end up re-layouting the screen with header disabled. The loop was caused by the code in RNSScreen where we call `updateBounds` as a result of native layout but also notify uimanager about view bounds change with `setSize` method. 
This PR breaks the loop by preventing screen container (not in stack) from calling `updateBounds`. We only need to notify uimanager about container size when the screen is rendered under navigation controller or as a native modal.
We update …
> Fix relayout loop on header show/hide change

- src/native-stack/views/NativeStackView.tsx
This fixes an incorrectly used prop to the `DebugContainer`. This was causing an appContainer to be rendered on every stackPresentation type causing a logbox to be rendered on every screen within a stack. So 1 on that main stack from RN and one additional one on every screen.
Change stackAnimation to stackPresentation on NativeStackView.ts props.
No evidence given as it is clearly visible via the code that this was being passed incorrectly. Logbox shown on modals.
> Multiple log box showing

- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.java
- ios/RNSScreen.m
- ios/RNSScreenContainer.m
Changed the logic of resolving `activityState` to take into account the initial `nil` value of it by passing the `NSNumber` instead of `int` (which was resolved to `0`) on iOS. The logic for restoring user interaction in `ScreenContainer` had to be changed too since it did not take into account going from value `1` to `2` for one of `Screen`s. It worked before because, at the end of the transition, the `activityState` of all `Screen`s was changed to `0` due to the initial `nil` pass, and then switched back to the proper value in the next evaluation, which resulted in `screenAdded` being set to `YES`. A similar situation, but without the need for change in `ScreenContainer` applies to Android. Fixes #702.
Added check for `nil` value of `activityState`. Added new prop `activityStateOrNil`. …
> fix: check if activityState is nil

- src/index.js
Export `shouldUseActivityState` in web. Fixes #701 .
Added `shouldUseActivityState` to the exported constants in `index.js` with `true` value, which can be useful when the support for `active` prop is dropped in the `react-navigation`.
> feat: export new prop for web

- .github/workflows/issue-validator.yml
Adds new GitHub action which validates every issue when they are `labeled`/`unlabeled`/`edited`(no need to launch it when an issue is created since it's being triggered by `labeled` event anyway).
For every specific label there are some sections required
- `bug` label requires sections:
- Description
- Steps To Reproduce
- Expected behavior
- Actual behavior
- Package versions
- `enhancement ` label requires section:
- Description
- `Question` label requires section:
- Description
A section is defined by any type of header(which is made using any number of `#` signs at the beginning of the line)
When there are any requirements that aren't fulfilled, the bot adds a comment and it keeps updating it/adding new ones until they are. It adds a new comment if there are no comments or the last …
> Add issue validator

- .eslintrc.js
- TestsExample/babel.config.js
- tsconfig.json
Added `native-stack` path to `tsconfig` and `.eslintrc.js` to properly resolve it in `TestsExample` project.
Updated `tsconfig.json` and `.eslintrc.js`.
Spot no eslint error in files of `TestsExample` project.
> fix: add native-stack to ts and eslint

- Example/nativeNavigation.js
- TestsExample/App.js
- TestsExample/ios/TestsExample.xcodeproj/project.pbxproj
- TestsExample/ios/TestsExample/Info.plist
- TestsExample/src/Test42.js
- TestsExample/src/Test642.js
- createNativeStackNavigator/README.md
- ios/RNSScreen.m
- ios/RNSScreenContainer.m
- ios/RNSScreenStack.m
- ios/RNSScreenStackHeaderConfig.h
- ios/RNSScreenStackHeaderConfig.m
- ios/UIViewController+RNScreens.m
- native-stack/README.md
- src/createNativeStackNavigator.js
- src/index.d.ts
- src/native-stack/types.tsx
- src/native-stack/views/HeaderConfig.tsx
Added orientation management on iOS.
Changed implementation details of `findChildVCForConfig` to always return the exact VC that should be used.
Added checks for `OS_TV`, where these APIs are unavailable.
`Test42.js` in `TestsExample` project.
> feat: add screen orientation on iOS

- ios/RNSScreenStackHeaderConfig.m
Added better handling of iOS < 13 for `statusBarStyle`. It now resolves to `UIStatusBarStyleLightContent` when `RNSStatusBarStyleLight` passed, and `UIStatusBarStyleDefault` otherwise, since these are the options available in iOS < 13. Fixes #755.
Updated `RNSScreenStackHeaderConfig.m`.
`Test642.js`.
> feat: add default status bar style

- README.md
- createNativeStackNavigator/README.md
- native-stack/README.md
- src/createNativeStackNavigator.js
- src/index.d.ts
- src/native-stack/types.tsx
Added missing props to `native-stack` and updated READMEs.
Updated all `README`s to mirror the available options. In `createNativeStackNavigator.js` changed the option for `largeTitleBackgroundColor` to be the same as with the newer `native-stack` and added missing prop.
> feat: update READMES and add missing props

- TestsExample/App.js
- TestsExample/src/Test750.js
- ios/RNSScreen.m
Suggested by @kmagiera change adding setting frame in the `viewWillAppear`. It ensures that the `parentViewController` is set when trying to set the frame, and if the parent is not `UINavigationController`, then the frame is properly set. It fixes the issue that appeared after #712 was merged, where there is a check for `parentViewController` not being `nil` introduced. The issue can be spotted and should fix #750.
Added setting frame in `notifyWillAppear`.
-->
`Test750.js` in `TestsExample` project.
> feat: add setting frame in notifyWillAppear

- TestsExample/App.js
- TestsExample/src/Test726.js
- ios/RNSScreenContainer.m
This change attempts to resolve the issue from #726 (see https://github.com/software-mansion/react-native-screens/issues/726#issuecomment-757879605). The issue itself is similar to what we fixed in #473, which is preventing deadlock on `sendEvent` mutex. We try to prevent it here by making the `updateContainer` method run asynchronously on the main queue.
Changed `ScreenContainer.m` to use `dispatch_async(dispatch_get_main_queue(), ...)` instead of `RCTExecuteOnMainQueue`.
`Test726.js` in `TestsExample` project.
> feat: add async container update on ios

- README.md
- TestsExample/src/Test42.js
- android/src/main/java/com/swmansion/rnscreens/Screen.java
- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
- android/src/main/java/com/swmansion/rnscreens/ScreenFragment.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfigViewManager.java
- createNativeStackNavigator/README.md
- native-stack/README.md
- src/index.d.ts
- src/native-stack/types.tsx
`SC` will stand for `ScreenContainer`. Added orientation management on Android. On every update of `native-stack` or navigators with using `SC` we check if there is orientation change needed. We do it by checking the top `Screen` and, if there is no child `HeaderConfig` (which has the priority) and there is a `HeaderConfig` above the `Screen`, changing the orientation according to it. If there are no child `SC`s in the `Screen` in `onContainerUpdate` even though the `Screen` has a child `SC`, it means that the child has not fired `onAttachedToWindow`, where the registration of child `SC` happens. It is not a problem, because then the correct update of orientation will be fired in `onAttachedToWindow` of the child `Screen` `HeaderConfig`, if it exists.
- Added `getHeaderConfig` for unified …
> feat: android orientation management

- ios/RNSScreenStackHeaderConfig.m
replace deprecate bridge.imageloader API, use `moduleForClass:`
change ios file RNSScreenStackHeaderConfig.m
> refactor: replace deprecated API

- .eslintrc.js
- TestsExample/App.js
- TestsExample/babel.config.js
- TestsExample/metro.config.js
- TestsExample/src/Test765.js
- babel.config.js
Based on help from @satya164 we change the resolving logic for babel and metro, leading to ability of using both react-navigation v4 and v5 in `TestsExample` project.
Added changes to `.eslintrc.js`, `babel.config.js` and `metro.config.js`.
`Test765.js` in `TestsExample` project.
> fix: change babel and metro resolvers logic

- android/build.gradle
After consultation with @kmagiera we came to a conclusion that keeping `buildscript` is not necessary since it would only be used when the project is a `rootProject` and `react-native-screens` are not meant to be used as a standalone project.
Removed `buildScript` from `android/build.gradle`
> feat: remove buildscript from main build.gradle

- TestsExample/ios/Podfile.lock
- TestsExample/package.json
- TestsExample/src/Test642.tsx
- TestsExample/tsconfig.json
- ios/RNSScreen.m
- ios/RNSScreenStackHeaderConfig.m
- package.json
- tsconfig.json
PR introducing 3 changes. 
- disabled the ability to modify the status bar appearance in non-fullScreen modals since it destroys the animation (see gifs in #767) and introduces the necessity to control the color of status bar in every modal, which does not work well e.g. with phones with iOS <13 since there are only fullScreen modals there. The system seems to pretty well deal with all the cases where this change could be problematic, so I think it is worth to do this.
- extended an `if` clause in `RNSScreenStackHeaderConfig.m` to fix the bug when trying to change options via `navigation.setOptions` while being in `fullScreenModal`. Till now, when the code reached the changed line, if did not go into `if` due to `nav` being `nil` for `fullScreenModal`, which resolved to `nextVC` also …
> feat: change modal logic

- src/native-stack/types.tsx
Suggested by @satya164 revert of `NativeStackNavigationConfig` to an empty object. It makes the `native-stack` `Navigator` accept only `screenOptions`, just how it is supposed to do. Should fix #809.
Changed `native-stack` `types.tsx` to properly show props for navigator.
Pass props other than `screenOptions` to `native-stack`'s `Navigator` component.
> fix: restore the proper type for NavigationConfig

- android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
Added a check for `!mFragmentManager.isDestroyed()` in `ScreenStack.java` since the code inside of `if` clause requires it. Not adding this sometimes resolves in crash seen in #751. Unfortunately it is not reproduced yet.
Should fix #751.
`!mFragmentManager.isDestroyed()` in `ScreenStack.java`.
Added
> feat: add check for isDestroyed

- src/native-stack/views/FontProcessor.expo.tsx
- src/native-stack/views/FontProcessor.tsx
Expo is moving away from using the `.expo` extension to identify "managed" apps in SDK 41, so we are patching libraries that currently depend on the extension to fork behavior.
The solution used here is more generic - we use the same `process` function that is set via `StyleSheet.setStyleAttributePreprocessor` [(the method we use in Expo managed apps to scope fonts)](https://github.com/expo/expo/blob/fb198eb79ddf6a2a6f51b2ca2dfa0788c5fa769a/packages/expo/src/Expo.fx.tsx#L36-L39.  In the (unlikely) case that other (non-Expo) folks are depending on this behavior it will also work out of the box in native-stack.  I'm not crazy about doing a deep import into React Native like this, but there is no public API for getting StyleSheet preprocessors from React Native.
An alternative approach could …
> Use ReactNativeStyleAttributes to process fontFamily

- TestsExample/App.js
- TestsExample/src/Test831.tsx
- ios/RNSScreenStackHeaderConfig.m
Moved check for `rtl` to before the `return` option with header not shown to be able to apply `rtl` transition between screens.
`Test831.tsx` in `TestsExample` project.
> fix: rtl transition without header on iOS

- TestsExample/App.js
- TestsExample/src/Test817.tsx
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackViewManager.java
Added change to `ScreenStackHeaderConfig.java` to expose the `Toolbar`, of which the `ScreenStackHeaderSubview`s are the children. It is needed since the `Toolbar` is not a child of `Screen` in the view hierarchy, therefore its children are not subscribed to the transition by default. Then, in the [`prepareOutTransition`](https://github.com/software-mansion/react-native-screens/blob/master/android/src/main/java/com/swmansion/rnscreens/ScreenStackViewManager.java#L39), we add a check for `ScreenStackHeaderConfig` and apply the transition to the children of its `Toolbar` making them stay on the screen for during the transition of going back. Fixes #817.
Added method to get the `Toolbar` of `ScreenStackHeaderConfig`.
Added check for getting the `Toolbar` in `prepareOutTransition` and firing …
> fix: make header subviews subscribe to transition

- README.md
- createNativeStackNavigator/README.md
- native-stack/README.md
Added information in READMEs that mixing `containedModal` and `containedTransparentModal` with different types of modals in one flow can lead to crashes.
- Updated `README.md` docs
- Updated `native-stack/README.md` docs
- Updated `createNativeStackNavigator/README.md` docs
> docs: add warning about mixing modal types

- TestsExample/App.js
- TestsExample/src/Test844.tsx
- ios/RNSScreenStackHeaderConfig.m
Reverted the change of updating the header introduced in #798 and added proper check. Should fix #844.
Changed the condition in `RNSScreenStackHeaderConfig` to only allow change without the `navctr` if we are in a `fullScreenModal`.
`Test844.tsx` in `TestsExample` project.
> fix: don't update header without navctr

- Example/src/screens/HeaderOptions.tsx
- createNativeStackNavigator/README.md
- native-stack/README.md
- src/native-stack/types.tsx
- src/types.tsx
Unified the descriptions of types and removed wrong information about header back button.
Modified main `types.tsx` and changed READMES and `native-stack/types.tsx`.
> fix: unify types definitions

- .eslintrc.js
- src/index.tsx
Change the logic of displaying the Screen on web to only detach the `Screen` if the `activityState` is `0`. It should prevent detaching views for during the transition.
Changed `index.tsx` to match the implementation from `react-navigation`.
It is needed to change the implementation of `react-navigation`'s navigators to use `react-native-screens` on web too to test this change.
> fix: detach screen only on activityState 0

- src/index.native.tsx
- src/index.tsx
Changed the logic to make the `enabled` prop set to `true` result in using native code even if `ENABLE_SCREENS` is set to `false`.
Changed `index.native.tsx`.
Don't call `enableScreens()` in your app and don't pass `false` to `detachInactiveScreens` in your navigator and it will resolve in native `react-native-screens` components being used.
> feat: make enabled take precendce over ENABLE_SCREENS

- src/index.native.tsx
Enabled native components of `react-native-screens` by default. It results in no need of calling `enableScreens()` at the top of your app to use them 🎉 
Changed `index.native.tsx`.
Do not call `enableScreens()` at the top of your app and spot that native components are used.
> feat: enable screens by default

- README.md
- createNativeStackNavigator/README.md
- native-stack/README.md
Calling `enableScreens()` at the top of your application is no longer required since `v3.0.0` and this should be reflected in the documentation.
- Updated README.md
- Updated native-stack/README.md
- Updated createNativeStackNavigator/README.md
> docs: remove from READMEs info about enabledScreens being required

- TestsExample/App.js
- TestsExample/src/Test865.tsx
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
Intricate logic for animation opening and closing screens in Android introduced incontinency in `navigation.reset`. 
The issue is described in detail in #865.
Fixes https://github.com/software-mansion/react-native-screens/issues/865.
- (Hopefully) simplified transition logic in Android.
https://user-images.githubusercontent.com/39658211/113130079-ef360800-921b-11eb-9aa8-ce6fd8c43cb3.mov
https://user-images.githubusercontent.com/39658211/113129416-2657e980-921b-11eb-9e99-2497e5ce0d73.mov
Provided `Test865.tsx` in `TestsExample` project.
> fix: rework open/back animation logic on Android

- src/native-stack/index.tsx
- src/native-stack/types.tsx
When working on my pet project I found out that Native Stack has no type similar to `StackScreenProps` shorthand that I often use with JS Stack.
I added one type to typings of native stack, I copied it from JS Stack and updated it to use Navigation Prop type from native stack instead of the JS one.
n/a
```typescript
import { NativeStackNavigationProp } from 'react-native-screens/native-stack';
type ProfileScreenNavigationProp = NativeStackNavigationProp<
RootStackParamList,
'Profile'
>;
interface Props = {
navigation: ProfileScreenNavigationProp;
};
export const ProgileScreen: React.FC<Props> = () => {
// ...
```
```typescript
import { NativeStackScreenProps } from 'react-native-screens/native-stack';
type Props = NativeStackScreenProps<RootStackParamList, 'Profile'>;
export const …
```
> add native stack screen props rype

- TestsExample/App.js
Added missing import statement in `App.js` for Test852 in TestsExample project.
> fix: add missing import in TestsExample

- src/index.native.tsx
Enable `react-native-screens` only on `Android`, `iOS` and `web`.
Added checks for `Android` and `iOS` in `index.native.tsx`.
> fix: whitelist supported platforms

- TestsExample/App.js
- TestsExample/src/Test881.tsx
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
When a screen is added to an empty stack it shouldn't have any animation. 
The issue is described in detail in #881.
Fixes #881.
Changed the default value of `stackAnimation` to `null` in `ScreenStack.java` and handle it accordingly.
`Test881.tsx` in `TestsExample` project.
> fix: properly handle first screen on stack

- TestsExample/App.js
- TestsExample/android/app/build.gradle
- TestsExample/android/app/src/main/java/com/testsexample/MainApplication.java
- TestsExample/babel.config.js
- TestsExample/ios/Podfile.lock
- TestsExample/package.json
- TestsExample/src/Test898.tsx
- TestsExample/yarn.lock
Added `react-native-reanimated` v2 to the `TestsExample` project.
All the configuration needed to do it for version `2.1.0`.
`Test898.tsx`.
> feat: add rea2 to TestsExample

- ios/RNSScreen.m
- ios/RNSScreenStackHeaderConfig.m
This addresses bugs such as #528 where header content is incorrectly positioned on initial load or after rotation. I was experiencing these issues in my current app, and when I looked at the XCode view debugger I could see that `RNSScreenStackHeaderConfig` subviews had their `.frame.origin.x` property set to a non-zero value that moved them out of place.
I'm fairly new to React Native and very new to this codebase, so I haven't totally got to the bottom of what's happening here. My guess/theory is that RN layout code is setting the position of these views as if they're part of of the regular view hierarchy, even though they're meant to be managed by a `UINavigationBar`. Rather than trying to fix this at a deeper level and risk introducing side effects, I've added a small workaround.
Fixes …
> Fix broken layout for header subviews in iOS

- Example/ios/Podfile.lock
- Example/package.json
- Example/yarn.lock
- TestsExample/ios/Podfile.lock
- TestsExample/package.json
- TestsExample/yarn.lock
Bump react-native version `0.64` -> `0.64.1` in `TestsExample/` and `Example/` projects.
This version includes fixes for iOS build problems in Xcode 12.5.
> chore: bump react-native version to 0.64.1

- src/createNativeStackNavigator.tsx
- src/native-stack/navigators/createNativeStackNavigator.tsx
- src/native-stack/views/NativeStackView.tsx
Removed the check for enabling RNScreens for `native-stack` v4 and v5. It is not necessary since there is no point in using `native-stack` and not enabling the `react-native-screens` for its' components.
> feat: remove check for screens enabled in native stack

- Example/src/screens/Modals.tsx
- Example/src/screens/SearchBar.tsx
- Example/src/screens/StackPresentation.tsx
Added platform-dependent checks for hiding headers in modal screens in the Example project.
Modals, SearchBar and StackPresentation playgrounds in the Example project.
> fix: add headerShown check in modals in Example

- README.md
- guides/CONTRIBUTING.md
To save some time asking for not deliberately ignoring the issue template I've decided to add a short contributing guide to which we could refer people to.
- Added CONTRIBUTING.md to `guides/`
- Added a link to contributing to the main README
> docs: add CONTRIBUTING guide

- RNScreens.podspec
When building for iOS with `use_frameworks!` in the project Podfile Xcode became fussy about explicitly specifying the framework dependencies rather than just the "React" target. In general RN modules have changed to depend on "React-Core" and all is fine. However, modules that use classes that aren't in the "React-Core" pod need to name all their dependencies explicitly. I've checked and every class that is currently imported by the native iOS code comes from "React-Core" except for RCTImageView and RCTImageLoader. These are both in the "React-RCTImage" framework/pod. Added this to the dependencies to fix linker errors for some projects that use this module.
Fixes #842 .
Update RNScreens.podspec to add the missing dependency.
This should change nothing for most projects, but those with …
> Add missing dependency on React-RCTImage pod.

- TestsExample/App.js
- TestsExample/ios/Podfile.lock
- TestsExample/src/Test593.tsx
- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
- android/src/main/java/com/swmansion/rnscreens/ScreenFragment.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java
PR made on top of #593 fixing the correct order (always willAppear/willDisappear before appear/disappear) on Android to match iOS where it is already correct.
- Added dispatching `onAppear` and `onDisappear` on the ui thread suggested in #593 both for normal and `none` transitions.
- Added code in `ScreenStack` making sure that the `willAppear` and `appear` are always dispatched when the new stack appears.
- Changed adding parent fragment order to be present when we setup fragment manager since we sometimes want to know if it is nested in `onUpdate` method.
`Test593.tsx` in `TestsExample` project.
> fix: make events dispatch in correct order

- Example/ios/Podfile.lock
- Example/src/screens/Animations.tsx
The new release of `react-native-screens` will come with two new `stackAnimation` props on iOS - `simple_push` and `slide_from_bottom`.
- Added `simple_push` and `slide_from_bottom` to Animations example.
> feat: update Animations example

- native-stack/README.md
- src/native-stack/types.tsx
This PR deprecates the `appear` event because of its redundancy to more powerful `transitionStart`/`transitionEnd` events.
> feat: deprecate appear event

- TestsExample/ios/Podfile.lock
- ios/RNSScreen.m
When the swipe to go back is cancelled, all lifecycle events are called on both transitioning screens and we don't want them to be sent to JS. In the future, we can send e.g. `swipeCancelled` event in such case if it is requested by users.
Added logic catching the case of cancelled swipe and not calling notification methods then.
`Test593.tsx` in `TestsExample` project.
> fix: no events when swipe cancelled

- Example/yarn.lock
- TestsExample/yarn.lock
- yarn.lock
Bumping packages from `dependabot`.
> chore(deps): bump browserslist from 4.16.1 to 4.16.6 (#953)

- TestsExample/src/Test758.tsx
- createNativeStackNavigator/README.md
- guides/GUIDE_FOR_LIBRARY_AUTHORS.md
- ios/RNSSearchBar.m
- native-stack/README.md
- src/types.tsx
Added option to set color of text in iOS search bar.
Added new prop to `SearchBar.m` and types.
Added checks for availability of iOS 13 in proper places.
`Test758.tsx` in `TestsExample` app.
> feat: add search field color

- package.json
- src/native-stack/views/NativeStackView.tsx
- yarn.lock
Added changes from https://github.com/react-navigation/react-navigation/blob/main/packages/native-stack/src/views/NativeStackView.tsx#L28 to display warning about header in modal only after the prop has been changed, so it will not display the warning if the user specified `headerShown: true` in the options for the screen.
`Test800.tsx` in `TestsExample` project.
> fix: dont warn about header if prop not changed

- Example/App.tsx
Example app uses the newest version of `react-native-screens` thus it no longer requires to call `enableScreens()`.
Fixes #973
> feat: remove enableScreens from example app

- Example/ios/Podfile.lock
- Example/package.json
- Example/yarn.lock
- TestsExample/ios/Podfile.lock
- TestsExample/package.json
- TestsExample/yarn.lock
This PR bumps version of react-native to `0.64.2` in Example and TestsExample projects.
> chore: bump react-native version to 0.64.2

- TestsExample/ios/Podfile.lock
- ios/RNSScreenContainer.m
PR reverting async container update on iOS (#777) since it caused multiple problems: 
- https://github.com/software-mansion/react-native-screens/issues/905#issuecomment-860647715
- https://github.com/software-mansion/react-native-screens/issues/972#issuecomment-861463305
- https://github.com/software-mansion/react-native-screens/issues/943#issuecomment-845479999
The revert should not reintroduce the freeze from #726 since it was connected to disabling user interaction in `updateContainer` method, which we no longer do.
Removed `async` dispatching of `updateContainer`.
`Test726.js` in `TestsExample` project to see the previous freeze not occur.
> revert: async container update

- TestsExample/App.js
- TestsExample/src/Test913.tsx
- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
Suggested by @kmagiera change to `ScreenContainer.java`, altering https://github.com/software-mansion/react-native-screens/pull/477/, switching `removeAllViews();` to `removeViewAt(i);` in order to fix the case of calling `onDetachedFromWindow` multiple times in the child `Screen`s, which can be seen in `Test913.tsx`. This behaviors occurs due to the logic of `removeAllViews` method, which does not check if the child views are not already detached when the method is called, whereas the check is present in `removeViewAt` method (see https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/ViewGroup.java#5559 which is not present in https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/ViewGroup.java#5771).
`Test913.tsx` …
> fix: make sure we only call onDetachedFromWindow once

- android/src/main/java/com/swmansion/rnscreens/ScreenFragment.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java
PR fixing navigating in nested stack without animation, which did not trigger navigation events due to check for being nested, resolving in never dispatching those events there. PR switches it to a check inside parent fragment and makes it decide whether it should dispatch navigation events in a child.
We don't do it if the child has `none` animation and we are going forward since events will be dispatched in child via `onCreateAnimation` of `ScreenStackFragment` then.
`Test593.tsx` with `stackAnimation == 'none'`.
> fix: no animation in nested stacks

- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java
This MR fixes #1008 
Instead of assigning PixelUtil.toPixelFromDIP to static variable, use it when it is necessary
> Access to PixelUtil.toPixelFromDIP when it is necessary

- TestsExample/src/Test1032.tsx
- ios/RNSScreenStack.m
Fixes #1022
Adds event cancelation only when gesture should be recognized.
Test1032.tsx
> fix: touch event canceled with gesture disabled

- TestsExample/src/Test1036.tsx
- ios/RNSSearchBar.m
Fixes #1027 on iOS 13 and higher
Removes manual cancel button hiding/showing and uses built in function.
Test1036.tsx
> fix: Search bar returns to an incorrect position after losing focus (fix for iOS 13+)

- ios/RNSScreenStack.m
We found a typo in method call.
Fixes typo
> fix: Fixes typo in method name for TV-OS

- README.md
- native-stack/README.md
Since React-Navigation v6 documentation of `native-stack` is placed in the official [React-Navigation documentation](https://reactnavigation.org/docs/native-stack-navigator). This PR directs developers to the correct place.
> docs: add information about react-navigation v6

- src/native-stack/navigators/createNativeStackNavigator.tsx
Since react-navigation v6 `@react-navigation/native-stack` is the preferred way of using native-stack. Nevertheless, nothing stops developers from using `react-native-screens/native-stack` with RNv6. This PR adds a check if react-native-screens' native-stack is used with RNv6 and warns about this.
Bump @react-navigation/native in TestsExample to use v6.
> feat: warn when using native-stack from rns in v6

- .github/workflows/android-build-test.yml
- .github/workflows/ios-build-test.yml
- .github/workflows/main.yml
- .github/workflows/tv-os-build-test.yml
Makes CI checks more efficient
> Improves CI checks

- Example/.flowconfig
- Example/android/app/build.gradle
- Example/android/build.gradle
- Example/android/gradle.properties
- Example/android/gradle/wrapper/gradle-wrapper.properties
- Example/index.js
- Example/ios/Podfile
- Example/ios/Podfile.lock
- Example/ios/ScreensExample.xcodeproj/project.pbxproj
- Example/metro.config.js
- Example/package.json
- Example/yarn.lock
- TestsExample/.flowconfig
- TestsExample/android/app/build.gradle
- TestsExample/android/build.gradle
- TestsExample/android/gradle.properties
- TestsExample/android/gradle/wrapper/gradle-wrapper.properties
- TestsExample/babel.config.js
- TestsExample/ios/Podfile
- TestsExample/ios/Podfile.lock
- TestsExample/ios/TestsExample.xcodeproj/project.pbxproj
- TestsExample/package.json
- TestsExample/yarn.lock
This PR bumps version of react-native to `0.65.1` in Example and TestsExample projects.
> chore: bump react-native version to 0.65.1

- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt
Currently setting `stackAnimation: flip` results in exception on Android. It should resolve to default android animation instead.
- Resolve `flip` stackAnimation to default Android animation.
> fix: no exception while using flip animation on Android

- android/src/main/java/com/swmansion/rnscreens/ScreenFragment.kt
Fix a bug introduced in #890 where when container is already null, the app crashes.
> fix: send progress when container is null

- .github/workflows/android-build-test.yml
- .github/workflows/ios-build-test.yml
- .github/workflows/main.yml
- .github/workflows/tv-os-build-test.yml
Adding `workflow_dispatch` event is required to trigger CI manually.
https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
> feat: add possibility to run CI builds manually

- android/build.gradle
`jcenter()` repository was removed in #1042. Lack thereof results in failing `./gradlew assembleRelease` in `android/` directory.
Fixes #1092
- Brought `jcenter()` repo back to `build.gradle` file
Remove `jcenter()` from `android/build.gradle` and run `./gradlew assembleRelease` or `./gradlew assembleDebug`.
> fix: add jcenter() to build.gradle

- package.json
- windows/RNScreens/RNScreens.cpp
- windows/RNScreens/ReactPackageProvider.cpp
- windows/RNScreens/Screen.cpp
- windows/RNScreens/ScreenContainer.cpp
- windows/RNScreens/ScreenContainerViewManager.cpp
- windows/RNScreens/ScreenStack.cpp
- windows/RNScreens/ScreenStackHeaderConfig.cpp
- windows/RNScreens/ScreenStackHeaderConfigViewManager.cpp
- windows/RNScreens/ScreenStackViewManager.cpp
- windows/RNScreens/ScreenViewManager.cpp
- windows/RNScreens65.sln
Fixes #1097 
#1009 broke a number of things:
- it added a linting step to precommit, but the commands used in the precommit are linux commands that won't work on Windows
- the linting rules change the order of #includes, which breaks precompiled headers
Also adding a 0.65 solution (Note: I didn't recreate the project, I just manually removed/added the project references like fmt, etc.)
> Get react-native-screens building for/on Windows again

- TestsExample/src/Test758.tsx
- createNativeStackNavigator/README.md
- guides/GUIDE_FOR_LIBRARY_AUTHORS.md
- ios/RNSSearchBar.m
- native-stack/README.md
- src/types.tsx
Added option to change `Cancel` button text in searchBar. Requested in https://github.com/software-mansion/react-native-screens/issues/1081.
`Test758.tsx`
> feat: add cancel button text

- ios/RNSSearchBar.m
For some reason when `searchBar`'s controller is instantiated with `new`, the `searchBar` itself does not appear on `iOS` 12. Changing it to `[[UISearchController alloc] initWithSearchResultsController:nil]` resolves the issue.
`Test758.tsx` with `iOS 12`.
> fix: make search bar appear on iOS 12

- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenContainerViewManager.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt
- android/src/main/java/com/swmansion/rnscreens/ScreensShadowNode.kt
Added delayed update logic to `ScreenContainer` in order to resolve issues with too early detached nested navigators when going back from a screen in `native-stack` with nested different navigators. This change was part of synchronous fragment updates introduced in #1066. Going back like that triggers `removeAllScreens` code of the nested navigator and it resolved in detaching all of the child screens before the update of `native-stack` was dispatched, leading to blank screen from the start of navigation.
`Test860.tsx` to see that without this change the nested navigators are detached at the start of transition.
> fix: delay ScreenContainer updates in same manner as ScreenStack

- android/build.gradle
- android/spotless.gradle
Fixes issue mentioned in https://github.com/software-mansion/react-native-screens/pull/1118 with clashing Spotless configuration when developer's app also uses Spotless. 
This PR makes spotless only load within `react-native-screens` project.
Moved spotless configuration to separate file and load it conditionally using `apply from` syntax.
init a RN project, add 
```
plugins {
id "com.diffplug.spotless" version "5.14.1"
}
``` 
to build.gradle
`yarn add react-native-screens`, and try to build.
> fix: apply spotless conditionally

- .github/workflows/ios-e2e-test.yml
Fixes github actions concurrency group for ios e2e
> chore: Change concurrency group name

- .github/workflows/tv-os-build-test.yml
Fixes concurrency group name for tvOS
> chore: Change concurrency group name for tv os

- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.kt
fixes an error when building for android on different kotlin versions / lint setups
I have changed the project's gradle setup to match the `Example/` in this repo, but still getting the error... but even though this could be kotlin version issue, it seems to me that `context` can't be null here anyways, so figured I'd open a PR for review 🤷 
`context` is never null according to the constructor, so I just changed one instance of `Context?` to `Context`
> fix: context is never null

- android/build.gradle
This PR fixes build errors in detox by enabling desugaring in Android.
Thanks to @dantenol for suggesting this fix.
Fixes https://github.com/software-mansion/react-native-screens/issues/1078
- Enabled desugaring in android/build.gradle wtih ⬇️
```
compileOptions {
sourceCompatibility JavaVersion.VERSION_1_8
targetCompatibility JavaVersion.VERSION_1_8
}
```
> fix: enable desugaring of java 8 bytecode

- .github/workflows/ios-e2e-test.yml
- Example/package.json
When iOS e2e test fail save screenshots as artifacts
> chore: Adds screenshot artifact to iOS e2e

- Example/android/build.gradle
- TestsExample/android/build.gradle
- android/build.gradle
This PR downgrades kotlin version to match react-native's one - https://github.com/facebook/react-native/blob/main/ReactAndroid/src/main/third-party/kotlin/BUCK#L54
Adds a way for the developer to override kotlin version via `kotlinVersion` prop in `build.gradle` `ext` property.
Also, removes the dependency on the standard library ([explaination](https://stackoverflow.com/a/64988522)) thus lets Gradle infer correct versions for a particular Kotlin version.
Fixes #1109.
Run ./gradlew compileDebugKotlin in react-native-screens/TestsExample/android.
> fix: downgrade kotlin & take kotlinVersion from ext

- android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt
- guides/GUIDE_FOR_LIBRARY_AUTHORS.md
PR removing the behavior of attaching listener for `backStack` changes on `Android`. Based on https://stackoverflow.com/a/60560844/13006595 it looks like it is not available while using synchronous `Fragment` updates via `commitNow`. Also, it was not used in `react-navigation` since it provides its own listener for hardware back button on `Android`.
***It can be considered `BREAKING CHANGE` if you use this library outside of `react-navigation`***
All tests working even when `gestureEnabled` set to `true` on `Android` in `NativeStackView`.
> feat: remove adding to back stack logic on Android

- TestsExample/App.js
- TestsExample/src/Test1091.tsx
- ios/RNSScreenStackHeaderConfig.m
Setting up the default value for `direction` in [native stack v6](https://github.com/react-navigation/react-navigation/blob/main/packages/native-stack/src/views/HeaderConfig.tsx#L114) revealed an issue with a swipe gesture on iOS 12.
Setting `direction` with the same value twice cancels the transition between screens in iOS 12.
This issue doesn't occur on iOS 13+ because Apple reimplemented how the gesture system works.
Fixes #1091
- Added check and set `direction` in `RNScreenStackHeaderConfig` only when it changed
https://user-images.githubusercontent.com/39658211/134510295-f79104e8-9b0d-4547-981d-7247ffc0a2cd.MP4
https://user-images.githubusercontent.com/39658211/134510751-f2dcd869-1b9c-4182-b5a8-ae80dfe757ea.MP4
`Test1091.tsx` in `TestsExample` project
> fix: canceled swipe gesture on iOS 12 when direction hasn't changed

- src/index.native.tsx
PR adds iOS check for NativeScreenNavigationContainer.  Android trying to call RNSScreenNavigationContainer which is only had on iOS.
Added iOS check before the NativeScreenNavigationContainerValue init. Actually line 235 calls NativeScreenNavigationContainer if navigation hasTwoStates but I combined both check in one place.
1- Add navigation patch https://github.com/react-navigation/react-navigation/pull/9772
2- Run Test619 on Android
> fix: add hasTwoStates iOS check

- ios/RNSScreen.h
- ios/RNSScreenContainer.h
- ios/RNSScreenWindowTraits.h
- ios/RNSScreenWindowTraits.m
PR exposing a way to check if there was a window trait (status bar or orientation) set by user in any of the navigators. In such case, it should take precedence over other methods, like `expo-screen-orientation`. Calling 
```
+ (BOOL)shouldAskScreensForTrait:(RNSWindowTrait)trait
includingModals:(BOOL)includingModals
inViewController:(UIViewController *)vc;
```
should return `NO` if there was no screen in view hierarchy that requests a specific trait and `YES` otherwise.
PR to be used e.g. in `Expo`.
***These methods are used by providing their exact signature as a string and therefore their name should not be changed.***
> fix: make method for checking if trait is set

- .github/ISSUE_TEMPLATE/bug-report.md
This change will (hopefully) reduce repetitive questions that maintainers have to ask in order to gather the necessary information to work on an issue. This includes platforms, workflow, and more package versions.
- Added section about the platform that the issue is affecting
- Added section about managed/bare workflow
- Extended section with package versions
> docs: update bug-report template

- android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt
It seems like Kotlin null safety is slightly differently resolved between versions. This caused a compile error with Kotlin v1.3.X.
Fixes https://github.com/software-mansion/react-native-screens/issues/1163
- Ensured mTopScreens null safety in `ScreenStack.kt`
Change https://github.com/software-mansion/react-native-screens/blob/master/TestsExample/android/build.gradle#L10 to use `kotlinVersion = "1.3.72"`
> fix: ensure mTopScreen's null safety in ScreenStack

- README.md
This PR adds information on how to override the Kotlin version used by screens and the minimum Kotlin required version.
This change becomes relevant since version 3.9.0
> docs: add kotlin guide to change version

- README.md
- src/index.native.tsx
Since v3.9.0 `react-native-screens` use `react-freeze` library which requires at least react-native `v0.64`
> docs: update required react-native version

- TestsExample/App.js
- TestsExample/src/Test1204.tsx
- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt
This PR turns off accessibility for screen and header beneath transparent modal on Android.
Fixes #1204
Added a `turnOffA11yUnderTransparentScreen` method invoked in ScreenStack's `onUpdate` method. It iterates through the stack to search for the first transparent screen from the top and turns off a11y for the screen and header beneath.
https://user-images.githubusercontent.com/39658211/140723838-90dec12d-5d3b-4235-80d5-b456a28d7551.mp4
https://user-images.githubusercontent.com/39658211/140723856-53a1057e-77cf-43b5-ac7c-4b34632df53c.mp4
`Test1204.tsx` in `TestsExample/` project
> fix: turn off accessibility for screen and header beneath transparent modal on Android

- ios/RNSScreen.m
Added a check for private `_jsThread` field in `_bridge` in order not to try and send events to JS before the thread is ready. Should resolve #1211. Should close #1212. Suggested by @piaskowyk 
To be provided.
> fix: check if jsThread is not null

- Example/e2e/examplesTests/bottomTabs.e2e.ts
- Example/ios/Podfile.lock
- Example/src/screens/BottomTabsAndStack.tsx
- Example/src/shared/Button.tsx
- TestsExample/App.js
- TestsExample/ios/Podfile.lock
- TestsExample/src/Test1198.tsx
- TestsExample/src/Test1209.tsx
- src/index.native.tsx
React-navigation's `useIsFocused` works based on [changes between renders]( https://github.com/react-navigation/react-navigation/blob/b91c9b05ff96727f5fa6ef0bec51b5d7eac06600/packages/core/src/useIsFocused.tsx#L17). Freezing stops all renders on non-visible screens thus breaking the `useIsFocused` hook. 
This issue can be mitigated by allowing one more render before freezing the screen / disabling freeze for the first render.
This also fixes unnecessary pop animation on on stack reset.
Fixes #1198, #1209
- Added `DelayedFreeze` component in `index.native.tsx`
- Added e2e tests for bottom-tabs example
https://user-images.githubusercontent.com/39658211/143202264-a7c9d9ee-b3b9-4502-b1f3-b2428aab3e8e.mov
https://user-images.githubusercontent.com/39658211/143216963-10c5f165-5844-4ab3-beab-d6438 …
> feat: disable freeze for first render

- ios/RNSScreenStack.m
Added a check for if `topScreen` in `gestureRecognizerShouldBegin` method is `RNSScreenView`, since it is not in some cases. Reproduction of such behavior would be much needed. Should fix #1194.
Not yet available
> fix: check if topScreen is RNSScreenView

- TestsExample/App.js
- TestsExample/src/Test1227.tsx
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt
#1190 introduced a bug where stack animation was incorrectly resolved on Android during simple `navigate`.
Thanks to @WoLewicki for creating the fix
Test1227.tsx
> fix: use shouldUseOpenAnimation to determine animation

- Example/App.tsx
- Example/e2e/firstTest.e2e.ts
- Example/package.json
- Example/src/screens/SearchBar.tsx
- Example/src/shared/Toast.tsx
- Example/src/shared/index.ts
- Example/yarn.lock
- createNativeStackNavigator/README.md
Update Example app to reflect current master status.
The search bar is now available also on Android devices and thus 'Search bar' section needed to be updated.
Not every available search bar setting was reflected in the Example. 
- Updated Search bar example
- Reverted search bar documentation for react-navigation v4 
Search Bar playground in `Example/` project
> chore: update search bar playground in Example app

- android/src/main/java/com/swmansion/rnscreens/CustomSearchView.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt
Removes nullability from `CustomSearchView` constructor. This should fix issues caused by `androidx.appcompat:appcompat:1.3.0`.
> fix: Removes nullability from CustomSearchView

- Example/src/screens/SearchBar.tsx
This PR adds missing `inputType` variable in `navigation.setOptions`. Without this, you can't change the keyboard's type on Android in the Example's Searchbar playground.
> fix: add missing inputType in navigation.setOptions in Example

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/android-build-test.yml
- .github/workflows/android-e2e-test.yml
- .github/workflows/ios-build-test.yml
- .github/workflows/ios-e2e-test.yml
- .github/workflows/main.yml
- .github/workflows/tv-os-build-test.yml
- README.md
- guides/GUIDE_FOR_LIBRARY_AUTHORS.md
This PR renames `master` occurrences to `main` in the CI and documentation.
> fix: rename master occurences to main

- README.md
- guides/GUIDE_FOR_LIBRARY_AUTHORS.md
This PR unifies all URLs that relate to `react-native-screens` to use `software-mansion`.
> docs: unify links in the documentation

- .github/workflows/needs-repro.yml
It seems like the GitHub Actions bot added in https://github.com/software-mansion/react-native-screens/pull/1253 behaves incorrectly when a new comment is added/edited. This PR disallows needs-repro action to run on adding/editing comments.
> fix: dont run needs-repro on comment

- .github/workflows/needs-repro.yml
This PR restores `needs-repro` action to work on comment add/edit/delete.
Also, added prop for `needs-repro` action to trigger only if the issue was created after 01-01-2022.
GitHub Action was fixed here: https://github.com/software-mansion-labs/swmansion-bot
> feat: bring back needs-repro trigger on comment

- .github/workflows/needs-more-info.yml
- .github/workflows/needs-repro.yml
This PR makes GitHub Actions bot responses more concise. This change was made because of feedback that people tend to ignore and don't want to read messages that are too long.
> feat: make bot responses shorter

- TestsExample/ios/Podfile.lock
- TestsExample/src/Test642.tsx
- guides/GUIDE_FOR_LIBRARY_AUTHORS.md
- ios/RNSScreen.h
- ios/RNSScreen.m
- ios/RNSScreenContainer.m
- ios/RNSScreenStack.m
- ios/RNSScreenWindowTraits.h
- ios/RNSScreenWindowTraits.m
- ios/UIViewController+RNScreens.m
- native-stack/README.md
- src/native-stack/types.tsx
- src/native-stack/views/NativeStackView.tsx
- src/types.tsx
Added prop `homeIndicatorHidden` for hiding home indicator on `iOS`. 
`Test642.tsx`
> feat: add home indicator hiding

- Example/package.json
- Example/yarn.lock
- TVOSExample/yarn.lock
- TestsExample/yarn.lock
- yarn.lock
Bump nanoid to 3.2.0 throughout the repository.
> chore: bump nanoid to 3.2.0

- TestsExample/package.json
- TestsExample/yarn.lock
Changes in #1213 overridden nanoid version bump in #1283. 
This PR bumps nanoid to the most recent nanoid version in /TestsExample
> chore: bump nanoid to 3.2.0 in /TestsExample

- reanimated/package.json
Added `reanimated` folder with `package.json` so using files from `react-native-screens/reanimated` works outside of our repo.
Use files from `/reanimated` outside of this repo.
> fix: add directory so /reanimated works outside of repo

- README.md
Added explanation of https://github.com/software-mansion/react-native-screens/issues/1183 to `Common Problems` section.
> feat: add onScroll triggered to common problems

- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.kt
Changed `Activity` to extend to `ReactActivity` since it is the one being extended at least from `react-native` 0.62.
> fix: change Activity to extend to ReactActivity

- TestsExample/src/Test860.tsx
- android/build.gradle
- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt
- guides/GUIDE_FOR_LIBRARY_AUTHORS.md
- native-stack/README.md
- src/native-stack/types.tsx
- src/native-stack/views/NativeStackView.tsx
- src/types.tsx
Added props for manipulating navigation bar on `Android`. Requested in https://github.com/software-mansion/react-native-screens/discussions/1244.
This PR adds `androidx.core:core-ktx:1.5.0` dependency and it for sure would be good to check if it works in older `Android` APIs. These options use the newer API which affects all system bars, so same changes to both `statusBar` and `navigationBar` are strongly suggested.
`Test860.tsx`.
> feat: add android navigation bar manipulation

- ios/RNSScreenStackAnimator.m
This PR simplifies code in `animateFadeFromBottomWithTransitionContext` method by using constants rather than an inline enum. Also, removes redundant variables by inlining the calculated values.
> fix: simplify fade_from_bottom animation code on iOS

- .github/workflows/android-build-test-fabric.yml
- .github/workflows/ios-build-test-fabric.yml
This PR adds two new workflow files - `android-build-test-fabric.yml` & `ios-build-test-fabric.yml `. These workflows test whether `react-native-screens` build without errors using Fabric architecture on both Android and iOS.
> feat: add test build Fabric workflows

- android/build/generated/source/codegen/java/com/facebook/react/viewmanagers/RNSScreenManagerDelegate.java
- android/build/generated/source/codegen/java/com/facebook/react/viewmanagers/RNSScreenManagerInterface.java
- android/build/generated/source/codegen/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderConfigManagerDelegate.java
- android/build/generated/source/codegen/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderConfigManagerInterface.java
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfigViewManager.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt
- src/fabric/ScreenNativeComponent.js
- src/fabric/ScreenStackHeaderConfigNativeComponent.js
Props were not working on Android on Paper architecture, because they were not present in delegate. This PR fixes them.
1. Run Example application
2. Test if all `Screen` and `ScreenStackHeaderConfig` props are working
> fix: Fixes android props on paper

- README.md
This PR fixes the '404 Not found' error caused by the typo in the `README-Fabric.md` url and rewords the sentences in the Fabric section.
> docs: fix README-Fabric.md link, reword sentences

- .github/workflows/android-build-test-fabric.yml
- .github/workflows/android-build-test.yml
This PR adds cache-dependency-path on Android CI test builds.
- Updated `android-build-test-fabric.yml` workflow
- Updated `android-build-test.yml` workflow
> fix: add cache-dependency-path on Android

- ios/RNSScreenStackComponentView.mm
This PR fixes a bug on Fabric architecture where an inactive screen stayed at the top of the stack after app reload.
Fixed by calling `resetViewToScreen` method in `ScreenStack's` `prepareForRecycle` method on iOS.
- Removed `_invalidated` logic on Fabric as it is not being used
- Updated and called `dismissOnReload` to call `resetViewToScreen` method in ScreenStack on iOS
https://user-images.githubusercontent.com/39658211/155159886-ff4ff128-e1c0-4e71-8a98-5b7cc92942d0.mov
https://user-images.githubusercontent.com/39658211/155159913-95e90a31-626e-464c-8e7e-55d74d593d68.mov
FabricExample/
> fix: app reload on fabric on iOS

- ios/RNSScreenStackComponentView.mm
https://github.com/software-mansion/react-native-screens/pull/1339 removed code which on Paper architecture was responsible for handling nested stacks. As @Ubax suggested this PR adds this to `prepareForRecycle` method and reverts removal of `didMoveToWindow`.
Run this code snippet in the `FabricExample/` project
<details>
<summary>Code snippet</summary>
<br>
```jsx
import * as React from 'react';
import {View, StyleSheet, Text} from 'react-native';
import {NavigationContainer} from '@react-navigation/native';
import {createNativeStackNavigator} from '@react-navigation/native-stack';
function First() {
const NestedStack = createNativeStackNavigator();
return (
<NestedStack.Navigator>
<NestedStack.Screen name="NestedFirst" component={NestedFirst} />
</NestedStack.Navigator>
);
}
function …
```
> fix: add stack nesting on Fabric

- android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt
Initial navigation bar content color is not applied. Actually don't know the technical reason behind it.
It works If you edit the 'navigationBarColor' value and save it to a different value while the app is open.
`Test860.tsx`.
Change `navigationBar` color to `yellow` and you will see the navigation bar content color is not applied on the first app opening.
It should set the light background to dark content, but it is setting the light background to light content.
> fix: apply initial navigation bar content color

- Example/yarn.lock
- TVOSExample/yarn.lock
- yarn.lock
This PR bumps plist to 3.04 within the repo.
Changes: 
- chore(deps): bump plist from 3.0.3 to 3.0.4 in /TVOSExample (#1350) 
- chore(deps): bump plist from 3.0.1 to 3.0.4 (#1349) 
- chore(deps): bump plist from 3.0.1 to 3.0.4 in /Example (#1348)
> chore(deps): bump plist to 3.0.4

- RNScreens.podspec
Latest version of RN requires c++17 for fabric (https://github.com/facebook/react-native/commit/c2e4ae39b8a5c6534a3fa4dae4130166eda15169)
Set CLANG_CXX_LANGUAGE_STANDARD to c++17
Test fabric with latest RN and make sure it builds
> Use c++17 for fabric on iOS

- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt
- src/index.native.tsx
Removed unnecessary `processColor` which was added by mistake since the `statusBarColor` did not work without `customType = "Color"` in its `@ReactProp`.
`Test860.tsx` to see that it still works correctly after this change.
> fix: remove processColor

- ios/RNSScreenStack.m
See video here: https://twitter.com/radexp/status/1506981953156927499
react-native-screens accidentally broke a subtle behavior of the edge swipe/interactive pop gesture recognition. In simple vanilla iOS app, the edge swipe is easily recognized even when touch is panning across a scroll view diagonally or while scroll view is in motion. Because RNS does not have a normal view/view controller hierarchy (or some other subtle reason), the pop gesture breaks.
RNS sets `_controller.interactivePopGestureRecognizer.delegate = self;` so it's not completely broken… but this subtle behavior was still broken, driving me bonkers over the past couple of years :) 
I don't know the true root cause of this issue, this could require deeper changes to RNS, for the default native behavior to _just work_. …
> [iOS] Fix edge swipe (interactive pop) gesture recognition

- ios/RNSFullWindowOverlay.m
Added check for if `_container` is `nil` which leads to app crash if `invalidate` was called before `didMoveToWindow` (e.g. navigating back from screen with `navigation.goBack()`). Should fix #1374.
Example from https://github.com/software-mansion/react-native-screens/issues/1374
> fix: add check for if container is null

- TestsExample/ios/Podfile.lock
- ios/RNSScreenComponentView.mm
Support screen props on Fabric
Part of stack PR:
* https://github.com/software-mansion/react-native-screens/pull/1362
* https://github.com/software-mansion/react-native-screens/pull/1363
* https://github.com/software-mansion/react-native-screens/pull/1364
* https://github.com/software-mansion/react-native-screens/pull/1365
> feat: Screen props: `screenOrientation` (3)

- ios/RNSScreenComponentView.mm
- ios/RNSScreenController.h
- ios/RNSScreenController.mm
- ios/RNSScreenStackComponentView.mm
This PR moves the snapshotting logic from Screen to ScreenStack. From now on a snapshot is made from only the top-most screen on the stack.
Snapshots are used in order to have a transition animation during the go-back invoked from the JS side. 
Problems:
_____
Layout shift on app reload is partly fixed by simplifying logic in `resetViewToScreen` method in `RNSScreenController` by running `[_initialView updateBounds];` on every re-render. This will finally properly set the layout.
It leaves a slight issue with a layout jump on the initial render which offsets the Screen by the height of the header. The problem is probably caused by [the asynchronous layout calculation in the commit phase of the Fabric render pipeline](https://reactnative.dev/architecture/render-pipeline#phase-2-commit) …
> fix: iOS Fabric snapshotting mechanism

- TestsExample/src/Test758.tsx
- createNativeStackNavigator/README.md
- guides/GUIDE_FOR_LIBRARY_AUTHORS.md
- ios/RNSSearchBar.m
- native-stack/README.md
- src/types.tsx
Adds support for setting the tint color of the native stack search bar on iOS.  This will change the color of the cursor/caret and the cancel button text.
RNSSearchBar.m has been modified to accept a `tintColor` option, the SearchBarProps  interface has been updated as well as the documentation.   I based my changes off of [this pull request](https://github.com/software-mansion/react-native-screens/pull/1108/commits/d4a0020591004a2d16ebd19845ec41c41fcf2a52).   Let me know if I missed any doc updates.
```js
useLayoutEffect(() => {
navigation.setOptions({
headerSearchBarOptions: {
tintColor: "red",
}
})
},[navigation])
```
> feat: add iOS search bar tint color

- android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt
`BlurView` sometimes calls `draw` method of the app's rootView, causing unexpected behavior in our library. Since `BlurView` is a child of `ScreenStack` in the crashing example, calling [`op.draw()`](https://github.com/software-mansion/react-native-screens/blob/d5f7374ada7421aeaa132c53653fed19992a0ba6/android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt#L278) calls `BlurView` `onDraw` method, which then sometimes calls `draw` method in app's `rootView`. It results in visiting the [`drawAndRelease` method](https://github.com/software-mansion/react-native-screens/blob/d5f7374ada7421aeaa132c53653fed19992a0ba6/android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt#L275) again. The important thing is [`drawingOps.indices`](https://github.com/software-mansion/react-native-screens/b …
> fix: blurView integration with ScreenStack

- RNScreens.podspec
Added check for if env var is set to `1` instead of if it exists, based on https://github.com/software-mansion/react-native-reanimated/blob/e49e1abea60badb0bfb7666389adfa29093bf697/RNReanimated.podspec#L41 and suggestion from @tomekzaw and @piaskowyk
> fix: add better fabric_enabled check

- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerDelegate.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerInterface.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderConfigManagerDelegate.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderConfigManagerInterface.java
- ios/RNSScreen.mm
- ios/RNSScreenStack.mm
- ios/RNSScreenStackHeaderConfig.h
- ios/RNSScreenStackHeaderConfig.mm
- src/fabric/ScreenStackHeaderConfigNativeComponent.js
This PR unifies some business logic between Paper & Fabric implementations.
See [commits](https://github.com/software-mansion/react-native-screens/pull/1446/commits).
TODO
> chore: unify business logic between archs (8)

- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerDelegate.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerInterface.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderConfigManagerDelegate.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderConfigManagerInterface.java
- ios/RNSScreen.h
- ios/RNSScreen.mm
- ios/RNSScreenStack.mm
- ios/RNSScreenStackHeaderConfig.h
- ios/RNSScreenStackHeaderConfig.mm
- src/fabric/ScreenNativeComponent.js
- src/fabric/ScreenStackHeaderConfigNativeComponent.js
This PR adds `preventNativeDismiss` prop for Fabric.
See [commits](https://github.com/software-mansion/react-native-screens/pull/1444/commits).
TODO
> chore: add `preventNativeDismiss` prop for Fabric (7)

- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerDelegate.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerInterface.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderConfigManagerDelegate.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderConfigManagerInterface.java
- ios/RNSScreen.h
- ios/RNSScreen.mm
- ios/RNSScreenContainer.mm
- ios/RNSScreenStack.h
- ios/RNSScreenStack.mm
- ios/RNSScreenStackHeaderConfig.h
- ios/RNSScreenStackHeaderConfig.mm
- src/fabric/ScreenNativeComponent.js
- src/fabric/ScreenStackHeaderConfigNativeComponent.js
This PR adds `homeIndicatorHidden` & `activityState` props for Fabric.
See [commits](https://github.com/software-mansion/react-native-screens/pull/1443/commits).
TODO
> chore: add `homeIndicatorHidden` & `activityState` props for Fabric (6)

- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerDelegate.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerInterface.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderConfigManagerDelegate.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderConfigManagerInterface.java
- ios/RNSConvert.h
- ios/RNSConvert.mm
- ios/RNSScreen.h
- ios/RNSScreen.mm
- ios/RNSScreenContainer.mm
- ios/RNSScreenStack.h
- ios/RNSScreenStack.mm
- ios/RNSScreenStackHeaderConfig.h
- ios/RNSScreenStackHeaderConfig.mm
- src/fabric/ScreenNativeComponent.js
- src/fabric/ScreenStackHeaderConfigNativeComponent.js
- src/native-stack/views/NativeStackView.tsx
This PR adds `gestureResponseDistance` prop for Fabric & unifies some logic related to the prop.
See [commits](https://github.com/software-mansion/react-native-screens/pull/1442/commits).
TODO
> chore: add `gestureResponseDistance` prop for Fabric (5)

- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerDelegate.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerInterface.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderConfigManagerDelegate.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderConfigManagerInterface.java
- ios/RNSConvert.h
- ios/RNSConvert.mm
- ios/RNSScreen.h
- ios/RNSScreen.mm
- ios/RNSScreenContainer.mm
- ios/RNSScreenStack.h
- ios/RNSScreenStack.mm
- ios/RNSScreenStackAnimator.mm
- ios/RNSScreenStackHeaderConfig.h
- ios/RNSScreenStackHeaderConfig.mm
- src/fabric/ScreenNativeComponent.js
- src/fabric/ScreenStackHeaderConfigNativeComponent.js
- src/native-stack/views/NativeStackView.tsx
This PR adds `customAnimationOnSwipe` prop for Fabric & unifies some logic related to the prop.
See [commits](https://github.com/software-mansion/react-native-screens/pull/1434/commits).
TODO
> chore: add `customAnimationOnSwipe` prop for Fabric (4)

- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerDelegate.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerInterface.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderConfigManagerDelegate.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderConfigManagerInterface.java
- ios/RNSConvert.h
- ios/RNSConvert.mm
- ios/RNSScreen.h
- ios/RNSScreen.mm
- ios/RNSScreenContainer.mm
- ios/RNSScreenStack.h
- ios/RNSScreenStack.mm
- ios/RNSScreenStackAnimator.mm
- ios/RNSScreenStackHeaderConfig.h
- ios/RNSScreenStackHeaderConfig.mm
- src/fabric/ScreenNativeComponent.js
- src/fabric/ScreenStackHeaderConfigNativeComponent.js
- src/native-stack/views/NativeStackView.tsx
This PR adds `hideKeyboardOnSwipe` prop for Fabric.
See [commits](https://github.com/software-mansion/react-native-screens/pull/1433/commits).
TODO
> chore: add `hideKeyboardOnSwipe` prop for Fabric (3)

- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerDelegate.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerInterface.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderConfigManagerDelegate.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderConfigManagerInterface.java
- ios/RNSConvert.h
- ios/RNSConvert.mm
- ios/RNSScreen.h
- ios/RNSScreen.mm
- ios/RNSScreenContainer.mm
- ios/RNSScreenStack.h
- ios/RNSScreenStack.mm
- ios/RNSScreenStackAnimator.mm
- ios/RNSScreenStackHeaderConfig.h
- ios/RNSScreenStackHeaderConfig.mm
- src/fabric/ScreenNativeComponent.js
- src/fabric/ScreenStackHeaderConfigNativeComponent.js
- src/native-stack/views/NativeStackView.tsx
This PR adds `replaceAnimation` prop for Fabric.
See [commits](https://github.com/software-mansion/react-native-screens/pull/1432/commits).
TODO
> chore: add `replaceAnimation` prop for Fabric (2)

- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerDelegate.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerInterface.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderConfigManagerDelegate.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderConfigManagerInterface.java
- ios/RNSConvert.h
- ios/RNSConvert.mm
- ios/RNSScreen.h
- ios/RNSScreen.mm
- ios/RNSScreenContainer.mm
- ios/RNSScreenStack.h
- ios/RNSScreenStack.mm
- ios/RNSScreenStackAnimator.mm
- ios/RNSScreenStackHeaderConfig.h
- ios/RNSScreenStackHeaderConfig.mm
- src/fabric/ScreenNativeComponent.js
- src/fabric/ScreenStackHeaderConfigNativeComponent.js
- src/native-stack/views/NativeStackView.tsx
This PR aims unifies logic related to the dismissed prop.
* [unify `RNSScreenStack#updateContainer` method](https://github.com/software-mansion/react-native-screens/pull/1431/commits/e310fca25d5f892ac241f5f3c0ebba63002491a6)
TODO
> chore: add `dismissed` prop for Fabric (1)

- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerDelegate.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerInterface.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderConfigManagerDelegate.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderConfigManagerInterface.java
- ios/RNSConvert.h
- ios/RNSConvert.mm
- ios/RNSScreen.h
- ios/RNSScreen.mm
- ios/RNSScreenContainer.mm
- ios/RNSScreenStack.h
- ios/RNSScreenStack.mm
- ios/RNSScreenStackAnimator.mm
- ios/RNSScreenStackHeaderConfig.h
- ios/RNSScreenStackHeaderConfig.mm
- src/fabric/ScreenNativeComponent.js
- src/fabric/ScreenStackHeaderConfigNativeComponent.js
- src/native-stack/views/NativeStackView.tsx
Stack PR (base).
This PR aims to introduce all missing props in `RNSScreenView` component & unify logic between architectures (make shared all the parts of code that can be shared)
* https://github.com/software-mansion/react-native-screens/pull/1431
* https://github.com/software-mansion/react-native-screens/pull/1432
* https://github.com/software-mansion/react-native-screens/pull/1433
* https://github.com/software-mansion/react-native-screens/pull/1434
* https://github.com/software-mansion/react-native-screens/pull/1442
* https://github.com/software-mansion/react-native-screens/pull/1443
* https://github.com/software-mansion/react-native-screens/pull/1444
* https://github.com/software-mansion/react-native-screens/pull/1446
See particular PRs
TODO
> chore: add missing props & unify business logic between archs

- android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt
Rewrote:
- setStyle;
- setHidden;
- setColor
methods to use `WindowInsetsControllerCompat` for StatusBar management (instead of old approach with changing window flags).
I'm currently working on [react-native-keyboard-controller](https://github.com/kirillzyusko/react-native-keyboard-controller) library which heavily relies on `WindowInsets*` API. However if the code uses old way with window flags management - it breaks `WindowInsets*` API and I can not listen for keyboard events anymore using `ViewCompat.setWindowInsetsAnimationCallback`. So in this PR I rewrote some methods to new style and used `WindowInsetsControllerCompat` instead of managing window flags.
However I couldn't find a way how to rewrite `setTranslucent` method 🤔 (though in your example app it works without any issues, I …
> feat: use recommended WindowInsetsControllerCompat for StatusBar management

- FabricTestExample/src/Test1260.tsx
- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerDelegate.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerInterface.java
- ios/RNSConvert.h
- ios/RNSConvert.mm
- ios/RNSScreen.mm
- ios/RNSScreenStack.mm
- ios/RNSScreenStackHeaderConfig.mm
- src/fabric/ScreenNativeComponent.js
Added support for `swipeDirection` (iOS only) prop on Fabric
* added it to `SceenNativeComponent.js` (for codegen)
* added prop update inside `RNSScreenView#updateProps:oldProps:`
* added noop for Android
* copied newly generated interfaces to paper directory
* `Test1260` in FabricTestExample
> feat: missing Screen prop: swipeDirection

- FabricTestExample/App.js
- FabricTestExample/src/Test556.js
- FabricTestExample/src/Test624.js
- FabricTestExample/src/Test860.tsx
- ios/RNSScreen.h
- ios/RNSScreen.mm
- ios/RNSScreenContainer.mm
- ios/RNSScreenStack.mm
- ios/RNSScreenStackAnimator.mm
- src/fabric/ScreenNativeComponent.js
PR adding missing `onNativeDismissCancelled` prop, moving `RNSScreenView` resolving logic to a new prop in `RNSScreen`, and fixing snapshotting mechanism issues.
Various test cases in `FabricTestExample`.
> fix: fabric issues

- ios/RNSScreenStack.mm
- src/fabric/ScreenStackNativeComponent.js
Implemented `onFinishTransitioning` event for ScreenStack on Fabric. 
* Added event type to codegen 
* Added event dispatch on Fabric
* Small refactoring of event emitting methods so they are shared between architerctures.
No new tests
This event was used only with react-naviagation v4.
> feat: implement `onFinishTransitioning` event for ScreenStack for Fabric

- FabricTestExample/src/Test1153.tsx
- ios/RNSScreen.mm
Added the fix introduced here: 
* https://github.com/software-mansion/react-native-screens/pull/1153
for Fabric.
* Moved `hideHeaderIfNecessary` method to common section
* Added fix for Fabric: when returning from second screen application would crash due to order of view unmounting (child-first) on Fabric (calling `view.reactSubviews[0]` would cause application to crash)
* Moved `Test1153`. See: https://github.com/software-mansion/react-native-screens/pull/1153
> fix: `hideHeaderIfNecessary` for Fabric

- .github/workflows/close-when-stale.yml
Added `close-when-stale` action from [swmansion-bot](https://github.com/software-mansion-labs/swmansion-bot)
* Added action code to github workflows
> chore: add close when stale action & label 

- src/index.native.tsx
- src/native-stack/views/NativeStackView.tsx
Moved code that sets default value for `gestureResponseDistance` prop on `Screen` component "deeper", so that, when 3rd party library uses our primitives it does not have to set the default value by itself. Behaviour is unchanged.
* The code was moved to `index.native.tsx`
`Test1296` -- see that `gestureResponseDistance` prop works just fine
> fix: default value for `gestureResponseDistance` 

- ios/RNSScreenStack.mm
Fixes #1510
Fixed & improved `RNSScreenStackView` logic regarding `UIGestureRecognizerDelegate` protocol.
* Added `gestureRecognizer:shouldReceiveEvent:`. Events for particular gesture recognisers are now filtered before `gestureRecognizerShouldBegin` method is called.
* Any `UIScreenEdgePanGestureRecognizer` must fail for scroll view gesture recogniser to begin.
* When `fullScreenSwipeEnabled == true` scroll view gesture recogniser is prioritised before our `RNSPanGestureRecognizer`.
* Simplified logic in `gestureRecognzerShouldBegin`.
Now, when adding another gesture recogniser with screen stack as delegate one must make sure that events are properly filtered.
Here you can add screenshots / GIFs documenting your change.
You can add before / after section if you're changing some …
> fix: handle multiple gesture recognizers

- android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt
Used `ViewCompat` for setting `setOnApplyWindowInsetsListener` and `onApplyWindowInsets`.
It's needed because of `ViewCompat.setWindowInsetsAnimationCallback` - if we use direct methods it breaks compat layer and as a result compat listeners will not receive updates.
It's a follow-up PR to https://github.com/software-mansion/react-native-screens/pull/1451
- Used `ViewCompat` in `setTranslucent` method;
No changes from UI perspective.
I used this code: https://github.com/kirillzyusko/react-native-keyboard-controller/compare/main...issue/rns-status-bar-translucency
Without these changes animation stucks, since callback in `setWindowInsetsAnimationCallback` is not receiving updates (once the screen is mounted `setTranslucent` method is getting called, and since it works without `compat` mode …
> refactor: use ViewCompat for status bar translucency management

- ios/RNSScreenStack.mm
`gestureRecognizer:shouldReceiveEvent` method is unfortunately available only since iOS 3.14, so I decided to replave it with calls to methods from older apis (9.0+).
* Overrided methods from older api: `gestureRecognizer:shouldReceivePress:` && `gestureRecognizer:shouldReceiveTouch:`. 
* Removed override of `gestureRecognizer:shouldReceiveEvent:`
It seems likely to me, that overriding `gestureRecognizer:shouldReceiveTouch:` should be enough but basing on apple developer docs - I'm not sure, thus this PR is introducing some dead code (`gestureRecognizer:shouldReceivePress:` method).
`Test1072` -- see that the behaviour restored in #1512 works also on older iPhones.
> fix: add usage of older API for older iOS versions

- TestsExample/src/Test1476.tsx
- ios/RNSScreen.h
- ios/RNSScreen.mm
- ios/RNSScreenStack.mm
The issue reported in #1476 was resolved "in normal cases" by #1521
& #1509. 
However if **on screen with modal presentation** `fullScreenSwipeEnabled` is set to `true` ***or*** custom animation is set the gesture recognisers still handle the gesture (it depends on configuration of these props which gesture recogniser applies, but the buggy behaviour occurs). 
Case described above is pretty rare, as it does not make much sense to set `fullScreenSwipeEnabled` or `stackAnimation` & `customAnimationOnSwipe` on screen with modal presentation but this is exactly what happens when using native stack from `@react-navigation` (since [this PR](https://github.com/react-navigation/react-navigation/pull/10674) was released)
It seems to me that there are three reasonable solutions:
1. We can reject …
> fix: reject all gestures when modal is presented

- README.md
Updates the table in the README that documents the supported versions of React Native for various versions of this project.
As of version [`3.14.0`](https://github.com/software-mansion/react-native-screens/releases/tag/3.14.0), support for RN `0.68.0` and below has been dropped.
From the release notes:
> Moreover, from this release forward, Fabric is supported only for react-native 0.69+. Support for 0.68.x is dropped.
- Updated `README.md` docs
N/A
> docs: Update Supported React Native Versions Table in ReadMe

- FabricTestExample/App.js
- FabricTestExample/src/Test1473.tsx
- TestsExample/App.js
- TestsExample/src/Test1473.tsx
- ios/RNSScreen.mm
Fixes #1473 
When modals are pushed onto the stack, in view hierarchy they end up not being descendants of `RNSScreenNavigationController` -> [When a modal is dismissed & we ask `RNSScreen` with modal view for its navigation controller](https://github.com/software-mansion/react-native-screens/blob/cc5de7ba28e90ecce9bbb3464ef0a625eaae032f/ios/RNSScreen.mm#L753-L755) (`[self navigationController]`) we receive null. This caused `getIndexOfView:` method to return `-1` (as the view was not found) what resulted in wrong value of `_dismissCount`. 
Added a check for case when `navigationController` of `RNSScreen` is null - now in such case we default to `_dismissCount == 1`
https://user-images.githubusercontent.com/50801299/179496086-0064e0bd-bf0e-4475-8a46-01432c75ec73.mov …
> fix: invalid dismissCount value when closing modals

- ios/RNSScreenStackHeaderConfig.mm
Fabric warning contained this typo:
> Back button subivew is not yet Fabric compatible in react-native-screens
> Fix typo subivew

- ios/RNSScreenStack.mm
Minor improvement to avoid creating copy of every mutation in for loop. 
* Changed `auto` -> `auto&` inside C++ style for loop.
Run `FabricTestExample` & see it works fine.
> chore: avoid unnecessary struct copying in iOS code

- FabricTestExample/App.js
- FabricTestExample/src/Test887.tsx
- TestsExample/App.js
- TestsExample/src/Test1539.tsx
- TestsExample/src/Test887.tsx
- src/index.native.tsx
- src/index.tsx
- src/reanimated/ReanimatedNativeStackScreen.tsx
- src/reanimated/ReanimatedScreen.tsx
This PR exposes a `Screen` which is prewrapped with `ScreenContext`. Previous `Screen` implementation is internally renamed `InnerScreen` and should have no effect on the outside use of the library.
This change is necessary to use `useReanimatedTransitionProgress` feature without additional setup within react-navigation repo. 
Discussed in detail in https://github.com/react-navigation/react-navigation/pull/10585
Closes https://github.com/react-navigation/react-navigation/pull/10585
`Test1539.tsx` in `TestsExample` project.
> fix: wrap Screen with ScreenContext

- ios/RNSScreen.mm
Fixes #1299 **on Fabric**. I was not able to reproduce this issue on Paper -> changes introduced in this PR do not change behaviour on Paper. 
View recycling caused behaviour such that VCs of views that returned from recycle pool were not set as delegates for presentation controller. This caused `presentationControllerDidDismiss:` method not to be called and in consequence we did not receive information that modal transition had finished -> we did not allow for another one to start. 
Set `stackPresentation` to default value in `prepareForRecycle` method to workaround view-recycling & check incoming new prop value (in `updateProps:oldProps:`) against actual state not old props. I pasted just below (a little bit paraphased) comment I placed in code in `prepareForRecycle` method with better …
> fix: set VCs of views from recycling pool as UIAdaptivePresentationControllerDelegate

- Example/ios/ScreensExample/AppDelegate.m
- FabricExample/ios/FabricExample/AppDelegate.mm
- FabricTestExample/ios/FabricTestExample/AppDelegate.mm
- README.md
- TestsExample/ios/TestsExample/AppDelegate.mm
According to the Apple docs a call to ... must be made for `UIDevice` `orientation` property to work correctly. 
I checked and neither we call `[[UIDevice currentDevice] beginGeneratingDeviceOrientationNotifications]` nor any dependency does this for us (I looked up in node_modules with `grep --include=\*.{m,mm} -rnw './node_modules/' -e "beginGeneratingDeviceOrientationNotifications"`), however it worked properly. I also checked with [`generatesDeviceOrientationNotifications`](https://developer.apple.com/documentation/uikit/uidevice/1620055-generatesdeviceorientationnotifi?language=objc) method whether orientation notifications were enabled or not. They were on. This nudges me towards conclusion that it possible that these notifications are enabled in some internal Apple code. 
However, …
> fix: manually enable device orientation notifications

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- FabricTestExample/ios/Podfile.lock
- RNScreens.podspec
- TestsExample/ios/Podfile.lock
As a version of folly can change between versions of React-Native we need to remove an explicit version of `folly_version` from our libraries to let RN infer the correct version.
Change based on https://github.com/th3rdwave/react-native-safe-area-context/commit/eb111ff4eebc8d06ca01e7d12d9661147d03da20
Removed explicit folly version from RNScreens.podspec
Build FabricExample/
> fix: remove explicit folly version

- guides/GUIDE_FOR_LIBRARY_AUTHORS.md
- native-stack/README.md
This PR updates the documentation of the newly added `freezeOnBlur` prop.
> docs: add freezeOnBlur to READMEs

- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.kt
Fixes #1506 
`ScreenContainer#setupFragmentManager` method resolves `FragmentManager` instance for `ScreenContainer` to use for conducting transactions. Until now, when first (not nested) `ScreenContainer` was initialised we took `FragmentManager` from top level activity, but it leads to conflicts with native Android navigation when React Native is not loaded directly in main activity (there are cases (see #1506) when both `react-native-screens` & Android native navigation use simultaneously the same FragmentManager leading to crashes).
Added a method resolving fragment manager whose fragment's view is `ReactRootView`.
See #1506 for crash description and how to reproduce.
> fix: handle React Native loaded on Fragment

- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.kt
Changes introduced in https://github.com/software-mansion/react-native-screens/pull/1553 in case of `FragmentManager.findFragment` method throwing an exception could lead to some hard to debug behaviour. Now in case something goes wrong, we will get clear error message. 
Code responsible for resolving `FragmentManager` when React Native is loaded of fragment now throws uncaught exception. 
See #1553 and #1506
> chore: throw error when failed to find fragment for react root view

- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.kt
Fixes #1565
See first #1553 and #1562 
This PR reverts changes introduced in #1562 - as for now this is a best known solution to a problem. 
**Silently** fallback to activity's `FragmentManager` in case there is a `Fragment` under activity, but it is not the one with `ReactRootView`. 
Thing to note is that we are falling back silently w/o any warning. 
See #1565, #1553
> fix: fallback to default behaviour when fragment not found

- ios/RNSFullWindowOverlay.mm
- ios/RNSScreen.mm
- ios/RNSScreenContainer.mm
- ios/RNSScreenNavigationContainer.mm
- ios/RNSScreenStack.mm
- ios/RNSScreenStackHeaderConfig.mm
- ios/RNSScreenStackHeaderSubview.mm
- ios/RNSSearchBar.mm
This PR replaces bad double-quotes imports (which break Swift interop) with good angle-bracket imports.
The forbidden pattern is: `#import "RCT`
See also:
* https://github.com/software-mansion/react-native-reanimated/pull/3150
* https://github.com/software-mansion/react-native-gesture-handler/pull/2180
* https://github.com/react-native-svg/react-native-svg/pull/1848
> fix: use angle-bracket imports

- .github/workflows/android-e2e-test.yml
- .github/workflows/ios-build-test-fabric.yml
- .github/workflows/ios-build-test.yml
- .github/workflows/ios-e2e-test.yml
- .github/workflows/tv-os-build-test.yml
This PR  upgrades macOS runner image to `macos-12` to fix `kLSNoExecutableErr: The executable is missing` error.
Also, path patterns were improved to trigger CI in more cases.
> fix: upgrade iOS CI runner image

- .github/workflows/android-build-test-fabric.yml
- .github/workflows/android-build-test.yml
- .github/workflows/android-e2e-test.yml
- .github/workflows/ios-e2e-test.yml
- FabricExample/android/app/build.gradle
- FabricTestExample/android/app/build.gradle
[Following `react-native-gesture-handler`](https://github.com/software-mansion/react-native-gesture-handler/blob/9d8a460de8337daf41ecd92a4b71bde2dc95dd1d/.github/workflows/android-build.yml#L35) as it takes over 1h to complete the workflow.
* used `-PreactNativeArchitectures=arm64-v8a` gradle option to build only arm64-v8a architecture
* added paths to dependency list of workflows, so they get triggered when their configuration changes
* added abi filters to `FabricExample` & `FabricTestExample` so single architecture builds are respected
Run the workflows
> chore: build only arm64-v8a architecture on CI for Fabric Android build

- FabricExample/ios/Podfile.lock
- FabricExample/package.json
- FabricExample/yarn.lock
- FabricTestExample/ios/FabricTestExample.xcodeproj/project.pbxproj
- FabricTestExample/ios/Podfile.lock
- FabricTestExample/package.json
- FabricTestExample/yarn.lock
- TestsExample/android/app/src/main/java/com/testsexample/MainApplication.java
- TestsExample/ios/Podfile.lock
- TestsExample/package.json
- TestsExample/yarn.lock
Updated React Native version to stable 0.70.0 in `react-native-screens` example applications. 
* Updated `package.json` files & reinstalled `node_modules` & `pods` 
* Updated `react-native-reanimated` version to commit hash from main as it not contains [desired fix](https://github.com/software-mansion/react-native-reanimated/pull/3493)
Tested this on example applications.
> chore: bump React Native to 0.70.0 in test examples

- guides/GUIDE_FOR_LIBRARY_AUTHORS.md
- src/native-stack/types.tsx
- src/types.tsx
This PR exposes the `preventNativeDismiss` and `onNativeDismissCancelled` props for library authors used for preventing native navigation. We should not expose these props in the native-stack.
Code in react-navigation which uses these props can be seen here:
https://github.com/react-navigation/react-navigation/blob/main/packages/native-stack/src/views/NativeStackView.native.tsx#L270
- Added `preventNativeDismiss` and  `onNativeDismissCancelled` props to `ScreenProps` in `src/types.tsx`
- Added `preventNativeDismiss` and  `onNativeDismissCancelled` props to `GUIDE_FOR_LIBRARY_AUTHORS.md`
- Reformated `GUIDE_FOR_LIBRARY_AUTHORS.md` file
- Sorted `freezeOnBlur` prop alphabetically in `src/types.tsx` and `src/native-stack/types.tsx`
> fix: expose missing props in ScreenProps

- FabricTestExample/android/gradle.properties
As the comment in the code says: this line is no longer needed since https://github.com/software-mansion/react-native-reanimated/pull/3493 got merged and dependency on `react-native-reanimated` [was updated](https://github.com/software-mansion/react-native-screens/pull/1584/commits/06f2a4fbf6373e86ad26dc081af06910b68e3369).
Removed unused line.
Build & run `FabricTestExample` and see that it works.
> chore: remove unused project property in FabricTestExample

- yarn.lock
Dependency react-freeze bump from `1.0.0` -> `1.0.3`.
> chore: bump react-freeze from 1.0.0 to 1.0.3

- README.md
Update supported React Native version for Fabric in library's main readme.
Support for older versions has been dropped as we added autolinking in #1585 (it [requires `@react-native-community/cli` 9.1.0 or newer](https://github.com/react-native-community/cli/releases/tag/v9.1.0) (support for `cmakeListsPath` in config) which is shipped with React Native since 0.70.0) 
Since 3.18.0 Fabric will be supported only with React Native 0.70.0 or newer.
--
> docs: update supported RN version for Fabric

- ios/RNSFullWindowOverlay.mm
- ios/RNSScreen.mm
- ios/RNSScreenContainer.mm
- ios/RNSScreenNavigationContainer.mm
- ios/RNSScreenStackHeaderConfig.mm
- ios/RNSSearchBar.mm
Potentially fixes #1570 as suggested in [comments](https://github.com/software-mansion/react-native-screens/issues/1570#issuecomment-1233329916). 
I tested it on iOS 16.0 simulator & device - worked for me. However when I passed this solution to other team @software-mansion, it was reported back to me that there is no change (buggy behaviour still occurs).
I'm gonna merge this PR, as it introduces only `line-swap` change, which should not introduce any regression and potentially fixes the bug.
**NOTE**: this issue seems to be already fixed internally by Apple as reported [here](https://github.com/react-navigation/react-navigation/issues/10840#issuecomment-1248117850).
Just moved `navitem.title = ...` assignment below `navitem.titleView = ...` one.
See #1570
> fix: potentially fix iOS 16.0 navigation header title bug

- src/native-stack/utils/getDefaultHeaderHeight.tsx
Fixes #1604 
`Platform.isTVOS` check was removed with `react-native@0.70` [(see the PR)](https://github.com/facebook/react-native/pull/34071) as it was only wrapper for `Platform.isTV` check (which exists since `0.61`). 
Dropped usage of removed `Platform.isTVOS` check in favour of `Platform.isTV`.
See #1604 -- check on any app that the library now works with `@types/react-native@0.70.*`
> fix: drop usage of removed Platform.isTVOS field

- FabricTestExample/package.json
- FabricTestExample/yarn.lock
Earlier version caused some problems with existence of `CMakeLists.txt` in `safe-area-context` `android/src/main/jni` directory on React Native `0.70.2`.
Bumped the version in `FabricTestExample`
See that `FabricTestExample works`
> chore: bump react-native-safe-area-context to 4.4.1 in FabricTestExample

- FabricTestExample/package.json
- FabricTestExample/yarn.lock
- package.json
Autolinking was added with #1585 and it added `react-native.config.js` file with codegen configuration, **but** it did not add this file to npm include list causing its absence in final released package...
Fixes #1608
Added `react-native.config.js` to npm file list in main `package.json`
See #1608 for reproductions.
> fix: add `react-native.config.js` to npm package

- react-native.config.js
Fixes #1614
#1611 added `react-native.config.js` file to the library which uses features supported since `@react-native-cli@9.0.0` thus causing library fail to link while on Paper with React Native < 0.70.
This fix is borrowed from `react-native-safe-area-context`.
Added check for `@react-native-community/cli-platform-android` version in `react-native.config.js`.
--
> fix: configure cli for Android only when RNCLI version >= 9.0.0

- README.md
Giving more detail to where the override should be.
Description and motivation for this PR.
Helps users who are experiencing crashing from react-native-screens on Android who have placed the override in the wrong location. This modifies the readme for more clear instructions on what to do. When placed in the MainActivityDelegate, the crash still occurs, while placing it in the parent, it seems to be fine.
Fixes #1481 .
N/A
N/A
> chore: clarify installation instructions for Android

- .github/workflows/ios-build-test.yml
- Example/ios/Podfile.lock
- Example/package.json
- Example/yarn.lock
- FabricExample/ios/Podfile.lock
- FabricExample/package.json
- FabricExample/yarn.lock
- FabricTestExample/ios/Podfile.lock
- FabricTestExample/package.json
- FabricTestExample/yarn.lock
- TestsExample/ios/Podfile.lock
- TestsExample/package.json
- TestsExample/yarn.lock
See: https://github.com/facebook/react-native/issues/35210 for explanation why fixes are needed and why they look like it. 
Followed recommendations included in aforementioned issue.
* `FabricTestExample`: upgraded `React Native` to `0.70.5`
* `FabricExample`: upgraded `React Native` to `0.70.5`
* `Example`: upgraded `React Native` to `0.66.5`
* `TestsExample`: upgraded `React Native` to `0.70.5`
* `TVOSExample`: ??? Need to check whether it is affected
So `Test iOS build` CI fails due to [mismatched versions of `hermes-engine` in `Podfile.lock` and version in "snapshot"](https://github.com/software-mansion/react-native-screens/actions/runs/3435966238/jobs/5728946474). Locally everything works fine, I updated pods, and have also run `pod update hermes-engine --no-repo-update` and pushed …
> fix: Examples stopped to work after RN issue

- .gitignore
I'm not sure what generates it, but it should not be included anyway
Just a small update, so it won't get checked-in into version control accidentally. 
Added `android/.settings` to lib-wide git ignore list
N/A
> chore: exclude android/.settings file form repo

- Example/ios/ScreensExample/AppDelegate.m
- FabricExample/ios/FabricExample/AppDelegate.mm
- FabricTestExample/ios/FabricTestExample/AppDelegate.mm
- README.md
- TestsExample/ios/TestsExample/AppDelegate.mm
- ios/RNSFullWindowOverlay.mm
- ios/RNSScreen.mm
- ios/RNSScreenContainer.mm
- ios/RNSScreenNavigationContainer.mm
- ios/RNSScreenStackHeaderConfig.mm
- ios/RNSScreenWindowTraits.mm
- ios/RNSSearchBar.mm
UIKit documentation states that in order to successfully use orientation in iOS apps the orientation has to be enabled via [the `beginGeneratingDeviceOrientationNotifications ` method](https://developer.apple.com/documentation/uikit/uidevice/1620041-begingeneratingdeviceorientation?language=objc). This was addressed in https://github.com/software-mansion/react-native-screens/pull/1543.
This PR attempts to make this change internal and also removing an additional `react-native-screens` installation step from README.
PR made based on code from `expo-screen-orientation` package [from this line](https://github.com/expo/expo/blob/519ac3d86864da9dd920a9ff8d0c880f6ec81a58/ios/versioned/sdk46/EXScreenOrientation/EXScreenOrientation/ABI46_0_0EXScreenOrientationRegistry.m#L38). 
Fixes …
> fix: make enabling device orientation notifications internal

- Example/yarn.lock
- FabricExample/yarn.lock
- FabricTestExample/yarn.lock
- TVOSExample/ios/Podfile.lock
- TVOSExample/ios/TVOSExample.xcodeproj/project.pbxproj
- TVOSExample/yarn.lock
- TestsExample/src/Test1649.tsx
- TestsExample/yarn.lock
- ios/RNSScreen.h
- ios/RNSScreen.mm
- yarn.lock
Making use od dependabot & resolving some minor issues with tvOS build.
Most notably I had to raise deployment target for `TVOSExample` to `11.0`.
> chore: bump deps & fix tvOS build

- FabricTestExample/ios/Podfile.lock
- ios/RNSScreen.mm
RN logs a warning when this method is not overridden and at the same time `-init` method is. 
I decided to return NO despite the fact that we dispatch taks on main
queue in init, becuase comments in RN interals state that modules that
require main queue setup will be initialised ahead of time -- and I
believe we do not need it.
`RNSScreenManager` now explicitly states that it does not require main queue setup.
--
> fix: override requiresMainQueueSetup in RNSScreenManager

- .github/workflows/ios-build-test-fabric.yml
Make `ios-build-test-fabric` workflow build `FabricTestExample` instead of `FabricExample`
This is done to unify behaviour between platforms as `android-build-test-fabric` builds `FabricTestExample`. 
Edited working directory of workflow.
> chore: unify CI between platforms

- FabricTestExample/App.js
- FabricTestExample/src/Test1157.tsx
- TestsExample/src/Test1157.tsx
- ios/RNSScreenStackHeaderConfig.mm
- ios/RNSScreenStackHeaderSubview.h
- ios/RNSScreenStackHeaderSubview.mm
Resolves #1563 
The issue was tricky & deceptive.
In `RNSScreenStackHeaderSubview` during initialisation we assigned to `_prop` default prop values. We used it later in `updateProps:oldProps:` to check whether the `type` changed - if it was the case we called `setType`, otherwise there was no action taken. 
With such setup, in case of `newProps.type` value, being the same as `_prop.type` the `type` property would not get initialised and default to `0` leading to crashes later on. 
**NOTE**: We need to verify this in other components, as we are using there the same faulty mechanism. 
* Removed if-check whether the `type` property should be updated
* Unified ifdef'd (`RN_NEW_ARCH_ENABLED`) sections of code
* Updated test screen & added it to `FabricTestExample`
* Removed the warning
See …
> feat(iOS): back button subview for Fabric

- FabricTestExample/src/Test550.js
- TestsExample/src/Test550.js
- ios/RCTImageComponentView+RNSScreenStackHeaderConfig.h
- ios/RCTImageComponentView+RNSScreenStackHeaderConfig.mm
- ios/RNSScreenStackHeaderConfig.mm
Up to now there was missing implementation of back button image loading logic on Fabric.
I managed to implement it using only RN API (I avoided creation of custom image component with custom state as it is done in `react-native-svg`).
It is worth to notice that there might be still some buggy behaviour present, as instead of provided asset (an arrow, see examples) a red rectangle is rendered. However I decided to not include further fix in this PR, as current behaviour is the same on both architectures. Most likely there will be a follow up PR.
* Implemented missing logic
* Added some needed categories (see changes)
See `Test550` in `FabricTestExample`.
> fix(iOS): image loading for back button on Fabric

- ios/RNSScreen.mm
Earlier when calling `updatePresentationStyle` in `RNSScreen` we have relied on order of method calls and kept our fingers crossed that the order would not be violated with future changes. 
Now we leverage `finalizeUpdates:` method from `RCTComponentViewProtocol` which is called after all updates are applied to the component. 
For broader context see #1649 (comments).
Moved call to `updatePresentationStyle` from `updateProps` to `finalizeUpdates`. 
See `Test1649` (everything should work as before)
> chore: refactor medium detent iOS implementation 

- FabricTestExample/App.js
- FabricTestExample/src/Test1683.tsx
- TestsExample/App.js
- TestsExample/src/Test1683.tsx
- src/native-stack/views/NativeStackView.tsx
Resolves #1683 
At the moment, when user set theme on `NavigationContainer` the status bar does not adapt. It keeps following OS theme. You have to set theme for status bar separately in screens options.
Everything works fine when the app theme is following the OS theme (vast majority of cases I guess):
```
const scheme = useColorScheme(); // From RN API
...
<NavigationContainer theme={scheme === 'dark' ? DarkTheme : DefaultTheme}>
...
```
The issue appears when for example OS theme is `dark`, but the app wants to force display in `light` -> then the status bar keeps respecting OS theme and rest of the application does not (except few other components such as search bar, but they will be handled in separate PR's).
Proposed changes fix the problem & modify the default behaviour in …
> fix(iOS): status bar does not respect app theme

- android/build.gradle
- android/versioned-res/anim-v33/rns_default_enter_in.xml
- android/versioned-res/anim-v33/rns_default_enter_out.xml
- android/versioned-res/anim-v33/rns_default_exit_in.xml
- android/versioned-res/anim-v33/rns_default_exit_out.xml
https://github.com/software-mansion/react-native-screens/pull/1693 introduced new animation xml's with features available only since API level 33 (Android 13). This resulted in build failures in cases where `compileSdk`/`targetSdk` is set to value lower than 33.
Note: placing these animations in qualified resource directory `res/anim-v33` did not resolve the issue, because the qualifier is only used during runtime - in build phase all resources must be valid from the perspective of given SDK (at least it seems so).
I thought of few options: 
1. Having separate `res` directories for `compileSdk >= 33` and `compileSdk < 33` and selecting appropriate in `build.gradle`.
The main disadvantage is that most of the animation resources are being duplicated and any future modifications will require …
> fix: Android build for `compileSdk < 33`

- android/build.gradle
- android/src/main/AndroidManifest.xml
Warning during Android build:
> package="com.swmansion.rnscreens" found in source AndroidManifest.xml: /home/dee/mobile/node_modules/react-native-screens/android/src/main/AndroidManifest.xml.
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.
Instead set the namespace (or testNamespace) in the module's build.gradle file, as described here: https://developer.android.com/studio/build/configure-app-module#set-namespace
- Updated `android/build.gradle` 
- ~Updated `android/src/main/AndroidManifest.xml`~ (@kkafar: please see [this commit description](https://github.com/software-mansion/react-native-screens/pull/1717/commits/e62dc0e3a6b56020dfbb8fc6a39beb2678a100f8)) and review notes.
Build test examples and notice that the warning no longer appears.
> chore: set library namespace in build script

- Example/android/app/src/main/java/com/swmansion/rnscreens/example/MainActivity.java
- FabricExample/android/app/src/main/java/com/fabricexample/MainActivity.java
- FabricTestExample/android/app/src/main/java/com/fabrictestexample/MainActivity.java
- TestsExample/android/app/src/main/java/com/testsexample/MainActivity.java
This override was accidentally removed during bumping examples to RN 0.71 (in some cases it was never added, but it should be).
Override `onCreate` method in apps `MainActivity` as the installation guide says (see project readme).
Build & run test examples
> chore: override `onCreate` in example apps

- FabricTestExample/src/Test1097.tsx
- TestsExample/src/Test1097.tsx
- android/src/main/java/com/swmansion/rnscreens/CustomSearchView.kt
- android/src/main/java/com/swmansion/rnscreens/SearchBarManager.kt
- android/src/main/java/com/swmansion/rnscreens/SearchBarView.kt
- guides/GUIDE_FOR_LIBRARY_AUTHORS.md
- ios/RNSSearchBar.mm
- native-stack/README.md
- src/fabric/SearchBarNativeComponent.ts
- src/index.native.tsx
- src/types.tsx
Add `setText` native command to SearchBar imperative API.
Added the JS impl, native impl (both Android & iOS, Fabric & Paper), updated JS types & codegen specs.
`Test1097` in both `FabricTestExample` & `TestsExample`
> feat: add `setText` command on SearchBar

- ios/RNSScreenWindowTraits.mm
Fixes:
> [Orientation] BUG IN CLIENT OF UIKIT: Setting UIDevice.orientation is not supported. Please use UIWindowScene.requestGeometryUpdate(_:)
for iOS 16+.
Changes were inspired by these threads:
- https://developer.apple.com/forums/thread/707735
- https://developer.apple.com/forums/thread/709215
- https://stackoverflow.com/a/73735976/9272042
- added usage of new API for rotation management for iOS 16+ in `RNSScreenWindowTraits.mm`;
https://user-images.githubusercontent.com/22820318/223976297-8cb1733d-6611-4d23-aed1-e659fadf6b09.mov
Just test a scenario when `enforceDesiredDeviceOrientation` is called on iOS 16. Every time when you call
```objc
[[UIDevice currentDevice] setValue:@(newOrientation) forKey:@"orientation"];
```
You will see a warning in XCode logger. If you rotate screen …
> fix: use new rotation API for iOS 16

- android/src/main/res/v33/anim-v33/rns_default_enter_in.xml
- android/src/main/res/v33/anim-v33/rns_default_enter_out.xml
New Android animations introduced in https://github.com/software-mansion/react-native-screens/pull/1693 were laggy (especially enter-out / enter-in animations).
This was caused by [these lines](https://cs.android.com/android/platform/superproject/+/android-platform-13.0.0_r6:frameworks/base/core/res/res/anim/activity_open_exit.xml;l=23-24) in Android source code -- alpha was not animated.
Set more reasonable target value for alpha animation & explicitly set start offset on enter out animation.
See #1693 for description.
> chore: improve Android 13 animations

- src/index.tsx
This PR changes the type of `ScreenStackHeaderConfig` so it can be passed to `Animated.createAnimatedComponent` from Reanimated.
- Updated `ScreenStackHeaderConfig` type in `index.tsx`
Previously, the following code in [ScreenStackHeaderConfigBackgroundColorExample.tsx](https://github.com/software-mansion/react-native-reanimated/blob/b44920c101778de8566a3247061b14775cb21737/app/src/examples/ScreenStackHeaderConfigBackgroundColorExample.tsx#L22-L25) would throw the following error:
```ts
const AnimatedScreenStackHeaderConfig = Animated.createAnimatedComponent(ScreenStackHeaderConfig);
```
```
No overload matches this call.
Overload 1 of 2, '(component: ComponentClass<ScreenStackHeaderConfigProps, any>, options?: Options<ScreenStackHeaderConfigProps> | undefined): ComponentClass<...>', gave …
```
> fix: ScreenStackHeaderConfig type

- ios/RNSScreen.h
- ios/RNSScreenStack.mm
PR adding intercepting of native header back button on `iOS`, so the back animation does not fire there if it should have been intercepted.
https://github.com/react-navigation/react-navigation/blob/9fe34b445fcb86e5666f61e144007d7540f014fa/example/src/Screens/NativeStackPreventRemove.tsx with those changes applied.
> feat: prevent native back button dismissal on iOS

- README.md
#1765 introduced incompability with newer versions of react native (Fabric only), and the readme was not updated.
Just added a note.
Does not apply.
Does not apply.
> fix: update supported React Native version in readme

- android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt
Due to [Android docs](https://developer.android.com/reference/android/view/ViewGroup#drawChild(android.graphics.Canvas,%20android.view.View,%20long)) the canvas parameter in  `ViewGroup.drawChild(canvas, ...)`
method must not be null. This restriction was enforced on type level in sdk 34 thus our code was no longer valid.
Closes #1787
Removed type nullability using `!!` operator. I decided to go with this solution, because:
1. With current implementation `DrawingOp.canvas` has to be nullable (as after performing the draw we do not drop the object, but invalidate it instead and we do not want
to hold no longer requried reference to canvas).
2. In case we actually pass null there -- we will crash anyway. 
Set `compileSdkVersion` & `targetSdkVersion` to 34 in `TestExample` & see that the …
> fix: canvas nullability in ScreenStack for Android SDK 34

- ios/RNSScreenWindowTraits.mm
Currently when XCode w/o support for iOS 16 is used the RNSScreens compilation will most surely fail due to unrecognized symbols being present in the `RNSScreenWindowTraints` code.
See [this discussion](https://github.com/software-mansion/react-native-screens/pull/1732#issuecomment-1594455264).
Added compilation guards for iOS sdk version. When not present old implementation is used. 
See #1732 & try to compile & test on different major versions of xcode (e.g. 12 & 14)
> fix: ifdef orientation code that requries iOS 16

- FabricExample/yarn.lock
- FabricTestExample/ios/Podfile.lock
- FabricTestExample/yarn.lock
- TestsExample/ios/Podfile.lock
- TestsExample/yarn.lock
- yarn.lock
XCode reporting out-of-date podfile locks & bad yarn locks makes it hard to work with. I'm bringing those up to speed.
Also integrating some changes from dependabot.
* Reinstalled node modules & pods where necessary, also ran `yarn install` in main library directory. 
+ Dependabot changes
-
> chore: update & reinstall selected deps

- .github/workflows/android-e2e-test.yml
- Example/.detoxrc.js
- Example/e2e/firstTest.e2e.ts
- Example/ios/Podfile.lock
- Example/yarn.lock
After removal of navigation v4 in #1790 there were still some tests lingering in the `Example` App. Also few issues with jest, detox & Android emulator.
* Bumped emulator runner version
* Removed tests for v4
* Updated deps in Example 
* Synced pods
CI finally works
> chore: fix CI

- src/index.native.tsx
Default values for medium-detent related props were set only in `NativeStackView` so only in case user used native stack directly from `react-native-screens`. This led to buggy behaviour when `@react-navigation/native-stack` was in use. 
See conversation: https://github.com/software-mansion/react-native-screens/issues/1686#issuecomment-1621899668
Default prop values are now set in `InnerScreen` in `index.native.tsx` which is used internally by `@react-navigation/native-stack` package.
See conversation: https://github.com/software-mansion/react-native-screens/issues/1686#issuecomment-1621899668 (and below).
Use `stackPresentation: 'formSheet'` with native stack from `@react-navigation/native-stack` and see that the modal is opened by default to full height.
> fix: move setting default values of medium-detent related props to `InnerScreen`

- src/native-stack/utils/getDefaultHeaderHeight.tsx
- src/native-stack/views/NativeStackView.tsx
On phones with Dynamic Island (iPhone 14 Pro) the statusbar became larger and the header below smaller.
This is not reflected yet in code, which leads to bugs using for e.g. the useHeaderHeight() hook.
Fixes #1671
See also my PR in react-navigation:
https://github.com/react-navigation/react-navigation/pull/11338
Sizes can be verified with:
https://www.figma.com/community/file/1248375255495415511/Apple-Design-Resources-%E2%80%93-iOS-17-and-iPadOS-17
https://useyourloaf.com/blog/iphone-14-screen-sizes/#iphone-14-pro
> fix: headerheight incorrect on phones with dynamic island

- ios/RNSScreen.h
- ios/RNSScreen.mm
- src/fabric/ScreenNativeComponent.ts
- src/index.native.tsx
- src/native-stack/types.tsx
- src/native-stack/views/NativeStackView.tsx
- src/types.tsx
This PR adds new iOS only event. Event is triggered after canceled swipe back (as on video)
https://github.com/software-mansion/react-native-screens/assets/36106620/e9f63c7c-e6b4-4444-895a-d6b41c725963
> chore: add onGestureCancel event

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- FabricTestExample/ios/Podfile.lock
- TVOSExample/ios/Podfile.lock
- TestsExample/ios/Podfile.lock
After releasing version 3.22.1 of react-native-screens, Podfile.lock files were not included to update. After trying to install pods of example projects, Podfile.lock is still being changed.
* Updated all `Podfile.lock` files of example projects.
> chore(deps): Bump versions of RNScreens, FBReactNativeSpec and RCTAppDelegate deps

- ios/RNSFullWindowOverlay.mm
Work done by @aweary. I've just edited the code & ensured this also can work on Fabric.
Link to initial PR: 
* https://github.com/software-mansion/react-native-screens/pull/1750 
```
`RNSFullWindowOverlay` is meant to cover the entire window, but at the moment VoiceOver doesn't know this and you can still navigate other views underneath this one. 
```
```
This sets the `accessibilityViewIsModal` to `YES`, which tells VoiceOver that it should ignore all sibling views (which in this case would be basically everything else since this is a subview of the `UIWindow`) and means VoiceOver can no longer escape this view and navigate hidden content.
It also adds `UIAccessibilityPostNotification(UIAccessibilityLayoutChangedNotification, _container)` to tell VoiceOver that it should move focus into …
```
> feat(iOS): make RNSFullWindowOverlay a modal for accessibility

- ios/RNSScreen.h
- ios/RNSScreen.mm
- ios/RNSScreenContainer.h
- ios/RNSScreenContainer.mm
- ios/RNSScreenNavigationContainer.h
- ios/RNSScreenNavigationContainer.mm
- ios/RNSScreenStack.h
- ios/RNSScreenStack.mm
- ios/RNSScreenWindowTraits.mm
- ios/UIViewController+RNScreens.mm
Up to this moment it was distrubing that some of our classes were prefixed with `RNS`, some with `RNScreens` and some with `RN`...
This PR aligns all class names to use `RNS` prefix according to [iOS conventions](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Conventions/Conventions.html)
TODO:
Renamed all classes to comply to aforementioned conventions.
> refact(iOS): unify class & method naming with respect to conventions

- FabricTestExample/src/Test1097.tsx
- TestsExample/src/Test1097.tsx
- android/src/main/java/com/swmansion/rnscreens/SearchBarManager.kt
- guides/GUIDE_FOR_LIBRARY_AUTHORS.md
- ios/RNSConvert.h
- ios/RNSConvert.mm
- ios/RNSEnums.h
- ios/RNSScreenStackHeaderConfig.mm
- ios/RNSSearchBar.h
- ios/RNSSearchBar.mm
- native-stack/README.md
- src/fabric/SearchBarNativeComponent.ts
- src/types.tsx
Add support for [search bar placement](https://developer.apple.com/documentation/uikit/uinavigationitemsearchbarplacement?language=objc) prop on iOS.
Added both Fabric & paper native impl and exposed the prop on JS side.
`Test1097` in `TestExample` and `FabricTestExample`. 
Play around with value of `placement` prop in search bar configuration.
> feat(iOS): add support for search bar placement

- FabricTestExample/App.js
- FabricTestExample/src/Test1844.tsx
- TestsExample/App.js
- TestsExample/src/Test1844.tsx
- src/native-stack/utils/getDefaultHeaderHeight.tsx
- src/native-stack/views/NativeStackView.tsx
Currently, `useHeaderHeight()` hook returns wrong values for using large headers on iOS. This PR introduces a fix that adds a logic for calculating large headers.
This change is also a part of ongoing work on completely new `useAnimatedHeaderHeight` hook, introduced in #1802. 
- Added an if statement in `useHeaderHeight` that sets correct value for `headerHeight`.
<details>
<summary>iPhone 14 Pro (iOS 16.4)</summary>
</details>
<details>
<summary>iPhone 8 (iOS 16.4)</summary>
</details>
<details>
<summary>iPhone 14 Pro (iOS 16.4)</summary>
</details>
<details>
<summary>iPhone 8 (iOS 16.4)</summary>
</details>
You can test changes, included in PR by selecting `Test1844` from `TestsExample`/`FabricTestExample`.
> fix: Calculate large headers in `useHeaderHeight` hook

- src/native-stack/types.tsx
- src/types.tsx
`sheetExpandsWhenScrollingToEdge` prop is iOS specific and this fact is not described in type info. 
Added a note in type docs that this prop is iOS specific.
> docs: annotate `sheetExpandsWhenScrollingToEdge` prop as iOS specific

- ios/RNSSearchBar.mm
Fixes #1853
Looks like I've made a typo while implemnenting `toggleCancelButton:flag:` (flag has `BOOL *` type instead of just `BOOL`) leading to compile errors as reported in #1853.
Changed (fixed) the type of `flag` parameter from `BOOL *` to just plain `BOOL`.
See #1853 & try to build on macOS Catalyst
> fix(iOS): bad parameter type in `toggleCancelButton` search bar command

- ios/RNSConvert.h
- ios/RNSConvert.mm
- ios/RNSFullWindowOverlay.h
- ios/RNSFullWindowOverlay.mm
- ios/RNSScreen.h
- ios/RNSScreen.mm
- ios/RNSScreenContainer.mm
- ios/RNSScreenNavigationContainer.mm
- ios/RNSScreenStack.mm
- ios/RNSScreenStackHeaderConfig.mm
- ios/RNSScreenStackHeaderSubview.mm
- ios/RNSSearchBar.mm
1. Typing `facebook::react` is tedious (XCode completion does not work correctly in case of namespaces for some reason I do not want to spend any more time investigating)
2. `facebook` prefix does not convey any useful meaning from the perspective of this library -- we can achieve the same code-isolation by using just `react` or `rct`
3. We can not resign completely from using this prefix (by putting `using namespace facebook::react` in our `.mm` files) because some C++ codegened types have the same names as their counterparts from Objective-C and we need to distinguish between them (take a look into `RNSConvert.h`).
Replace all usages of `facebook::react::` with `react::`.
Added `namespace react = facebook::react;` where necessary.
> chore: improve readability of C++ namespaced types

- ios/RNSSearchBar.h
- ios/RNSSearchBar.mm
When adding 
https://github.com/software-mansion/react-native-screens/pull/1843
I've forgotten to add API avaibility checks for method definitions (usage and declarations were guarded). This caused build problems when deploying for lower iOS versions.
Fixes #1859
Added missing availbility checks.
Build iOS without having iOS 16 installed (or somehow disabled?).
> fix(iOS): add missing iOS API availbility checks

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- FabricTestExample/ios/Podfile.lock
- TestsExample/ios/Podfile.lock
Reinstalling pods & deps in example apps after `3.24.0` was released, so that `Podfile.lock` is up to date on any new branch.
Create new branch, reinstall pods and notice that no changes were generated in `Podfile.lock`.
TODO: We should really make CI for this
> chore: reinstall deps & pods in example apps after release

- ios/RNSScreen.mm
`RNSScreenView` (iOS) inherits from `RCTViewComponentView` which has custom implementation of `finalizeUpdates:` method, thus we should call it.
Added missing call to `[super finalizeUpdates:]` in `RNSScreenView`.
WIP
> fix(iOS): add missing call to super method in `RNSScreenView#finalizeUpdates`

- android/src/main/res/v33/anim-v33/rns_default_enter_out.xml
The issue was reported [here](https://github.com/react-navigation/react-navigation/issues/11438) on `@react-navigation` repo.
*Note* Awaiting for response from people that reported the issue
Adjusted alpha animation duration as suggested in one of the comments. 
Basing on people opinion that this improves the situation.
> fix(Android): shorten alpha animation to 83ms on default enter-out

- android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt
`replaceSystemWindowInsets` is deprecated. Now it's recommended to use `WindowInsetsCompat.Builder().setInsets` so in this PR I'm adding this new API for Android API >= 30.
Feel free to test my changes because maybe I'm not aware about some specific logic behind `replaceSystemWindowInsets` API and these changes are introducing breaking changes (I hopefully it will not, but still better to double test) 🙌 
These changes were inspired by https://android-review.googlesource.com/c/platform/frameworks/support/+/1254619/1/viewpager/viewpager/src/main/java/androidx/viewpager/widget/ViewPager.java#440
- started to use `Builder.setSystemWindowInsets` instead of `replaceSystemWindowInsets` for Android API >= 30
Nothing is changed from UI perspective 🙂 
I've tested example application and didn't …
> chore: migrate `replaceSystemWindowInsets` to `Builder.setSystemWindowInsets`

- ios/RNSFullWindowOverlay.mm
- `FullWindowOverlay` cannot receive tap events when it is shown on top of `UIModalPresentationFullScreen` Modal which is the default presentation style of the react native Modal.
- UIKit changes the layout hierarchy when the modal is full screen. It is mentioned in the below docs. The view does not move to the window if a full-screen modal is being presented. However, the `_container` moves to the window as it is appended explicitly using `addSubview` in the key window. 
- https://developer.apple.com/library/archive/featuredarticles/ViewControllerPGforiPhoneOS/PresentingaViewController.html
- So the `RNSFullWindowOverlay` view gets attached to the superview but they are not moved to the window. This PR adds a simple fix to replace `didMoveToWindow` with `didMoveToSuperview`. I considered …
> fix: full window overlay cannot receive tap when modal is full screen

- src/native-stack/types.tsx
- src/types.tsx
Fix: https://github.com/react-navigation/react-navigation/issues/11481
`react-natigation` use a `ScreenStackHeaderConfig` component in  from `react-native-screens`
see: `packages/native-stack/src/views/HeaderConfig.tsx`
During fixing https://github.com/react-navigation/react-navigation/issues/11481 it's required to change types of `react-native-screens`
1. Edit source code to force use PlatformColor `./node_modules/@react-navigation/native-stack/src/views/HeaderConfig.tsx` 
```tsx 
import {
ScreenStackHeaderConfig
} from "react-native-screens";
// ...
<ScreenStackHeaderConfig
titleColor={
Platform.select({
default: PlatformColor("systemGray4"),
android: PlatformColor("@android:color/holo_orange_dark")
})
}
backgroundColor={
Platform.select({
default: PlatformColor("systemTealColor"), …
```
> fix: use `PlatformColor` instead of plain `string` for color related props

- android/src/main/java/com/swmansion/rnscreens/ScreenFragment.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.kt
- android/src/main/java/com/swmansion/rnscreens/SearchBarView.kt
- android/src/main/java/com/swmansion/rnscreens/events/HeaderAttachedEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/HeaderBackButtonClickedEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/HeaderDetachedEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/ScreenAppearEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/ScreenDisappearEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/ScreenDismissedEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/ScreenTransitionProgressEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/ScreenWillAppearEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/ScreenWillDisappearEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/SearchBarBlurEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/SearchBarChangeTextEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/SearchBarCloseEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/SearchBarFocusEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/SearchBarOpenEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/SearchBarSearchButtonPressEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/StackFinishTransitioningEvent.kt
Fixes #1759
`RCTEventEmitter` was deprecated over 3 years ago in [this commit](https://github.com/facebook/react-native/commit/2fbbdbb2ce897e8da3f471b08b93f167d566db1d)
I don't know when it will be finally deleted, but: 
1. There is no reason to wait for this moment with migration
2. According to the [commit message](https://github.com/facebook/react-native/commit/2fbbdbb2ce897e8da3f471b08b93f167d566db1d) there can be some minor performance improvements on Fabric
3. People complain on wall of warnings during build process
I inspected ReactNative's source code and it seems that parent class impl of `Event.dispatch` method we used up to this point calls `Event.getEventData` internally and if anything is returned it dispatches the event using appropriate event emitter ([see …
> chore(Android): migrate from deprecated `RCTEventEmitter`

- android/gradle.properties
MaxPerm option does not work with Java version >= 17 and it was deprecated many many years ago (looks like it was ignored [since Java 8](https://stackoverflow.com/questions/12114174/what-does-xxmaxpermsize-do))
and recently it was completely removed (using it throws an error). 
From the information I've gathered in "recent" Java versions (>= 8) permament generation space size is not limited thus this options is redundant.
Removed `-XX:MaxPermSize=512m` arg from gradle deamon invocation.
CI
> chore: remove MaxPerm args from JVM invocation

- .github/workflows/android-e2e-test.yml
Attempt to improve our e2e CI run time by adding cache for JDK setup. 
Also use JDK 17, it is not necessary yet, but it will be soon as AGP 8.0 requires it. 
Upgraded JDK to 17 & added JDK cache.
I've also experimented with running on `ubuntu-latest` instead of `macos-12` however emulator fails to start in such case.
> fix(CI): run Android e2e with JDK 17

- .github/workflows/android-build-test-fabric.yml
- .github/workflows/android-build-test.yml
- .github/workflows/ios-build-test-fabric.yml
- .github/workflows/ios-build-test.yml
- .github/workflows/tv-os-build-test.yml
After having iOS build lasting almost 3h (due to poor internet connection on worker, long download time & the machine was extremely slow) I've decided to put timelimit on each workflow run. 
I took a quick look at workflow durations in the past month and it looks like 60 minutes should be enough.
Added `timeout-minutes: 60` for each CI workflow
> chore(CI): put timelimit on execution of each workflow

- windows/RNScreens/RNScreens.vcxproj
- windows/RNScreens/ScreenStack.cpp
- windows/RNScreens/ScreenStack.h
When using a `StackNavigator` on an app on Windows, when you popped the stack you would end up with no displayed content instead of the first page.
The Windows stack implementation wasn't updating `Content` to the top of the stack (after the removal and motification of the vector).
Also the Windows project had an aggressive assertion of SDK version, causing apps to unnecessarily either download an older SDK or patch their app. See https://github.com/react-native-async-storage/async-storage/pull/810 for a similar fix.
```jsx
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
// ,,,
const Stack = createNativeStackNavigator();
export default function App() : JSX.Element {
return (
<NavigationContainer> …
```
> Fix issue when emptying nav stack on Windows

- README.md
Changed expo install react-native-screens to npx expo install react-native-screens, because global expo-cli is deprecated [docs-expo-cli](https://docs.expo.dev/archive/expo-cli/)
- Updated `README.md` docs
> docs: update deprecated expo install instructions to `npx expo install`

- Example/android/build.gradle
- FabricExample/android/build.gradle
- FabricTestExample/android/build.gradle
- TestsExample/android/build.gradle
- android/build.gradle
- android/spotless.gradle
~Won't merge it RN as recent versions of these libraries require sdk >= 33 while current RN setup (clean app) requires >= 31.~
While the statement above holds true new context emerged: since August 2023 all Android apps have to target sdk >= 33 ([link](https://developer.android.com/google/play/requirements/target-sdk))
Thus this should not be a problem. 
* Bumped default Kotlin version to `1.8.22` in example apps
* Bumped default Kotlin version to `1.8.0` in lib (this aligns it with RN 0.73 template)
* Bumped default target & compile target to 34 (notice that this is the default value used by the library, this can be overriden by user in application build.gradle)
* Bumped series of lib depenencies (Android ones) to decently recent versions.
Ci works
> chore: bump library native Android deps & config

- android/src/main/java/com/swmansion/rnscreens/SearchBarView.kt
Currently, when user opens the search bar all of the subviews on the toolbar are being pushed to the left.
Instead, we want to hide them or even remove them so that they won't be visible during the layout.
This PR fixes that problem by secretly hiding the toolbar elements, changing their visibility to `GONE`.
Fixes #1450.
- Added a fix that is being controlled by `handleOpen` and `handleClose` methods in SearchBarView.
https://github.com/software-mansion/react-native-screens/assets/23281839/8ca8e18e-2cf6-4c04-85c8-51b5d69f1a61
https://github.com/software-mansion/react-native-screens/assets/23281839/41330ea7-a12b-4e14-9a1e-2207a54ebed0
In our example app open `SearchBar.tsx` and add `headerRight: () => <Button title="Test"/> to the `navigation.setOptions({` declaration. Then launch the app …
> fix(Android): Change elements visibility on search bar open

- ios/RNSScreenStackHeaderConfig.mm
In the current state, the RTL mode didn't work correctly for large headers and search bar - even if user sets RTL mode in their app, the content of the large header and search was still on the left side. Also, what I've found, the icon of the back button was still pointing to the left, even if the back button was on the right side of the screen.
Fixes #1884.
- Added a workaround for pointing arrow to the left - unfortunately I couldn't find a better solution for changing the direction of the arrow.
- Changed the direction of the contents in the navigation bar when user is in RTL mode.
1. Launch example application from `Example` directory.
2. Switch `Right to left` option to `true`
3. Check `Header Options` and `Search bar` tabs to see the difference.
4. You can also change …
> fix(iOS): Fix positioning of large header and search bar

- src/index.native.tsx
Unification of way the native components are resolved in `index.native.tsx`.
* Every native component is now resolved by `require(<component_spec_file>)` instead of directly querying view registry by using `requireNativeComponent`
* Ensured that every component spec is exported as default from its module
CI & launched native apps -- seems to be working fine. 
TODO: Check backward compatibility of this change
> chore: use `require` syntax for resolution of all native components

- ios/RNSScreen.mm
- ios/RNSScreenStack.mm
- ios/RNSScreenStackHeaderConfig.mm
- src/native-stack/views/NativeStackView.tsx
It looks that sometimes when you're most likely on the first screen the initial header height (taken from the `getDefaultHeaderHeight` method) stays and is not being updated from the `onHeaderHeightChange` event. Also, when user hides the status bar it wasn't counted to the final value of header height. This PR fixes those problems and also other minor issues, related to the calculating header height.
- Added calls for calculating header height on setting animated config and changing `statusBarHidden` prop.
- Changed implementation of `getCalculatedStatusBarHeightIsModal` method.
- Refactorized naming of the methods, related to the header height.
- Added asserting modal hierarchy.
You can change `Modals.tsx` file by adding this snippet:
```js
const headerHeight = …
```
> fix(iOS): change implementation of calculating status bar, refactor methods used on header height change

- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.kt
Currently when user changes status bar and action bar visibility header height is not being changed on `use(Re)animatedHeaderHeight`. This PR fixes this by checking if status bar or action bar has been hidden.
- Fixed calculating header height by taking into account status bar height and action bar height.
You can check how those change works by changing `statusBarHidden` / `headerShown` in Test1802.tsx test.
> fix(Android): Fix calculating header height when changing status/action bar visibility

- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.kt
Small PR which probably resolves [#1515](https://github.com/software-mansion/react-native-screens/issues/1515). 
For my case, I got this build issue after upgrading from 0.72.5 to 0.73.0-rc.2:
```
> Task :react-native-screens:compileDebugKotlin FAILED
e: file:///Users/ivanignatiev/GitHub/****/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.kt:391:46 Unresolved reference: attr
```
I do not know Java or Kotlin, so, please guide me if additional work is needed.
@kkafar: Since AGP 8.0 the default value for `android.nonTransitiveRClass` property [has changed from `false` to `true`](https://developer.android.com/build/releases/past-releases/agp-8-0-0-release-notes). This requires resource file names to be fully qualified. React Native 0.73 …
> fix: Unresolved reference: attr after upgrading to 0.73.0-rc.2

- Example/yarn.lock
- FabricExample/yarn.lock
- FabricTestExample/yarn.lock
- TVOSExample/yarn.lock
- TestsExample/yarn.lock
- yarn.lock
This PR unifies all of the dependabot requests from example apps and library itself for updating `react-devtools-core` from version 4.28.0 to 4.28.4.
- https://github.com/software-mansion/react-native-screens/pull/1935
- https://github.com/software-mansion/react-native-screens/pull/1936
- https://github.com/software-mansion/react-native-screens/pull/1937
- https://github.com/software-mansion/react-native-screens/pull/1938
- https://github.com/software-mansion/react-native-screens/pull/1939
- https://github.com/software-mansion/react-native-screens/pull/1940
> chore(deps): update `react-devtools-core` from 4.28.0 to 4.28.4

- ios/events/RNSHeaderHeightChangeEvent.mm
It looks like when I was implementing class that is representing the `onHeaderHeightChange` I made a mistake and I forgot / accidentally removed `canCoalesce` method which led to displaying `RNSHeaderHeightChangeEvent: unrecognized selector sent to instance` for a couple of users.
This issue resolves that error by adding `canCoalesce` method to the event.
Fixes #1932.
- Added `canCoalesce` method to `RNSHeaderHeightChangeEvent` file
You can test the changes by checking `Test1802.tsx` component in FabricTestExample.
> fix(iOS): add `canCoalesce` method to RNSHeaderHeightChangeEvent

- android/build.gradle
So I've recently bumped versions of few native library dependencies in https://github.com/software-mansion/react-native-screens/pull/1891, but it also bumped some transitive dependencies that conflicted with lower versions that are required by packages such as `gesture-handler`, `reanimated`, `safe-area-context` etc.
I'm downgrading the versions as much I as can while also keeping possible high `material` version.
I downgraded kotlin to `1.6.21` in TestsExample && tested the build.
> fix: downgrade native deps to avoid conflicts with other libs

- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt
I found this working on my app going in portrait mode on Android quite aleatory, when it was supposed to be locked on React Navigation - using the `orientation: "portrait"` on my screens.
(Note : orientation was not locked on the AndroidManifest file, I actually need the landscape mode elsewhere in the app.)
**What is the fix?**
Sometimes when the props `orientation` is set, the fragment and its activity associated are not yet available. So doing a setOrientation in the updateProps function does not work. 
They can also be set directly on the onUpdate function of the ScreenFragment itself, using the `trySetWindowTrait` function and the main activity; but the "super" allowing this behavior to the ScreenStackFragment (=the ones that I use) were not here. 
A similar fix is also done in the …
> fix(Android): update status bar & orientation in screen stack fragment

- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt
- android/src/paper/java/com/swmansion/rnscreens/FabricEnabledViewGroup.kt
We are in the process of migrating to New Architecture. We noticed a suspicious error message in LogCat, and discovered that `FabricEnabledViewGroup`'s state updates in `updateScreenSizeFabric()` would fail with "setState called without a StateWrapper", due to: 
https://github.com/facebook/react-native/blob/79d620dff7561e6c9370184f9f19e79643486716/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/FabricViewStateManager.java#L65
Call `fabricViewStateManager.setStateWrapper()` in `ScreenViewManager.kt`.
Run `FabricExample` and `Example`. View LogCat logs.
> fix(Android): Set stateWrapper in ScreenViewManager in Fabric

- Example/src/screens/Animations.tsx
- Example/src/screens/Events.tsx
- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt
- android/src/main/res/base/anim/rns_slide_in_from_left_ios.xml
- android/src/main/res/base/anim/rns_slide_in_from_right_ios.xml
- android/src/main/res/base/anim/rns_slide_out_to_left_ios.xml
- android/src/main/res/base/anim/rns_slide_out_to_right_ios.xml
- guides/GUIDE_FOR_LIBRARY_AUTHORS.md
- ios/RNSConvert.mm
- ios/RNSScreen.mm
- native-stack/README.md
- src/fabric/ScreenNativeComponent.ts
- src/native-stack/types.tsx
- src/types.tsx
- windows/RNScreens/Screen.h
This PR adds iOS like slide in animation to Android.
But why?
iOS like slide in animations are extremely popular in Android apps. Twitter, Telegram, Slack and many other apps stack navigation resembles or flat out copies iOS behaviour. 
`react-navigation` non native stack gives us ability to have reimplementation of iOS slide in behavior. However, `expo-router` doesn't support non native stack. Besides that if you want native performance and iOS like behavior you are kinda stuck 🤷.
> feat(Android): add ios like slide animation

- .github/workflows/android-build-test-fabric.yml
- .github/workflows/android-build-test.yml
Setting version of JDK to 17 for CI builds as it is required by 0.73 to run.
CI passing should be enough
> chore: use JDK 17 for CI builds as required for RN 0.73

- ios/RNSScreen.mm
Currently, in iOS 17.2 Beta 1-2 there's a bug that causes application to crash after going to the second screen with the video player that contains controls. This PR fixes this issue.
Closes #1967.
- Added an if statement that returns if view is type of `AVPlayerView`, as we don't want to signal it about decelerating (sadly, this header file is not in UIKit's public API 😕.
https://github.com/software-mansion/react-native-screens/assets/23281839/6d040536-45fb-41ea-ad8a-1c86352bf199
https://github.com/software-mansion/react-native-screens/assets/23281839/6da618e4-2bf9-47fb-be9f-e73ae560f081
You can test this change on the repro, attached in the original issue: https://github.com/abanobmikaeel/react-native-video-crash/
> fix(iOS): Don't include AVPlayerView in `traverseForScrollView` method

- .github/workflows/android-build-test-fabric.yml
- .github/workflows/android-build-test.yml
- android/build.gradle
Upcoming react-native 0.73+ includes android gradle plugin 8+ which needs namespace in build.gradle but also needs buildFeatures.buildConfig enabled as well for modules that use it
It is not sufficient to enable this at the top-level app build.gradle, specific modules that use it (such as those that implement new architecture, it seems) must also enable it at the module level
This change was necessary and is in-use in my work app via patch-package as I work through android-gradle-plugin 8+ issues in prep for react-native 0.73 launching for everyone
It should be backwards compatible with older gradle plugins in the exact same way the previous namespace change was, as it is wrapped in the same conditional
It is similar to changes I needed to do as react-native-firebase maintainer --> …
> fix(android): add buildFeatures.buildConfig true for AGP8+ compat

- .github/workflows/android-build-test-fabric.yml
- .github/workflows/android-build-test.yml
- README.md
- ios/RNSScreen.mm
RN 0.73 has MainActivity in kotlin not java
- Updated README.md
> doc: add kotlin MainActiviy.kt to instructions

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- FabricTestExample/ios/Podfile.lock
- TestsExample/ios/Podfile.lock
Just updating all Podfile.lock files to ensure all of them has react-native-screens 3.27.0 version installed.
- Updated React Native Screens to 3.27.0 in Podfile.lock files
> chore: Update Podfile.lock files in example projects

- android/build.gradle
Users are reporting that they are receiving error while building their project with react-native-screens 3.27.0:
```
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
> Duplicate class androidx.lifecycle.ViewModelLazy found in modules jetified-lifecycle-viewmodel-ktx-2.2.0-runtime (androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0) and lifecycle-viewmodel-2.5.0-runtime (androidx.lifecycle:lifecycle-viewmodel:2.5.0)
```
This error is fairly easy to fix and is related to the wrong imports of dependencies in gradle.
Closes #1947.
- Added import for `lifecycle-viewmodel` and `lifecycle-viewmodel-ktx` (these two imports are necessary, as `lifecycle-viewmodel` evokes error for `lifecycle-viewmodel-ktx`.
> fix(Android): Fix error about duplicate class ViewModelLazy

- src/index.native.tsx
Executing side effects in render is usually considered bad manners in react land, and given concurrent rendering could have unexpected results if renders are thrown away.
This change makes it so setImmediate fires in an effect, and also cleans up after itself if for whatever reason the callback isn't fired. (although I think it's probably not possible with how setImmediate is implemented)
N/A
We (at Discord) ran essentially this patch for probably over a year now without issue and figured it might be good to give back.
Here's an issue related to it: https://github.com/software-mansion/react-native-screens/issues/1198
> fix: move DelayedFreeze setImmediate into an effect

- android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt
Currently when user tries to change the appearance of the navigation bar (using navigationBarHidden / navigationBarColor props) the content of the screen jumps to the place that does not respect safeAreaView. This PR fixes it by removing `decorFitsSystemWindow` declaration, as it breaks the interface by matching it to `fit system window`.
Resolves #1719.
- Removed `decorFitsSystemWindow` call from `ScreenWindowTraits.kt`
> fix(Android): modify the decorFitsSystemWindow parameter in setNavigationBarHidden

- FabricTestExample/App.js
- FabricTestExample/src/Test1981.tsx
- TestsExample/App.js
- TestsExample/src/Test1981.tsx
- ios/RNSScreen.mm
- ios/RNSScreenStack.mm
Since #1825 header config is no longer first child of a screen & `hitTest:withEvent:` method assumed this invariant to be true.
Fixed that by using appropriate screen method instead of blind assumption.
Fixes #1981
* Fixed `hitTest:withEvent:` method by using `findHeaderConfig` `RNSScreenView`'s method
* Improved `findHeaderConfig` method itself
`Test1981`
> fix(iOS): not working hitslop for headerRight/Left views

- Example/src/screens/Modals.tsx
- TestsExample/App.js
- ios/RNSScreenStack.mm
Updated logic in `RNSScreenStackView#setModalViewControllers:` so that it handles case when navigating back from top-level VC that was not presented
by the screen stack itself, as it happens with `UIModalPresentationCurrentContext` & `UIModalPresentationOverCurrentContext`.
Fixes #1813
We now check whether the top-level VC should be dismissed by the stack being asked.
See #1813 for reproduction steps.
I'm also adding these in `Example` application.
> fix(iOS): app freeze when navigating back from any modal nested in contained modal

- android/src/main/java/com/swmansion/rnscreens/CustomSearchView.kt
- android/src/main/java/com/swmansion/rnscreens/FragmentBackPressOverrider.kt
- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenFragment.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfigViewManager.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderSubview.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderSubviewManager.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackViewManager.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt
- android/src/main/java/com/swmansion/rnscreens/ScreensShadowNode.kt
- android/src/main/java/com/swmansion/rnscreens/SearchBarView.kt
- android/src/main/java/com/swmansion/rnscreens/SearchViewFormatter.kt
- android/src/main/java/com/swmansion/rnscreens/events/HeaderAttachedEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/HeaderBackButtonClickedEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/HeaderDetachedEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/HeaderHeightChangeEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/ScreenTransitionProgressEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/SearchBarBlurEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/SearchBarChangeTextEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/SearchBarCloseEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/SearchBarFocusEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/SearchBarOpenEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/SearchBarSearchButtonPressEvent.kt
Up to now we had mixed naming conventions -> I've applied [Android official ones](https://developer.android.com/kotlin/style-guide#naming_2)
Refactored whole library code so that we stick to single naming convention
Run any example & see that it runs as it should
> refact(Android): unify member-field naming convention in Kotlin

- README.md
So in [discussion](https://github.com/software-mansion/react-native-screens/issues/1985#issuecomment-1875344124) of #1985 I was just made aware that we did not
update supported react-native versions in our readme, leading to some confusion.
Updated the readme & also release notes of 3.28.0
N/A
> chore(docs): update compatibility table with supported RN versions with Fabric

- FabricTestExample/App.js
- FabricTestExample/src/Test2008.tsx
- TestsExample/App.js
- TestsExample/src/Test2008.tsx
- ios/RNSScreen.mm
Normally, while opening a modal, each screen should preserve its safe area, depending on the screen orientation. Unfortunately, when user dismisses transparent modals, safe area of the origin screen breaks, resulting in the vertical safe area on landscape orientation. 
Because of that, I investigated the logic behind the final decision of screen orientations and it looks like the problem was lying on `supportedScreenOrientations` method in RNSScreen.mm file.
1. First, the modal was being asked for its supported device orientation. Once it reached the `supportedScreenOrientations` method, it was asking for config of childVC. Because the childVC was `nil` and the orientation wasn't set in screen options, it was returning `nil`, resulting in returning all orientations without `upside down`. …
> fix(iOS): Fix incorrect safe area on transparent modals using landscape orientation

- src/index.native.tsx
- src/native-stack/views/NativeStackView.tsx
Previously, after going from one screen to another (or after opening the app) there was an error regarding ScreenGestureDetector:
`Warning: Invalid prop 'gestureDetectorBridge' supplied to 'React.Fragment'. React.Fragment can only have 'key' and 'children' props.`
This error indicates that we were passing props from ScreenGestureDetector to React.Fragment. Indeed, after looking onto the default value of GHContext, there was a Fragment that was receiving invalid props.
This PR fixes this by changing the look of React.Fragment, so we won't pass the props further.
Also, I've added a warning that is being shown when user tries to use `goBackGesture` and the navigator is not wrapped in ScreenGestureDetector.
Fixes #2010.
- Fix warning of React.Fragment when the ScreenGestureDetector isn't …
> fix: change default value of context of ScreenGestureDetector, add warning for goBackGesture

- src/gesture-handler/GestureDetectorProvider.tsx
- src/gesture-handler/index.tsx
- src/index.tsx
- src/native-stack/contexts/GHContext.tsx
Unfortunately, because of changing the way how we export the components, I didn't saw the wrong export of GHContext in gesture-handler's `index.tsx` file. To match the changes from the PR with full screen swipe (#1913), I've created the directory in a wrong place. This PR fixes this export by moving the context to native-stack and removing the export from the gesture-handler/index.tsx.
I'm also removing this export, because right now it's possible to import GHContext from `react-native-screens` and also from `react-native-screens/gesture-handler` which is wrong.
- Changed the export of GHContext in index.tsx
- Moved GHContext from gesture-handler to native-stack
Try to build and run TestsExample - see if the bundling state passes correctly. Then, try to import GestureDetectorProvider and …
> fix: move GHContext from gesture-handler to native-stack

- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.kt
I've been discussing this change with @WoLewicki.
The problem here is that you're attempting to call `runOnUiQueueThread` on the wrong Context.
Changes the `Context` where we invoke `.runOnUiQueueThread`
Tested against this reproducer:
https://github.com/cortinico/reproducer-rnscreens-bridgeless
> fix(Android): change context while running `runOnUiQueueThread` on 0.73 with Bridgeless

- ios/RNSScreenWindowTraits.mm
This fixes two issues with scenes on iOS:
1. A casting issue, which allows non-window scenes on iOS, e.g. CarPlay's CPTemplateApplicationScene
3. An assumed loading order - the UIWindowScene is not guaranteed to be the first scene (or even present) in a multi-scene app
Fixes #1857
**Edit:** I originally reported that this would only fix the second crash reported in #1857. Upon review of the first crash in that issue, I believe this PR actually addresses both crashes.
There really isn't any simple code that can be used to test this, as this scenario requires having an app that implements multiple scenes, at least one of which being CarPlay. It would be several hundred lines of code.
> fix(iOS): Check for multiple screens while changing screen orientation

- ios/RNSScreen.mm
This PR fixes the behaviour of `useAnimatedHeaderHeight`, when header is not shown.
Currently, it includes the status bar height when `headerShown` prop is false. This is wrong, since we don't have a header in such scenario and we don't want to include status bar there. Therefore, when navigation controller does not exist or `isNavigationBarHidden` is set to true, we simply return 0.
- Removed calculating status bar height when header is not shown.
You can use `Test1802.tsx` to test these changes.
> fix(iOS): Remove calculating status bar height in useAnimatedHeaderHeight when header is not shown

- Example/yarn.lock
- FabricExample/yarn.lock
- FabricTestExample/yarn.lock
- TVOSExample/yarn.lock
- TestsExample/yarn.lock
Just aggregating dependabot PRs with the version updates of `ip` package from 1.1.8 to 1.1.9.
For the context, this change is made because of the latest vulnerability that has been exposed in `ip` library. The version of this package is vulnerable to Server-Side Request Forgery (SSRF) attacks (CVE: https://github.com/advisories/GHSA-78xj-cgh5-2h22).
- https://github.com/software-mansion/react-native-screens/pull/2039
- https://github.com/software-mansion/react-native-screens/pull/2040
- https://github.com/software-mansion/react-native-screens/pull/2041
- https://github.com/software-mansion/react-native-screens/pull/2042
- https://github.com/software-mansion/react-native-screens/pull/2043
> chore(deps): bump ip from 1.1.8 to 1.1.9 in example apps

- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.kt
Potential fix for changes from https://github.com/software-mansion/react-native-screens/pull/2022, see comment https://github.com/software-mansion/react-native-screens/pull/2022#issuecomment-1957369797
> fix(Android): use reactApplicationContext in onScreenChanged

- README.md
- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt
Since React Native Screens 3.30.0, we will support only 0.68+ versions of React Native. This PR drops support for the versions, lower than that revision.
- Added row to the table of supported versions in README
- Added missing bullet point for supporting visionOS
- Removed unnecessary annotation
- Removed note about bug in RN 0.61 (sadly this still occurs in newest RN)
> chore: drop React Native 0.64 - 0.67 since 3.30.0

- ios/RNSModule.mm
This PR fixes problem with goBackGesture screen transition. If stackView can not be found, transition just shouldn't start instead of crashing app and throwing the `Invalid view type, expecting RNSScreenStackView` error.
> fix(iOS): Add view check for getting StackView in `goBackGesture`

- android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt
- android/src/main/res/v33/anim-v33/rns_default_enter_in.xml
- android/src/main/res/v33/anim-v33/rns_default_enter_out.xml
There was some issues with android animation, the root cause is the drawing order, not the actual animations. This reverts the changes to the animations so it matches stock android ones and always reverse drawing order for android api 33+.
Revert the animation changes in https://github.com/software-mansion/react-native-screens/commit/00543fb35201e34dfb5e73e22ff12d274a1ea5f5 and https://github.com/software-mansion/react-native-screens/commit/05f4dd7c77608010d3990ae2af3ec54d5f735760.
Return true from needsDrawReordering when api 33+.
Here you can add screenshots / GIFs documenting your change.
You can add before / after section if you're changing some behavior.
Api 33
https://github.com/software-mansion/react-native-screens/assets/2677334/8777838c-a2bb-4e43-bcc2-a9a51926eeb9
The mitigations …
> fix: android screen stack animation

- guides/GUIDE_FOR_LIBRARY_AUTHORS.md
- ios/RNSConvert.mm
- ios/RNSEnums.h
- ios/RNSScreen.mm
- ios/RNSScreenStack.mm
- ios/RNSScreenStackAnimator.mm
- native-stack/README.md
- src/native-stack/types.tsx
- src/types.tsx
Before `slide_from_left` transition was resolved to default transition on iOS. Now this transition will make screen to appear from left side to right.
- updated docs;
- added `RNSScreenStackAnimationSlideFromLeft` to enum value;
- added `animateSlideFromLeftWithTransitionContext` method;
- added support for reverse gestures (from right to left to close a screen);
https://github.com/software-mansion/react-native-screens/assets/22820318/e0a71147-0aea-47ef-9d4b-319d7fd8dd81
- Open `Animations` screen
- select `slide_from_left` animation
- open "New screen"
- if you want to test gesture for dismissing the screen, you'll need to specify `<Stack.Screen name="Screen" options={{ customAnimationOnSwipe: true }}>`
> feat(iOS): Add `slide_from_left` transition

- android/gradle/wrapper/gradle-wrapper.properties
- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.kt
This PR reverts the change from another PR #2028 that removed notifying about header height change event. Also, here I've also included changes that are fixing incorrect values being returned from `calculateHeaderHeight()` function, which causes to move the target of the touchables 🚀 
- Fixed incorrect values, returned from `calculateHeaderHeight` method
- Reverted notifying about header height change
You can check `Test556.tsx` and `Test1072.tsx` to check if touchables are working correctly.
> fix(Android): add notifying for header height change, fix header height values

- package.json
This PR resolves issue with not working installation on react-native-screens on 3.30.0. It seems that `postinstall` step is breaking due to not finding `react-navigation` submodule.
- Removed postinstall step from package.json
> fix: remove postinstall step from package.json

- android/build.gradle
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt
This PR fixes backward compatibility with React Native versions older than 0.71. The issue was caused by using prefabs in the screen transition animation feature. I added a check that makes this feature available since React Native 0.71
Tested against RN versions:
Fixes https://github.com/software-mansion/react-native-screens/issues/2082
> fix(Android): Add backward compatibility for prefabs

- FabricTestExample/ios/Podfile.lock
- FabricTestExample/package.json
- FabricTestExample/yarn.lock
- ios/RNSScreenStack.mm
Some time ago, I've introduced a [fix](https://github.com/software-mansion/react-native-screens/commit/3b35894f1f83bc4c9daa518d68f3bcb0e832129a#diff-547f3e256039a77611e8a361cd680f6c4ddd17f1e057dea113777001a7b37cc3R617) for Fabric for scenario, when user tries to navigate to two (or more) different screens at the same time. Unfortunately, regression shows that it's not possible for now to navigate on more than one screen, because of this change. This PR reverts that change.
- Reverted a fix for navigating to more than one screen at the same time
- Updated React Native in FabricTestExample to 0.74.0-rc.6
https://github.com/software-mansion/react-native-screens/assets/23281839/779d1b43-56ae-4a55-8fc5-0594093ce884
https://github.com/software-mansion/react-native-screens/assets/23281839/ea9e421 …
> fix(iOS): Fix screen traversing on Fabric, update React Native to rc.6

- package.json
- src/native-stack/types.tsx
- yarn.lock
It seems that [here](https://github.com/software-mansion/react-native-reanimated/commit/80bcfd8793199a9dc99f430c3e440103c99a9667), Reanimated has changed their API and change the naming of used props to `topScreenStyle` and `belowTopScreenStyle`. This PR resolves this change by matching the naming to their API.
- Updated Reanimated to nightly 3.9.0
- Changed naming of `topScreenFrame` and `belowTopScreenFrame` props
> fix: change topScreenFrame and belowTopScreenFrame to match Reanimated API

- src/components/Screen.tsx
- src/fabric/ModalScreenNativeComponent.ts
- src/fabric/ScreenNativeComponent.ts
- src/fabric/ScreenStackHeaderConfigNativeComponent.ts
- src/fabric/SearchBarNativeComponent.ts
Add missing `ScreenStackHeaderConfig` events to fabric spec and remove the manual registration of events.
Also changed `Bubbling` events to `Direct` which fixes extraneous lifecycle events. It was to be done quite a while ago already: https://github.com/software-mansion/react-native-screens/pull/1308#discussion_r805773152
> fix: add missing events

- ios/RNSFullWindowOverlay.mm
This PR is a follow up for the PR #1526.
Currently, in React Native there's `RCTKeyWindow()` method which goes through each window of `RCTSharedApplication()` and selects the window that is a key window of a given window. This is a better solution, since we don't rely on a single `keyWindow` from RCTSharedApplication.
I've also added a support for Fabric.
I've checked how does FullWindowOverlay work with the change and it works as usual.
Closes #1526.
- Changed the method of retrieving window from `delegate.window` to `RCTKeyWindow()`
You can run `Test1844` and check if FullWindowOverlay works correctly.
> fix(iOS): Change retrieving window in FullWindowOverlay

- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- android/src/main/java/com/swmansion/rnscreens/events/HeaderAttachedEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/HeaderBackButtonClickedEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/HeaderDetachedEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/HeaderHeightChangeEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/ScreenTransitionProgressEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/SearchBarBlurEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/SearchBarChangeTextEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/SearchBarCloseEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/SearchBarFocusEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/SearchBarOpenEvent.kt
- android/src/main/java/com/swmansion/rnscreens/events/SearchBarSearchButtonPressEvent.kt
Currently, on Android every event has one class, putted in generic - `ScreenAppearEvent`. This seems to be wrong, as every event should have their own class inside `Event` generic. This PR changes this by replacing `ScreenAppearEvent` to the appropriate event class.
- Replaced ScreenAppearEvent to appropriate event types inside generics.
> chore(Android): fix emit type parameters

- src/components/Screen.tsx
All navigators except `native-stack` does not set `stackPresentation` so it resolved in `AnimatedNativeModalScreen` making all navigators that are nested or under some views not work with pressability. Follow-up to https://github.com/software-mansion/react-native-screens/pull/2028/
- Added `undefined` case for setting AnimatedNativeScreen
You can check `Test1214.tsx` or `Test2028.tsx` (after changing import to `@react-navigation/stack`) in order to test targets of touchables.
> fix: don't use AnimatedNativeScreen when stackPresentation prop is not set

- package.json
This PR intents to fix error, during the install step on other React Native applications. That's because of the name of the step - it shouldn't be named as `postinstall`, as method named this way is triggered by yarn v4. This was not an issue before, as we used yarn v1.
Fixes #2108.
- Changed `postinstall` name to `prepare` in package.json
- Added `yarn prepare` command during the `yarn release`.
> fix: Change postinstall step to prepare and run prepare on release in package.json

- FabricTestExample/App.js
- FabricTestExample/src/Test2048.tsx
- TestsExample/App.js
- TestsExample/src/Test2048.tsx
- ios/RNSScreenStack.mm
Basically this is another edition of the issue #1829 (handled by #1912).
The issue comes down to the fact, that our `ScreenStack` is not aware of all modal view controllers being in presentation,
but this time it is not aware of third-party modal view controllers (I've named them "foreign" modals in opposite to "owned" modals).
This PR is not a comprehensive solution but rather just a patch aiming at fixing one particular interaction reported in #2048.
I've left verbose code comments explaining the issue and suggesting solution in the source code, including:
```
// TODO: Find general way to manage owned and foreign modal view controllers and refactor this code. Consider building
// model first (data structue, attempting to be aware of all modals in presentation and some text-like …
```
> fix: issues with presenting owned modals from foreign ones

- ios/RNSScreenStackHeaderConfig.mm
Restore the iOS native behavior of automatically shorting the title of the header back button to "Back" if there is not enough space, which is documented [here](https://reactnavigation.org/docs/header-buttons#customizing-the-back-button)[^1] but does not behave as expected since v3.21.
Fixes #1589.
* Assign to `backBarButtonItem` only if actual customizations of the back button are being made.
| Before | After |
|--------|------|
| ![Broken 1](https://github.com/software-mansion/react-native-screens/assets/3784687/880eaecb-54d9-48d3-95bd-5f8e6cd7b066) | ![Working 1](https://github.com/software-mansion/react-native-screens/assets/3784687/201e8006-544d-43ee-95e3-308e2f926566) |
[^1]: According to the document, 'On iOS this includes a label next to the button, which shows the title of the …
> fix(iOS): restore native behavior of auto shortening back button title

- src/components/Screen.tsx
This PR intents to change Screen component into a functional component.
> refactor: screen rewritten as functional component

- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt
- android/src/main/java/com/swmansion/rnscreens/events/HeaderHeightChangeEvent.kt
This PR intents to fix some "Deprecated in Java" warnings when building on android. I decided not to suppress warnings manually when it is inescapable to avoid the warning.
Fixes #2018 
- replaced deprecated targetElavation with elevation
- adjusted usage of porter duff color filter
- calculating header top inset using recent method if android API >= 30 (the warning persists as the previous APIs still require deprecated method)
- fixed guarded runnable deprecated warning
- removed unused import
```
> Task :react-native-screens:compileDebugKotlin
'compileDebugJavaWithJavac' task (current target is 11) and 'compileDebugKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
w: …
```
> fix(Android): fix build deprecations

- android/src/main/java/com/swmansion/rnscreens/ScreensModule.kt
Fixes https://github.com/software-mansion/react-native-screens/issues/2115
The `System.loadLibrary("rnscreens")` can throw an exception that inherits from the `Error` class instead of the `Exception` class.
> Catch UnsatisfiedLinkError

- src/components/SearchBar.tsx
This PR intents to change SearchBar component into a functional component.
Rewritten SearchBar component as function leveraging useImperativeHandle to apply new methods
> refactor: searchbar rewritten as functional component

- android/src/main/cpp/jni-adapter.cpp
- common/cpp/react/renderer/components/rnscreens/RNSModalScreenComponentDescriptor.h
- common/cpp/react/renderer/components/rnscreens/RNSModalScreenShadowNode.h
- common/cpp/react/renderer/components/rnscreens/RNSScreenComponentDescriptor.h
- common/cpp/react/renderer/components/rnscreens/RNSScreenShadowNode.h
- common/cpp/react/renderer/components/rnscreens/RNSScreenState.cpp
- common/cpp/react/renderer/components/rnscreens/RNSScreenState.h
- cpp/RNScreensTurboModule.cpp
- cpp/RNScreensTurboModule.h
- package.json
PR adding formatting of all cpp codebase.
> chore: add formatting of all cpp

- android/build.gradle
Currently when you build Fabric app and then Paper app Android Studio has errors about duplicated classes. This should resolve that issue. 
**Test:**
Packed with `npm pack` and tested on new expo app. Seems that everything is fine.
> fix: error when building paper after fabric

- ios/RNSModule.mm
Similar to https://github.com/software-mansion/react-native-reanimated/pull/5953,  using `[RCTBridge currentBridge]` may lead to the wrong bridge in apps that have multiple React instances, as is the case for expo-dev-client. This results in apps sometimes crashing when reloading the bundle after interacting with the DevMenu.
Instead of using `[RCTBridge currentBridge]` we can just call `self.bridge` and ensure the correct bridge is always used
> Prevent iOS host object installation from getting the wrong bridge

- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerDelegate.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerInterface.java
- src/fabric/ModalScreenNativeComponent.ts
- src/fabric/ScreenNativeComponent.ts
- src/native-stack/types.tsx
- src/native-stack/views/NativeStackView.tsx
- src/types.tsx
Once upon a time there was an [issue](https://github.com/software-mansion/react-native-screens/issues/1719) regarding navigation bar. The problem was that the background color set to the navigation bar covered the content behind, see examples:
<table>
<tr>
<th>navigationBarColor: 'transparent'</th>
<th>navigationBarColor: 'yellow'</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Then [PR 1988](https://github.com/software-mansion/react-native-screens/pull/1988) solved the issue, but introduced another problem: sometimes it may be intended to have content behind the navigation bar.
<table>
<tr>
<th>navigationBarColor: 'transparent' after PR 1988</th>
<th>navigationBarColor: 'transparent' before PR 1988</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
This PR intents to add a new …
> feat(Android): added navigationBarTranslucent option

- ios/RNSScreenContainer.mm
Ensures `RNSScreenContainer` `UIView` subclass calls a designated initializer, this fixes an issue where subclassing `RNSScreenContainer` would recursively loop through the inits - ending in a crash.
`UIView.h` has:
`- (instancetype)initWithFrame:(CGRect)frame NS_DESIGNATED_INITIALIZER;`
> fix: change `-[RNSScreenContainer init]` to call `-[UIView initWithFrame:]` designated initalizer

- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
Basically tasks run from react-native-screens repo (such as linting & formating) would fail due to outdated gradle wrapper version (and the fact that we re using newer JDK now).
There was a second issue: when running tasks from react-native-screens project as gradle's `rootProject` and simultaneously having `react-native` repo side-by-side to `react-native-screens`
repo on disk - our current react native directory resolution algorithm would have found it and attempt to use to retrieve RN version, but:
1. the gradle.properties file is not there,
2. retrieved version could be out of sync with what's in project.
* Bumped gradle wrapper version to 7.5.1 (we were still on major 6).
* Adjusted the react native directory algorithm just a bit, so that when running in context of screens repo we …
> fix: bump gradle wrapper version to 7.5.1 & not use app node_modules when running tasks from repo

- apps/test-examples/App.js
- apps/test-examples/src/Test2184.tsx
- ios/RNSScreen.mm
PR adding calling `onGestureCancel` when trying to dismiss a modal with `gestureEnabled` set to `false`.
> feat: call onGestureCancel in modal too

- README.md
Doing so just before 3.32.0 release
Last supported RN version bumped to 0.71.0.
Last supported RN version for Fabric bumped to 0.74.0.
> chore: bump supported `react-native` versions in readme

- common/cpp/react/renderer/components/rnscreens/utils/RectUtil.h
The `eps` parameter in `compareFrameSizes` should be `const`. 
Both functions can be `constexpr` so I've marked them as such.
> [!note]
When doing a bit of research for this PR I've learned that [`constexpr` implies `inline` linkage (so also bending the ODR rule)](https://stackoverflow.com/a/14391320/8635522) for functions (and it seems that since C++17 also for namespace scoped variables) and must admit I was not aware of this before, thus I've come to conclusion that it will be ok to leave `inline` keyword there, so that the intent of `inline` linkage is clear.
Build Android / iOS
> chore: make eps parameter const & functions constexpr in RectUtil

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- FabricTestExample/ios/Podfile.lock
- TVOSExample/ios/Podfile.lock
- TestsExample/ios/Podfile.lock
So that this does not come up randomly in various PRs as unrelated changes.
- **Bump in TE**
- **Bump in FTE**
- **Bump in Example**
- **Bump in FabricExample**
- **Bump in TVOSExample**
N/A
> chore: reinstall pods in examples after release

- android/src/main/java/com/swmansion/rnscreens/RNScreensPackage.kt
- android/src/main/java/com/swmansion/rnscreens/utils/ScreenDummyLayoutHelper.kt
My recent PR:
* https://github.com/software-mansion/react-native-screens/pull/2169
introduced creation of dummy layout, which requires react context to be attached to activity, as we need access
to the activity. Unfortunately when running on Paper the context is not attached to the activity yet, resulting 
in exception being thrown.
<details>
<summary>Exception</summary>
```
Failed to create NativeModule 'UIManager'
java.lang.IllegalArgumentException: [RNScreens] Attempt to use context detached from activity
at com.swmansion.rnscreens.utils.ScreenDummyLayoutHelper.ensureDummyLayoutWithHeader(ScreenDummyLayoutHelper.kt:68)
at com.swmansion.rnscreens.utils.ScreenDummyLayoutHelper.<init>(ScreenDummyLayoutHelper.kt:53)
at com.swmansion.rnscreens.RNScreensPackage.createViewManagers(RNScreensPac …
```
> fix(Android, Paper): apps soft crash on exception due to detached context

- .github/workflows/android-e2e-test.yml
This PR intents to move android e2e test to ubuntu to avoid random crashes. Inspired by changes made by @kirillzyusko in [react-native-keyboard-controller](https://github.com/kirillzyusko/react-native-keyboard-controller).
- Changed workflow's `runs-on`
- Bump deps
- Added necessary extra steps
> chore: moved android e2e to ubuntu

- apps/examples/src/screens/Animations.tsx
- apps/test-examples/src/Test1097.tsx
- apps/test-examples/src/Test1166/AndroidDifferentScreenSearch.tsx
- apps/test-examples/src/Test556.js
- apps/test-examples/src/Test624.js
- apps/test-examples/src/Test645.js
- apps/test-examples/src/Test648.js
- apps/test-examples/src/Test649.js
- apps/test-examples/src/Test654.js
This PR intents to migrate examples to react-navigation v7.
Documentation: https://reactnavigation.org/docs/7.x/upgrading-from-6.x/
As for now I have only found ~~two~~ few files that needed changes. I ensured that nothing crashes in the example.
- migrated navigating to nested screen
- replaced `navigate` with `popTo` when explicitly going back to a specific screen
- ensured nothing crashes
> chore: migrate examples to react-navigation v7

- Example/metro.config.js
- FabricExample/metro.config.js
- FabricTestExample/metro.config.js
- TVOSExample/metro.config.js
- TestsExample/metro.config.js
The custom resolver implemented in our `metro.config.js` right now most likely does not conver all cases.
When working on my PR with modals for Android I've added `jotai` package and received errors from bundler that this package is not found,
because: 
1. it was not present in any nearby `node_modules` - the file that requries it resides now in `apps/test-examples`, thus application `node_modules` are not checked by default,
2. only our custom resolver looks into apps `node_modules` & fails to resolve this package. 
I haven't investigated why it does not work for `jotai` in particular, because more general solution is to just let the default module resolution algorithm look into
application `node_modules` as it should always do.
Added application `node_modules` to the list of additional …
> fix(examples): allow project node_modules to be used

- .github/workflows/close-when-stale.yml
1. Aligning with recent move in Reanimated
2. This is purely subjective: stale issues hanging for three weeks is too much
Changed `days-to-close` from 20 to 14.
N/A
N/A
> chore(CI): close stale issues after 2 weeks

- apps/test-examples/App.js
- apps/test-examples/src/Test2002.tsx
- ios/RNSModalScreen.mm
This PR fixes the color scheme adaptability when using `presentation: fullScreenModal`.
When changing the appearance mode between `light` and `dark` the screens reacted immediately except for the fullScreenModal presentation style.
When using a `UIModalPresentationFullScreen` the views belonging to the presenting view controller are removed after the presentation completes. After investigating the view hierarchy for a screen with `presentation: fullScreenModal` it turned out that the `RCTRootView` is removed, thus the `traitCollectionDidChange` observer ([see here](https://github.com/facebook/react-native/blob/d3e0430deac573fd44792e6005d5de20e9ad2797/packages/react-native/React/Base/RCTRootView.m#L362)) is not working anymore.
The solution was to add an extra observer for …
> fix(iOS): fullscreenmodal color scheme adaptability

- ios/RNSConvert.h
This PR fixes React Native screens not building on visionOS. As this platform needs explicit imports for used modules
- Fixed building `RNSConvert.h` for visionOS
Compile on visionOS
> fix: react-native-screens not building on visionOS

- ios/RNSScreenStackHeaderConfig.mm
This PR intents to fix back button direction in RTL mode forced by I18nManager for testing purposes on iOS.
When the application's language is changed using the `CFBundleDevelopmentRegion` the system is well aware of that, passes the information to React Native and Yoga. The result is a fully LTR / RTL compliant application.
However, when the `RTL` mode is set using the React Native's `I18nManager.forceRTL()` method (for testing purposes I believe) The change is applied to react views only and the system itself does not change it's direction.
In such case the only way for the native elements, such as `navigationBar` to adapt to the direction set by `I18nManager` is by manually applying the `semanticContentAttribute` based on `direction` prop passed by `react-navigation`.
> [!note]
In case …
> fix(iOS): back button does not respect I18nManager & improve RTL handling in header

- common/cpp/react/renderer/components/rnscreens/RNSScreenComponentDescriptor.h
The error check was bad - it reported error each time the frames were the same.
Obviously it shoud report frame mismatch.
Added missing negation.
> fix(Android): missing negation in check for mismatched frames

- apps/test-examples/App.js
- apps/test-examples/src/Test2223.tsx
- ios/utils/UIView+RNSUtility.mm
In #2193 I've made a mistake - on Paper, when there is no touch handler held in `_touchHandler` field I've started 
lookup for touch handler in ancestor chain from `self` -> which leads to infinite loop when swiping back in nested-stack navigation scenario.
* Started lookup from superview.
`Test2223`
1. Navigate to NestedStack.
2. Navigate to NestedStack details screen.
3. Use swipe gesture to go-back
W/o this PR the application will crash hitting infinite loop.
Also test that this behaviour remains fixed:
* https://github.com/software-mansion/react-native-screens/pull/2131
> fix(iOS, Paper): possibility of infinite loop when swiping back in nested stack

- .github/workflows/android-e2e-test.yml
- .github/workflows/ios-e2e-test.yml
I noticed there's an unnecessary step in the worklfow both for iOS and android e2e tests. 
The step is supposed to install any dependencies inside `examples/app` but there's no `package.json` file.
This PR removes the step.
- removed workflow step
> refact: remove unnecessary workflow step

- .github/workflows/android-build-test-fabric.yml
- .github/workflows/android-build-test.yml
- .github/workflows/close-when-stale.yml
- .github/workflows/ios-build-test-fabric.yml
- .github/workflows/ios-build-test.yml
- .github/workflows/ios-e2e-test.yml
- .github/workflows/main.yml
- .github/workflows/needs-more-info.yml
- .github/workflows/needs-repro.yml
- .github/workflows/platforms.yml
- .github/workflows/tv-os-build-test.yml
This PR bumps dependencies used in workflows to the latest versions
In most cases bump to v3 means that the Node runtime is updated from 12 to 16 and bump to v4 means it's updated to 20.
Additional changes are not affecting our workflows and are as follows:
- actions/setup-node@v3 changed flag name from `version` to `node-version`
- actions/cache@v4 added a new flag `save-always`
- actions/upload-artifact@v4 changed how operating on multiple files works: [migration docs](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md)
> chore: bump worklfow deps

- apps/test-examples/App.js
- apps/test-examples/src/Test2227.tsx
- ios/RNSScreenStack.mm
Doing the swipe also caused programmatic push to use manual transition and have no shadow.
Fixes #2227.
Set `_isFullWidthSwiping` to `NO` when swipe gesture ends in `handleSwipe:` so programmatic push and pop can use OS logic by default.
https://github.com/software-mansion/react-native-screens/assets/11507974/0f710aec-c8f0-4a3a-82df-d3edb5f0fb19
https://github.com/software-mansion/react-native-screens/assets/11507974/51119c74-b2c3-4c32-9202-6954c3c70218
1. Run `Test2227` in TestsExample app.
2. Push screen with `Go to Details`.
3. Swipe back with full screen swipe gesture.
4. Push screen with `Go to Details` again.
7. Before this fix there would be no shadow during transition after first full screen swipe back.
> fix(iOS): push and pop transitions change after full screen back swipe 

- apps/Example.tsx
- apps/src/screens/Events.tsx
- apps/src/screens/HeaderOptions.tsx
- apps/src/screens/SearchBar.tsx
- apps/src/screens/StackPresentation.tsx
- apps/src/shared/Form.tsx
- apps/src/shared/ListItem.tsx
- apps/src/shared/SettingsInput.tsx
- apps/src/shared/SettingsPicker.tsx
- apps/src/shared/SettingsSwitch.tsx
- apps/src/shared/ThemedText.tsx
- apps/src/shared/ThemedTextInput.tsx
- apps/src/shared/ThemedView.tsx
- apps/src/shared/index.ts
This PR adds dark theme to the example app. The theme changes automatically based on the device's appearance setting and can be changed by clicking a button.
- added dark styles to screens and components
- added a state and listener for basic theme management
- added a dark mode button
https://github.com/software-mansion/react-native-screens/assets/91994767/c156eaa7-7603-4f92-b1a2-5599e33ecc3f
https://github.com/software-mansion/react-native-screens/assets/91994767/5e479905-b046-4ea4-bfc1-1667837eee60
- Use the Example app
- Toggle the theme with a button or by changing device's setting
- Browse screens
> feat: added dark theme to example

- RNScreens.podspec
Since we support RN from 0.71, and `install_modules_dependencies` is already available there, we can remove the unused code.
> chore: remove unused code in podspec

- ios/RNSScreenStackHeaderConfig.mm
This PR intents to fix navigation bar appearance customization on tvOS.
Now it's impossible to customize the navigation bar on tvOS. The options, such as `headerTintColor` are not applied at all and the defaults are making it hard to read when the appearance is set to `dark` on the device:
- title text color defaults to white
- backgroundColor of modal screens header defaults to dark gray
In current implementation the appearance is set on the navigationItem, like this:  `navigationItem.standardAppearance = appearance`. Out of curiosity I tried setting the appearance on navigationBar as found in [this article](https://developer.apple.com/documentation/uikit/uinavigationcontroller/customizing_your_app_s_navigation_bar?language=objc), like this: `navigationBar.standardAppearance = …
> fix(TVOS): navbar appearance customization

- android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt
Initially reported & solution proposed by @corbella83.
Newer OpenJDK versions have introduced `List.removeLast` / `List.removeFirst` methods, which haven't existed in JDK before and were provided by Kotlin std lib `kotlin-std`. Android SDK 35 aligns with recent OpenJDK versions & when compiling with SDK 35 the method call is statically resolved to the function from JDK and not to the one from `kotlin-std`. Thus when running on lower version of runtime (<= 34) there is no such method available at runtime (at address resolved in compile time) leading to runtime crash. 
Section in Android docs describing this: https://developer.android.com/about/versions/15/behavior-changes-15?hl=en#openjdk-api-changes
Fixes #2257
* Replaced call to `drawingOpList.removeLast` with …
> fix(Android): comply to breaking changes in Android SDK 35

- ios/RNSScreenStack.mm
> [!note] 
This PR applies to iOS only. 
Ok, so this PR is related to #2247 & to get broader context I highly recommend to read [this comment](https://github.com/software-mansion/react-native-screens/pull/2247#pullrequestreview-2191107600) at the very minimum. 
On Fabric during JS initialised Screen dismissal (view removing in general) children are unmounted before their parents, thus when dismissing screen from screen stack & starting a dismiss transition all Screen content is already removed & we're animating only a blank screen resulting in visual glitch. 
Right now we're utilising `RCTMountingTransactionObserving` protocol, filter all mounting operations *before* they are applied and if screen dismissal is to be done, we take a snapshot of to-be-removed-screen. 
#2134 sets mounting …
> refact(iOS, Fabric): take snapshot in `unmountChildComponent:index:`

- apps/src/tests/Test556.tsx
- ios/RNSScreen.mm
- ios/RNSScreenStackHeaderConfig.mm
This PR intents to fix flickering custom header items when going to a previous screen on `fabric` architecture.
The items are unmounted before the transition happens when `POP` action is dispatched on navigation from JS causing the items to vanish for a moment.
The adopted solution uses snapshots of the custom items to be used until the transition's done.
Fixes #2243.
- added snapshots of the custom header items
- modified `Test556` for repro
https://github.com/user-attachments/assets/9da060ed-b65e-4b32-9ab1-debfc2bfd02d
https://github.com/user-attachments/assets/0413fab0-05f6-4e55-adab-f283e01bc551
- Use `Test556` repro
> fix(iOS): flickering custom header items

- apps/src/tests/Test2232.tsx
- apps/src/tests/index.ts
- ios/RNSScreenStackHeaderSubview.mm
This PR fixes #2232 by disabling view recycling in `RNSScreenStackHeaderSubview` view component, as no better solution was found.
The following sequence leads to the bug:
1. User clicks back button
2. The header subviews are properly removed and put in recycle pool in the same order they were mounted (recycle pool is a stack).
3. User pushes again just-popped-screen.
4. React Native reuses view from recycle pool, but `headerCenter` is to be mounted first, so RN reuses the view that was previously `headerRight` (because it is on top of the recycle pool stack).
Similarly the second view in recycle pool, which was previously `headerCenter` is now repurposed as `headerRight`.
5. RN sets correct frames for both subviews.
6. System sets wrong frame for the new `headerCenter` due to layout …
> fix(iOS, Fabric): wrong headerCenter layout after native dismissal

- ios/RNSScreenStackHeaderConfig.mm
When using a header left view and then removing it the default back button doesn't reappear on new arch. This is because we do not call `updateViewControllerIfNeeded` when removing views.
Call `updateViewControllerIfNeeded` in `unmountChildComponentView`.
In the FabricExample HeaderOptions example:
- Open Header item setting
- Choose left
- Choose right
- See the back button is gone.
When toggling state the default back button doesn't reappear.
> fix(iOS): update HeaderConfig view controller after unmounting subviews

- Example/metro.config.js
- TVOSExample/metro.config.js
This PR removes duplicated `react-native-reanimated` modules from metro config files.
> fix: removed duplicated modules from metro config

- src/components/ScreenStack.tsx
PR fixing animations on Fabric. 
The problem started in RN `0.74`, from which suspending the component triggers its `useLayoutEffect`. It has the consequences in `Animated` since detaching the native node happens then: https://github.com/facebook/react-native/blob/a5b84b925891fa509bec2e5ee5988bcb0326e198/packages/react-native/Libraries/Animated/useAnimatedProps.js#L221-L238. 
Check `Test887.tsx` to see that on fabric, when going forward or back, without this change the screen below is not animating.
> fix(Fabric): not working animations on second-top screen

- README.md
Update readme with supported react-native versions since 3.33.0 version of this library.
* Paper: support is declared for 0.72.0+
* Fabric: support is declared for 0.75.0+
N/A
> chore: update readme with supported RN versions since 3.33.0

- FabricExample/android/app/src/main/java/com/fabricexample/MainApplication.kt
- FabricExample/android/settings.gradle
- android/src/main/java/com/swmansion/rnscreens/utils/ScreenDummyLayoutHelper.kt
When running on Fabric + "bridgefull" combination, react packages are initialised very early in application lifetime (much earlier than in Fabric + bridgeless), when there is no activity injected to `ReactContext` yet. Thus when creating packages they do not have access to the activity and we relied on this access up to this moment to setup `ScreenDummyLayoutHelper` object, throwing exception if activity was not available. 
This diff delays initialisation of the dummy layout in case there is no access to activity when creating the object up to the point of invocation of `onHostResume` callbacks of `ReactContext` (this is the very moment activity is injected into the context), avoiding the crash. There is also fallback mechanism added in `computeDummyLayout` method, so that when accessed …
> fix(Android,Fabric,bridge-mode): patch crash with context detached from activity

- android/src/main/java/com/swmansion/rnscreens/utils/ScreenDummyLayoutHelper.kt
Due to missing `DoNotStrip` annotations proguard could treat the class & methods as unused (as reported in #2286)
and remove them completely. 
Possibly fixes #2286.
Annotate `ScreenDummyLayoutHelper` class & all method accessed via JNI.
Haven't triggerred the error localy, relying on report in #2286
> fix(Android,Fabric): add missing `DoNotStrip` annotation to JNI-accessed methods

- android/src/main/java/com/swmansion/rnscreens/utils/ScreenDummyLayoutHelper.kt
There was a crash on Android + Fabric + bridgeless:
1. trigger a redbox by triggering some JS error (e.g. call a method that does not exist),
2. fast refresh react-native,
3. see the crash in `onHostResume`.
The application crashed because we had a check for not null activity in reactContext. 
However after such reload ReactContext is recreated with null activity!!!.
In such case, when we don't have access to the activity, we're currently unable to create the dummy layout,
so the best we can do is not fail. The fix for jumping layout won't work, however.
This PR also adds synchornization on `synchornied` block in `maybeInitDummyLayoutWithHeaderMethod`, which should prevent
a possible data race, where both threads could try to create dummy layout simmultaneously. 
* Do not fail in …
> fix(Android,Fabric,bridgeless): crash on RN hot reload in dev mode when redbox in presentation

- .github/workflows/docs-check.yml
This PR adds additional workflow to publish landing page on GitHub pages whenever there's a change on main inside the `docs` directory.
- Added workflow for publishing landing page
- Added .nojekyll file
> docs: Add workflow to publish GitHub pages

- docs/src/pages/index.js
So previously, when there was a production build, screens from screen sequence in hero were wrongly moving into incorrect div. I've wrapped whole sequence into an additional div, so to disallow screens from moving there (somehow it fixes this issue).
- Wrapped page with additional divs
> docs: Fix layout of screen sequence animation

- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt
This PR removes a comment related to `FabricViewStateManager` that is unnecessary since it was replaced with `StateWrapper` by https://github.com/software-mansion/react-native-screens/pull/2218/commits/536b096bc3254a85cee9ff765034f5a0953fa3cc.
- removed comment
> chore(Android): removed redundant FabricViewStateManager comment

- common/cpp/react/renderer/components/rnscreens/RNSScreenComponentDescriptor.h
In the newest version of screens, there's a bug where compiler can't find RectUtil.h file from `utils/RectFile.h` during the compile phase of RNSScreenComponentDescriptor file.
This PR fixes this by changing the path of RectUtil.h file to <react/renderer/components/rnscreens/util/RectFile.h> file.
Fixes #2306.
- Changed import of RectUtil.h file in RNSScreenComponentDescriptor.h file
- Download reproducer from https://github.com/jankosecki/react-native-upgrade-tester/tree/rn-0.75
- Delete patches/react-native-screens+3.34.0.patch
- Clean up node_modules in case patch already applied
- Run yarn setup (it invokes "pod-install": "(cd ./ios ; RCT_NEW_ARCH_ENABLED=1 USE_FRAMEWORKS=static bundle exec pod install --repo-update)" which enables new architecture)
- Open XCode to set up development …
> fix(iOS): Change import of RectUtil.h file to react/renderer/components

- android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt
I have next navigator structure:
- JS
- native-stack
`native-stack` navigator customizes options as:
```ts
{
headerShown: false,
statusBarTranslucent: true,
navigationBarColor: "#FFFFFF",
navigationBarTranslucent: true,
},
```
When I go to `native-stack` - everything works well: the nav bar changes color. However, when I go back, then I'm getting a gray space in the bottom of my screen.
It happens because we disable mode `edge-to-edge` by calling `WindowCompat.setDecorFitsSystemWindows(window, true)` (the gray space appears because before we were already in edge-to-edge mode, because I had `KeyboardProvider` mounted in `App.tsx`).
So to fix this problem I decided explicitly check for boolean value for `navigationBarTranslucent` and set `decorFitsSystemWindows` only when we have an actual …
> fix: do not force set `translucent` nav bar (until it's explicitly specified)

- android/src/main/java/com/swmansion/rnscreens/Screen.kt
Fixes #2329
- Changes how we check if the child is a CircleImageView to be minification safe
Build `[this](https://github.com/BenIrving/refreshcontrolrepro/tree/main)` repro using this changeset, observe no crash when navigating between screens.
You can also check `Test640.tsx` test by going into the second screen (by button), then try to manually refresh list by swiping down (until the refresh control will show). During the refresh, try to go back to the first screen - application shouldn't crash.
> fix(Android): getChildDrawingOrder when using refreshcontrol

- docs/src/components/Testimonials/TestimonialList/index.tsx
- docs/src/pages/index.js
This PR adds gathered Testimonials to Screens landing page
> docs: Add Testimonials

- android/src/main/java/com/swmansion/rnscreens/CustomToolbar.kt
- apps/src/tests/Test2332.tsx
- apps/src/tests/index.ts
On Android API 29, while using `windowSoftInputMode` with `adjustPan` option, requestLayout is not being called while subviews are being added. That's because while ScreenStackHeaderConfig adds view to the toolbar, onMeasure is being called and even if we're calling `requestLayout` on parent, Android is returning from requesting the layout, as there's somehow ongoing layout. This is not the case for Android API 30 and higher.
The solution is to request another layout via ReactChoreographer (same as in ScreenContainer) to call our own layout callback on the next frame.
- Request layout via ReactChoreographer on `requestLayout` call in CustomToolbar class
<details><summary>BEFORE</summary>
</details>
<details><summary>AFTER</summary>
</details>
Use `Test2332.tsx` test case to check whether …
> fix(Android): Request layout manually for CustomToolbar below Android API 29

- apps/src/tests/TestModalNavigation.tsx
- apps/src/tests/index.ts
- ios/RNSScreenStack.mm
When 3 screens with a ‘modal’ presentation mode are stacked, navigating to a screen outside of the current stack is not functioning correctly.
Removed dismissing logic for `lastModalVc`.
https://github.com/user-attachments/assets/d4991253-52f1-4f35-8698-242d98b218d1
https://github.com/user-attachments/assets/571ebd45-7319-4225-ab5b-4f68027f4f09
`TestModalNavigation` was added to tests.
> fix(iOS): modal not presenting when deep in stack

- android/build.gradle
This PR is a potential fix for [#2295](https://github.com/software-mansion/react-native-screens/issues/2295). Following suggestions in [PR#2251](https://github.com/software-mansion/react-native-screens/pull/2251#issuecomment-2236771857)  and Android Gradle Plugin version 7.0.0 changes: `minSdkVersion` was renamed to `minSdk`, `targetSdkVersion` was renamed to `targetSdk`,  `compileSdkVersion` was renamed to `compileSdk`, this PR ensures compatibility with react native integrated with newest Android projects.  
Fixes #2295
In `adroid/build.gradle` file to get value for `minSdkVersion` in `defaultConfig` it will look for `minSdkVersion` in rootProject then look for `minSdk` and then fallback to default. Previously it looked for `minSdkVersion` and fallback if not found. 
Similar logic for …
> fix(Android): minSdkVersion fallback to default 21 but RN 0.74 require minSdkVersion 23

- src/TransitionProgressContext.tsx
- src/components/Screen.tsx
- src/components/Screen.web.tsx
- src/components/ScreenContainer.tsx
- src/components/ScreenStack.tsx
- src/components/ScreenStackHeaderConfig.tsx
- src/components/SearchBar.tsx
- src/core.ts
- src/fabric/FullWindowOverlayNativeComponent.ts
- src/fabric/ModalScreenNativeComponent.ts
- src/fabric/NativeScreensModule.ts
- src/fabric/ScreenContainerNativeComponent.ts
- src/fabric/ScreenNativeComponent.ts
- src/fabric/ScreenNavigationContainerNativeComponent.ts
- src/fabric/ScreenStackHeaderConfigNativeComponent.ts
- src/fabric/ScreenStackHeaderSubviewNativeComponent.ts
- src/fabric/ScreenStackNativeComponent.ts
- src/fabric/SearchBarNativeComponent.ts
- src/native-stack/contexts/GHContext.tsx
Add basic support for React Server Components support.
Related PRs for more context:
- https://github.com/necolas/react-native-web/pull/2678
- https://github.com/th3rdwave/react-native-safe-area-context/pull/502
- https://github.com/software-mansion/react-native-svg/pull/2287
- Added basic React Server Component support
- It's kinda hard to test this E2E. I wrote a small jest runner in jest-expo which executes in RSC mode, but it requires React 19 to work. Here's where I tested this patch https://github.com/expo/expo/pull/29404
- It will likely break between now and the full release, but this should at least reduce the number of patches required to work on Expo Router support.
- There's pretty good compilation on web:
```
2:I["../../node_modules/react-native-web/dist/exports/View/index.js" …
```
> feat: add basic React Server Component support

- android/build.gradle
Based on: https://github.com/software-mansion/react-native-screens/pull/2337 by @morganick.
Please see the original PR and its description for details.
See: https://github.com/software-mansion/react-native-screens/pull/2337#pullrequestreview-2328416182
for discussion why new PR has been created.
- **Using node resolver to find react native package for better monorepo support**
- **Using rootDir instead of projectDir**
- **Change the order of path lookup**
I've tested it using our both example apps and additionally I've created fresh RN app
and tested the Android build there.
> feat: add monorepo support for Android builds

- FabricExample/Gemfile.lock
- FabricExample/yarn.lock
- docs/yarn.lock
Aggregating dependabot updates
* #2321
* #2322
* #2323
> chore(deps): aggregate updates from dependabot

- apps/src/tests/Test2232.tsx
- src/components/Screen.tsx
Together with @kkafar we noticed that when switching back between BottomTabsView (A -> B -> A) , React is calling removeScreenAt and addScreen for tab we are leaving - in the same transaction! Because of that and asynchronous nature of react-native-screens, error described in #2345 exist. We also noticed that this weir behaviour is related to setting ZIndex in InnerScreen.
Fixes #2345
Test 2232 was failing due to change in headerBackTitleVisible property.
> [!Caution]
@kkafar:
Note that this change might be potentially breaking since we're effectively removing possibility of managing `Screen` components through "z indices", breaking public API. 
@kkafar:
The error mechanism is as follows:
1. `zIndex` being set causes RN diffing mechanism to include two mutations on the same view in the …
> fix!: always set Zindex to undefined for InnerScreen

- guides/GUIDE_FOR_LIBRARY_AUTHORS.md
- native-stack/README.md
- src/components/Screen.tsx
- src/native-stack/types.tsx
- src/native-stack/views/NativeStackView.tsx
- src/types.tsx
This PR intends to add support for previously removed `sheetAllowedDetents` and `sheetLargestUndimmedDetent` props values: `medium`, `large` and `all`. 
With addition of custom detents for iOS I've changed the API of NativeScreen component to receive `number[]` as the detent list and removed the old options. This removal was unnecessary. I've restored these options on the `Screen` component abstraction layer, where old options are translated to the new API w/o need for additional support in downstream packages such as react-navigation.
Corresponding PR in `react-navigation`:
* https://github.com/react-navigation/react-navigation/pull/12032
* updated the types,
* added "translation layer" in InnerScreen.
Test1649 is great for testing all sheet related props.
> feat: add compat mode for previously removed formSheet prop values

- apps/src/tests/Test1649/state.tsx
- guides/GUIDE_FOR_LIBRARY_AUTHORS.md
- native-stack/README.md
- src/components/Screen.tsx
- src/index.tsx
- src/native-stack/types.tsx
- src/native-stack/views/NativeStackView.tsx
- src/types.tsx
I'm exposing two new options for `sheetLargestUndimmedDetent` prop:
* `none` - denoting that dimming view will be always present,
* `largest` - denoting that dimming view will never be present.
Previously to achieve the effect of `none` you had to either rely on default or pass `-1` raw value.
Similarly achieving the effect of `largest` required user to set a numeric value and update it everytime new detent was added / removed. 
> [!note]
~~As I wrote this description, new idea popped out - instead of exposing numeric constant just add some string options, as with  `sheetAllowedDetents` (it is an array or some predefined string constants).
> What would be the API though? `sheetLargestUndimmedDetent: 'none'`? What's the wording here?~~
>
> *Done! ^^^*
`react-navigation` PR:
* …
> feat: expose `none` & `largest` values for `sheetLargestUndimmedDetent` prop

- apps/src/tests/Test2002.tsx
- ios/RNSScreen.h
- ios/RNSScreen.mm
- native-stack/README.md
- src/fabric/ModalScreenNativeComponent.ts
This PR adds `sheetInitialDetent` support to iOS and fixes detents logic on iOS < 16.
This functionality depends on changes made in this PR: https://github.com/react-navigation/react-navigation/pull/12032
- supporting `sheetInitialDetent` on iOS
- modified `Test2002.tsx` repro
- updated README definition to match types
- fixed `sheetAllowedDetents` on iOS < 16
- Use `Test2002.tsx` repro
> feat(iOS): sheetInitialDetent support

- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt
- apps/src/screens/Animations.tsx
- apps/src/screens/Events.tsx
- guides/GUIDE_FOR_LIBRARY_AUTHORS.md
- ios/RNSConvert.mm
- ios/RNSScreen.mm
- native-stack/README.md
- src/fabric/ScreenNativeComponent.ts
- src/native-stack/types.tsx
- src/types.tsx
- windows/RNScreens/Screen.h
Removes stackAnimation "ios" option in v4 after making it deprecated in 3.x.
> refactor!: remove deprecated ios stack animation

- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt
Recently, when adding formSheets I've also merged some code for future modals implementation.
When detaching the yet-unused code for modals from being used I've forgotten about one code place,
causing the header to not be created.
`modal` presentation is rather not widely used on Android, because it has no real differences from `push`,
however I'm restoring the old behavior for the sake of backward compatibility.
Kudos to @alduzy for noticing the issue.
* Fixed the condition that prevents the header from being created on Android, right now header 
is not created only for `formSheet` stack presentation.
`Test1649` - set 'modal' stack presentation to any screen and do not disable the header. See that it now works.
> fix: bring back headers when using "modal" presentation on Android

- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt
I haven't investigated it carefully, but there were case when updating `sheetCornerRadius` the appearance
model has not been built yet leading to a crash when casting to a non-null type.
Additionally, this PR prevents calls to `onSheetCornerRadiusUpdate` when not in `formSheet` presentation
or not in native stack.
* Prevent calls to `onSheetCornerRadiusUpdate` when not in `formSheet` presentation.
* Check for nullish view background before attempt to set the corner radius.
* Update the corner radius after all updates are applied, so that the `stackPresentation` has change of being updated.
`Test1649`. Try setting the corner radius now, should work properly.
> fix: prevent crash when there is no appearance model built

- android/src/main/java/com/swmansion/rnscreens/Screen.kt
Before this PR, when updating corner size after initial render different unit (pixel) has been used opposed to
`dp` used during initial render. This PR align this behaviour so that `dp` is always used.
* Calculate appropriate value in `Screen.onSheetDetentChange` function
`Test1649`
> fix: align units of sheet corner radius in different callsites

- src/components/Screen.tsx
- src/native-stack/types.tsx
- src/native-stack/views/NativeStackView.tsx
- src/types.tsx
This PR aims to improve prop naming by following renames:
* `sheetInitialDetent` -> `sheetInitialDetentIndex`,
* `sheetLargestUndimmedDetent` -> `sheetLargestUndimmedDetentIndex`
In case of `sheetInitialDetentIndex` prop additional value is handled: `last`, which indicates that the
sheet should be opened initially at largest detent.
In case of `sheetLargestUndimmedDetent` the `largest` variant has been changed to `last`, so there is no discrepancy between these two props.
Additionally, error handling has been improved for both of these props. Now if they are out of bounds, in production environment default value is used,
in developement mode an descriptive error is thrown.
^^^
Test1649
> refactor!: add "index" suffix to selected sheet props & add better error handling

- src/components/Screen.tsx
Previous code reduced detent array to three values on Android only in dev mode - this is undesired.
We want to always do it.
Moved the slicing operation out of check for dev mode.
`Test1649`, pass more than 3 values on Android, see that it works.
> fix: check for surplus values in sheet detents array not only in dev mode

- android/src/main/java/com/swmansion/rnscreens/Screen.kt
It turns out, that this check: https://github.com/software-mansion/react-native-screens/pull/2375/commits/b2dab7859c32a5848b40369c79c95b1e5f2bd77e was necessary,
and I forgot about it while applying the code review.
Current code will crash if `background != null && !(background is MaterialShapeDrawable)`, so e.g. when `background is ColorDrawable`.
We don't wanna fail in this case.
Allowed the cast to fail instead of throwing exception, when casting background to `MaterialShapeDrawable`.
One thing that concerns me 
`Test1649`
> fix(Android): do not crash in case background can not be casted to MaterialShapeDrawable

- apps/src/tests/Test2395.tsx
- apps/src/tests/index.ts
- src/components/ScreenStackHeaderConfig.tsx
This PR fixes headerConfig's incorrect layout with custom subviews after recent changes in https://github.com/software-mansion/react-native-screens/pull/2325.
> [!note]
@kkafar: 
Previously, before #2325, all children of the headerConfig component have been positioned absolutely, thus the headerConfig was always of height 0, not impacting layout of other components. After #2325, headerConfig's children are positioned using flexbox. This implies that it has no longer height of 0, thus it impacts the layout of other other elements, in particular `ScreenContentWrapper`, which is offset by the height of the highest header config subview.
>
> The initial idea to solve this was to set `height: 0; overflow: visible`, however, for some yet unknown reason the subviews become invisible with such …
> fix: `HeaderConfig` impacts layout of `Screen`'s contents

- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt
Fixes invalid behaviour of `fitToContents` sheet detent on Fabric. 
The erroneous behaviour has been caused by different order of updates on Fabric relative to Paper.
On Fabric `onCreateView` (the place where bottom sheet behaviour is created) is called much later,
Because of this the layoutCallback from `ScreenContentWrapper` fails to set proper sheet height,
as the `sheetBehaviour` is still `null`.
`Screen` now keeps weak reference to `ScreenContentWrapper` and queries it when needed during behaviour configuration.
`Test1649`, chante `sheetInitialDetents` to `fitToContents` and see that it now works on Fabric.
- [-] Ensured that CI passes
> fix(Android,Fabric): invalid behaviour of `fitToContents` sheet detent

- apps/src/tests/TestMemoryLeak.tsx
- apps/src/tests/index.ts
- ios/RNSScreen.h
- ios/RNSScreen.mm
- ios/RNSScreenStack.mm
On new architecture there is no callback that notifies components that they're deleted
and won't be used anymore. `RCTComponentViewProtocol#prepareForRecycle` was supposed to fulfill
this role, however after it became possible to disable view recycling for given class of components,
it is not always called. 
In our case, we need such callback in `Screen` to break the retain (strong reference) cycle between `ScreenView` and its `Screen` (controller),
otherwise we leak the `RNSScreenView` and `RNSScreen` instances.
Overrode the `mountingTransactionWillMount:withSurfaceTelemetry:` in `RNSScreenStack`, where screens that are meant to receive
`Delete` mutation are retained, and later in `mountingTransactionDidMount:withSurfaceTelemetry:` we dispatch a series of `invalidate` calls & release the …
> fix(iOS,Fabric): prevent memory leak by calling `invalidate` on deleted screens

- android/src/main/java/com/swmansion/rnscreens/ext/ViewExt.kt
- apps/src/tests/Test2282.tsx
This PR handles yet another case for going back on fabric. In the previous one (https://github.com/software-mansion/react-native-screens/pull/2383) I omitted a case where a horizontal list is simply rendered w/o being nested in any other list!
Fixes #2341 
- updated `Test2292.tsx` repro
- handle `parentView is ReactHorizontalScrollView`
- use `Test2282.tsx` repro
> fix(Android): going back on fabric with horizontal list crash

- ios/RNSEnums.h
- ios/RNSScreen.mm
We did not set default value of `activityState` on iOS. It was set to `0` by default `int` initializer.
In `Screen` component native spec we set it to `-1`, however this had no impact, because the value setter
`setActivityStateOrNil:` filtered out the `-1` value.
TODO:
1. [x] Verify that change in default value do not break any other navigator!
^ Looks like this will work, because navigators such as bottom tabs always set the activity state explicitly. 
This is a problem, because now, after adding preload support #2389 we filter out screens with `activityState == 0` in native stack.
Therefore, we now unintentionally force our API user to always set desired `activityState`.
Set `activityState` to `-1` by default on native side.
Just render screen inside native-stack w/o `activityState` …
> fix(iOS): do not force API user to set `activityState`

- src/index.tsx
- src/utils.ts
This PR introduces new `compatiblityFlags` object to the library public API. 
It is meant as a source of truth for the library consumers (especially `react-navigation`) to allow them to adjust to breaking changes
done in this library.
I've decided to go with single object with fields instead of individual constants, because it makes it easier for handling,
we don't have to change public exports every time we add something, it makes it easier to add/remove a flag.
1. Created & exposed `compatiblityFlags` object,
2. added `usesHeaderFlexboxImplementation`,
2. moved old flags into the object.
N/A
> feat!: expose library `compatibilityFlags` with new flag regarding header implementation

- src/components/Screen.tsx
- src/components/Screen.web.tsx
- src/components/ScreenContainer.tsx
- src/components/ScreenStack.tsx
- src/components/ScreenStackHeaderConfig.tsx
- src/components/ScreenStackHeaderConfig.web.tsx
- src/components/SearchBar.tsx
- src/gesture-handler/GestureDetectorProvider.tsx
- src/native-stack/types.tsx
- src/native-stack/utils/getDefaultHeaderHeight.tsx
- src/native-stack/views/FooterComponent.tsx
- src/native-stack/views/HeaderConfig.tsx
- src/native-stack/views/NativeStackView.tsx
- src/reanimated/ReanimatedNativeStackScreen.tsx
- src/reanimated/ReanimatedScreen.tsx
- src/reanimated/ReanimatedScreenProvider.tsx
This PR fixes `require cycles` warning caused by importing from `react-native-screens` in a `react-native-screens` module by changing the imports to relative.
Fixes #2408  .
- changed imports to relative
> fix: prevent Require cycles warning

- src/core.ts
- src/index.tsx
- src/utils.ts
This PR removes `shouldUseActivityState` flag from public API (and in general).
The flag was initially introduced in #624, as a mean for downstream library developers
to differentiate between different screen versions. This was introduced over 4 years ago 
and currently does not serve any role in `react-navigation` implementation. 
* Removed `shouldUseActivityState` flag from public API,
* added comment for `compatibilityFlags` object.
N/A
> feat!: remove `shouldUseActivityState` flag

- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt
- android/src/main/java/com/swmansion/rnscreens/bottomsheet/BottomSheetBehaviorExt.kt
- android/src/main/java/com/swmansion/rnscreens/bottomsheet/SheetUtils.kt
I plant to extract most of the form sheet API related code out of `ScreenStackFragment`, 
so that it is not polluted that much and more readable. Having experienced the #2045, where
big changes were rolled out at once, now I want to do it in couple of separate PRs.
This one simplifies sheet behaviour configuration logic in ScreenStackFragment by implementing 
series of helper extension functions on BottomSheetBehavior.
Test1649
> refactor(Android): cleanup sheet behavior configuration

- src/components/Screen.tsx
- src/components/ScreenContainer.tsx
- src/components/ScreenContainer.web.tsx
- src/components/ScreenContentWrapper.tsx
- src/components/ScreenContentWrapper.web.tsx
- src/components/ScreenFooter.tsx
- src/components/ScreenFooter.web.tsx
- src/components/ScreenStack.web.tsx
- src/components/SearchBar.tsx
- src/components/SearchBar.web.tsx
- src/index.tsx
This PR removes native components from our API. The motivation is that those shouldn't be available directly, only through our interface.
> feat!: remove native components from public API

- apps/src/tests/Test1096.tsx
- src/components/FullWindowOverlay.tsx
This PR intents to fix `FullWindowOverlay`s height issue.
The component is given wrong frame size during layout because of it's placement in the react tree. Although in the iOS view hierarchy it is displayed independently its height is still reduced by the height of the header.
Correct frame can be achieved by utilising `useWindowDimensions` hook and forcing correct width and height on the JS side.
Fixes #1247 
- modified `Test1096` repro 
- use `Test1096` repro
> fix(iOS): FullWindowOverlay layout height

- src/components/ScreenStackHeaderConfig.tsx
This PR changes  `ScreenStackHeaderConfig` into a [forwardRef](@alduzy/reanimated-patch).
This is needed if you want to attach `ref` to it, which **react-native-reanimated** needs to do [here](https://github.com/software-mansion/react-native-reanimated/blob/1d417a5c711d60822d25bd8b823f1f5968214bde/apps/common-app/src/examples/ScreenStackHeaderConfigBackgroundColorExample.tsx#L24) in order to migrate to v4, since the header config is now a function component and cannot be used directly anymore.
Without this change the app crashes with `Cannot read property 'getScrollableNode' of null`.
Related PR: https://github.com/software-mansion/react-native-reanimated/pull/6622
> fix: header config missing ref

- docs/docusaurus.config.js
This PR introduces persistance between system color theme and user selected color theme.
Before:
https://github.com/user-attachments/assets/59db2476-31a0-4a86-b04f-91239b4af51e
After:
https://github.com/user-attachments/assets/21a65e4b-826d-4c70-9fdb-8498e891fb75
> docs: Manage system color scheme changes

- ios/RNSScreen.mm
This PR fixes iOS build after recent cherry-picks. It removes the _sheetsScrollView leftover reference.
> fix(iOS): remove leftover _sheetsScrollView reference after cherry-picking from main

- src/components/ScreenStack.tsx
- src/fabric/ScreenStackNativeComponent.ts
Continuation of https://github.com/software-mansion/react-native-screens/pull/2423. Separate public `ScreenStackProps` and `NativeProps` by not casting NativeComponent as `React.ComponentType<ScreenStackProps> `.
> refactor: Separate API props and NativeProps for ScreenStack 

- android/src/main/java/com/swmansion/rnscreens/CustomToolbar.kt
- apps/src/tests/Test2332.tsx
This PR intents to fix `headerTitleAlign: 'center'` breaking layout on android API <= 29.
I found changes added in https://github.com/software-mansion/react-native-screens/pull/2332, which fixed a related toolbar problem on android API <= 29, affect the correct layout of the centered title.
The `EXACTLY` [MeasureSpec](https://developer.android.com/reference/android/view/View.MeasureSpec) causes the title not to obtain as much space as it needs. Fortunately changing the spec to `AT_MOST` in the custom `layoutCallback` fixes the issue without introducing regression.
I also included a check for the current `softInputMode` to abandon the action if it is not set to `adjustPan`.
Fixes #2435 
- updated `Test2332.tsx` repro
- changed measureSpec used in `layoutCallback`
- added `softInputMode` …
> fix(Android): center headerTitleAlign below Android API 29

- guides/GUIDE_FOR_LIBRARY_AUTHORS.md
- src/components/DebugContainer.tsx
- src/components/DebugContainer.web.tsx
- src/components/ScreenStackItem.tsx
- src/index.tsx
Currently there is a lot of logic to make `Screens` work properly in native-stack, including:
- Making sure screens is enabled and mark it for native-stack
- Making sure screens knows that it contains a large title
- Rendering a `DebugContainer` for `LogBox`
- Making sure the `DebugContainer` contains appropriate logic and wrapper
- Rendering a nested stack to be able to show header in modals
This diff consolidates this logic to a new component `ScreenStackItem`. This makes it possible to move the above logic to the `react-native-screens` package by moving this component. Moving the logic will make it easier to fix bugs in screens.
Extracted from https://github.com/react-navigation/react-navigation/commit/fbc8635d22acadd2487f6bfc94338cbdac0d5a60
> feat: add a ScreenStackItem component

- apps/src/tests/Test2282.tsx
- src/index.tsx
This PR intents to fix current screen going blank on Android when returning to the previous one. The issue has been already fixed by https://github.com/software-mansion/react-native-screens/pull/2134, but re-appeared recently. After a quick bisect it turned out that https://github.com/software-mansion/react-native-screens/pull/2412 caused the regression. Bringing back the removed `NativeScreensModule` export fixes the issue.
Fixes #1685 
- added missing export
- modified `Test2282.tsx` repro
https://github.com/user-attachments/assets/39bf6c66-39d2-4dfd-abc8-ee1c690417a4
https://github.com/user-attachments/assets/003446b2-c976-4cdb-8ab4-348dd619ba79
- use `Test2282.tsx` repro
> fix(Android): screen goes blank when going back on fabric

- src/components/DebugContainer.tsx
- src/components/DebugContainer.web.tsx
- src/components/ScreenStackItem.tsx
- src/index.tsx
We want to ensure that the tubomodule spec gets loaded & executed
and at the same time we don't want it exported. 
This syntax should ensure it! [MDN docs link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#import_a_module_for_its_side_effects_only)
Change export to side effect import!
Run FabricExample on Android & see that the underneath screen does not disappear when popping a screen.
> refactor: use side-effect import declaration to ensure TurboModule gets loaded

- ios/RNSConvert.mm
Fix react-native-screens module build failure for case sensitive file systems.
Fixes #2472.
> fix(iOS): RCTAssert.h file not found for case sensitive file system (#2472)

- src/components/Screen.tsx
- src/components/Screen.web.tsx
- src/components/ScreenContainer.tsx
- src/components/ScreenStack.tsx
- src/components/ScreenStackHeaderConfig.tsx
- src/components/ScreenStackHeaderConfig.web.tsx
- src/components/SearchBar.tsx
- src/gesture-handler/GestureDetectorProvider.tsx
- src/native-stack/types.tsx
- src/native-stack/utils/getDefaultHeaderHeight.tsx
- src/native-stack/views/HeaderConfig.tsx
- src/native-stack/views/NativeStackView.tsx
- src/reanimated/ReanimatedNativeStackScreen.tsx
- src/reanimated/ReanimatedScreen.tsx
- src/reanimated/ReanimatedScreenProvider.tsx
This is a #2410 cherry-pick from main. This PR aims to bring the fix to v3 as well.
This PR fixes `require cycles` warning caused by importing from `react-native-screens` in a `react-native-screens` module by changing the imports to relative. Additionally it fixes an [issue](https://github.com/software-mansion/react-native-screens/issues/2302) with react-compiler in expo projects.
Fixes #2408  #2302.
> fix: prevent Require cycles warning cherry-pick from main

- README.md
This PR updates the compatibility table in `README` with support for React Native 0.76.
I updated the table and added a brief description for Paper architecture since it's not the default for RN 0.76+.
I ran the following tests in order to see if the compatibility changed since the last check.
- RN `0.72` builds and run with screens `3.35.0` ✅
- iOS ✅
- Android ✅
- RN `0.76` builds and run with screens `3.33.0` ✅
- iOS ✅
- Android ✅
- RN `0.75` builds and run with screens `3.35.0` ✅
- iOS ✅
- Android ✅
- RN `0.76` builds and run with screens `3.33.0` ❌ 
- iOS ✅
- Android ❌
> chore: compatibility table README update

- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerDelegate.java
- guides/GUIDE_FOR_LIBRARY_AUTHORS.md
- ios/RNSScreen.mm
- native-stack/README.md
- src/fabric/ModalScreenNativeComponent.ts
- src/fabric/ScreenNativeComponent.ts
- src/native-stack/types.tsx
- src/native-stack/views/NativeStackView.tsx
- src/types.tsx
This PR changes default value for `fullScreenSwipeShadowEnabled` prop to `true` - meaning that the shadow will be present by default
in `simple_push` animation on iOS (this is the platform default).
> [!important]
> When changing this value I've noticed that the `fullScreenSwipeShadowEnabled` does something different
> than it suggests in type documentation & our GUIDE_FOR_LIBRARY_AUTHORS. Namely, it does effect `simple_push` animation
> in every scenario, not only in full screen swipe gesture interactive transition. I think we should change the name
> of the prop eventually. 
Updated all the docs & code.
I've played around with `Test1072`. Just set stack animation to simple push.
> feat(iOS)!: change default of `fullScreenSwipeShadowEnabled` to true

- README.md
Because `react-native-screens/native-stack` isn't moved to `@react-navigation/native` 😄 I've changed the caution about moving the dependency into the correct one. Also, I've redacted the sentence, so for me it looks better now.
- Fixed `@react-navigation/native-stack` to `@react-navigation/native` in README.
- Redacted caution
> chore(README): Redact caution of migrating JS API of native stack

- android/src/main/cpp/jni-adapter.cpp
Removes a dangling global reference to the `ScreenModule`.
When the application reloads, `nativeInstall` is called, which overwrites the reference to `globalThis` without deleting it. This PR deletes the reference before creating a new one.
I've tested it in a new project created using expo (SDK 52) and with fabric turn on.
> fix: Remove dangling global reference to `ScreenModule`

- apps/src/tests/TestModalNavigation.tsx
- ios/RNSScreenStack.mm
We recently fixed left-out modals dismissal when reloading react-native. For some reason 
calling in `dismissViewControllerAnimated:completion:` on **nested** UINavigationController
(the one responsible for displaying the navigation bar in modal, not the one reponsible for presentation)
during invalidation messes up with the animation. 
I'm not really sure why this is the case. Earlier we were calling dismiss on all presented modals,
but not on UINavigationController itself and it worked like a charm. 
I've found out that simply animating the change solves the situation - we fix the animation and keep nice
modal dismissal on reload.
Fixes #2488
:point_up:
`TestModalNavigation`
> fix(iOS,Paper): fix broken modal go-back animation

- docs/src/components/Hero/ScreenSequence/styles.module.css
Before on 4k monitors it was impossible to click on navbar due to hero svg overlapping with it. In this PR we adjusted styles for this to work.
> docs: Add hero support for 4k monitors

- common/cpp/react/renderer/components/rnscreens/RNSScreenShadowNode.cpp
- ios/RNSConvert.h
- ios/RNSFullWindowOverlay.mm
- ios/RNSScreen.mm
- ios/RNSScreenContainer.mm
- ios/RNSScreenFooter.mm
- ios/RNSScreenStack.mm
- ios/RNSScreenStackHeaderConfig.h
- ios/RNSScreenStackHeaderConfig.mm
- ios/RNSScreenStackHeaderSubview.mm
- ios/utils/RNSDefines.h
Possible build issues.
- **Add default for resizemode conversion**
- **Remove unimplemented and unused method**
CI
> fix(iOS): fix build issues when building with `-Werror -Wreturn-path`

- ios/RNSScreenStackHeaderConfig.mm
> fix(iOS): add missing largeTitleBackgroundColor prop

- ios/RNSConvert.mm
I've recently watched a [talk by Jonathan Müller](https://youtu.be/zGWj7Qo_POY?si=XY-llWKz3esbcGOl) from `CppOnSea`
and it was brought to my attention that there is `using enum` syntax in C++ (since C++20), which we can use
to make our conversion code much more readable.
Refactored RNSConvert.mm
Everything should work as before.
> refactor(iOS): cleanup conversion code

- .github/workflows/ios-e2e-test.yml
- Example/.detoxrc.js
CI started failing literally for no reason with error (when launching individual tests):
`DetoxRuntimeError: Failed to find a device by type = "iPhone 14"`
Sometimes restarting it makes it pass (no changes to code, just restarting CI).
I've also listed available devices on CI with `applesimutils --list` and iPhone 14 is obviously there.
I've changed the testing device to 'iPhone 15 Pro` (available on list ☝🏻) and it seems to be passing consistently, but 🤷🏻‍♂️ 
CI should pass...
> chore(CI): fix iOS e2e tests

- src/components/ScreenFooter.tsx
- src/components/ScreenStackItem.tsx
Associated PR:
* https://github.com/react-navigation/react-navigation/pull/12258
The footer is currently broken, as in the effect of recent refactors it erroneously ended up being rendered as child as `ScreenStackItem`, thus due to internal implementation it is rendered under `ScreenContentWrapper`. However, it has to be rendered as direct child of `Screen` component (the same as `HeaderConfig`). 
Under usual circumstances this would be a breaking change, however the prop is marked as `unstable`, therefore I'm proceeding.
`unstable_sheetFooter` is now rendered by `ScreenStackItem`.
`Test1649`
> fix: make unstable_sheetFooter usable with react-navigation v7

- android/src/main/java/com/swmansion/rnscreens/ScreenFooter.kt
- apps/App.tsx
- apps/src/tests/TestFormSheet.tsx
- apps/src/tests/index.ts
Previous implementation of `sheetTopWhileDragging` relied on linear interpolation.
Due to numeric errors in floating point division sometimes the footer was +- 1 pixel up/down 
from the accurate position, resulting in 1px flickering / "dancing".
This PR changes the way sheet top is computed to making use of the parent screen `top` property,
whenever possible.
- **Add test dedicated to formsheet**
- **"Stabilize" footer**
Added dedicated test `TestFormSheet`.
> fix(Android): prevent sheet footer from flickering on sheet sliding

- ios/RNSScreenStackHeaderConfig.mm
- requires this bug fix https://github.com/software-mansion/react-native-screens/pull/2500
- make it possible to support the stock Apple behavior where the large header is transparent and the collapsed header is blurry with a shadow. This is currently not possible because we inherit the blur effect from the collapsed title, and because there's no way to set the headerLargeTitle blur effect.
With this change, the default iOS behavior can more closely be matched by using the following props:
```js
{
headerLargeTitle: true,
headerTransparent: true,
headerBlurEffect: "systemChromeMaterial",
headerLargeTitleShadowVisible: false,
headerShadowVisible: true,
headerLargeStyle: {
// NEW: Make the large title transparent to match the background.
backgroundColor: "transparent",
},
}
```
Without the …
> feat: add support for transparent large header on iOS

- android/src/main/java/com/swmansion/rnscreens/InsetsObserverProxy.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt
- apps/Example.tsx
- apps/src/tests/TestAndroidTransitions.tsx
- apps/src/tests/index.ts
I've investigated the regression on form sheet keyboard behaviour. It has stopped respecting allowed detents when keyboard was opened.
https://github.com/user-attachments/assets/42d393c8-a50b-40f4-a8cc-41bca122b4aa
I tracked down the regression to #2371. I do not understand the interactions completely, as the regression happens only when `statusBarTranslucent` is explicitly set to `false`. `true` or `undefined` make the formsheet-keyboard interaction work correctly. This is especially baffling that I'm testing this on Fabric, therefore `false` is always provided
What I understand is that *setting insets observer* to `null` in `ScreenWindowTraits.setTranslucent` effectively removes **any** listener currently attached to decor view, thus preventing other functionalities from work (such as …
> fix(Android): fix formSheet-keyboard interaction

- apps/src/screens/StackPresentation.tsx
Fixed #2521
Separated the formsheet and card components and applied correct styles for formsheet.
Just use the `StackPresentation` screen in example app.
> chore: make formsheet work in Example app

- android/src/main/java/com/swmansion/rnscreens/InsetsObserverProxy.kt
- android/src/main/java/com/swmansion/rnscreens/RNScreensPackage.kt
- android/src/main/java/com/swmansion/rnscreens/bottomsheet/DimmingFragment.kt
Activity restarts do not invalidate JVM state entirely (at least it seems so), therefore InsetsObserverProxy
kept being registered on some decorview between activity restarts (context recreations) leading to crash
(we guard against multiple registrations).
Fixes #2519
Possibly fixes #2507
`InsetsOberverProxy` row registers for context lifecycle, when it's destroyed it cleans its state.
Haven't managed to reproduce this myself, but got confirmation in #2507 that this patch works.
> fix(Android): prevent crash with InsetsObserverProxy already registered

- android/src/main/java/com/swmansion/rnscreens/Screen.kt
Attempt to patch changes from https://github.com/software-mansion/react-native-screens/pull/2495. It improved the situation in most of the cases
but caused crashes in cases where we tried to insert subviews into viewgroups that have any kind of assertions on their child count, e.g. `NestedScrollView` or `ViewPager`.
Fixes #2529
Supersedes #2527 
In this PR I do two things:
* apply the workaround only to views that could actually have clipped subviews
* catch any kind of exception thrown on view insertion; if one is thrown we stop to add subviews for given child
Test2282 works in both configurations (complex screen with nested flatlists + my simple reproduction of the issue)
> fix(Android): prevent crash when we can not insert any subviews into child

- src/components/ScreenFooter.web.tsx
Recently `FooterComponent` was introduced for internal reasons, however it hasn't been exported on web
leading to issues.
> [!caution]
> We need to set up CI for web...
Fixes #2534
`FooterComponent` is now exported from `ScreenFooter.web.tsx`
??? We do not have a web example - we need to add it.
> fix(web): reexport missing component

- android/build.gradle
It has been reported that there are project configurations in which "$projectDir/../node_modules/react-native" exists, but node module resolution algorithm
fails to find it. I've reintroduced the aforementioned location.
Our examples should keep working as always ^^
> fix(Android): improve RN detection in build scripts

- apps/src/tests/Test2552.tsx
- apps/src/tests/index.ts
- ios/RNSScreenStackHeaderConfig.mm
- ios/RNSScreenStackHeaderSubview.mm
> [!note]
> This issue seems to concern only old architecture. See below for description of Fabric situation 👇🏻 
This PR aims to fix a bug described below 👇🏻 and at the same time balancing on the thin edge of not introducing regressions regarding: #2316, #2248, #2385. 
See `Test2552`. 
The flow is as follows: 
1. we have tab navigator with nested stack navigators on each tab (A & B),
2. In `useLayoutEffect` we schedule a timer which callback changing the subview elements,
3. before the timer fires we change the tab from A to B,
4. wait few seconds fot timer to fire,
5. go back to A,
6. notice that the subviews are laid out incorrectly (video below 👇🏻)
https://github.com/user-attachments/assets/2bf621a7-efd4-44cf-95e1-45a46e425f07
Basically what happens is we're sending `layoutIfNeeded` to …
> fix(iOS, Paper): fix header layout when updating non focued screen

- ios/RNSScreenStackHeaderConfig.mm
I was just writing #2552 and got confused that the header config subviews are added as subviews to the header config view
in host tree, before they are attached to the navigation bar view hierarchy. This transient state does not make any sense,
and we do not do similar thing on Fabric.
`self.superview` returns now `nil` until the subview is mounted in navigation bar view hierarchy.
Also moved the function to Paper specific section of file, because it is not called on Fabric on any codepath. 
We haven't used this behaviour. There should be no regression in text examples.
> refactor(iOS, Paper): do not add subviews to header config in HostTree

- ios/RNSScreenStack.mm
Noticed a low-hanging opportunity to simplify this method while doing something different.
We already had this loop implemented in helper function so we could use it.
CI should be enough
> refactor(iOS): simplify UINavigationControllerDelegate methods implementation

- apps/src/tests/TestAnimation.tsx
- apps/src/tests/index.ts
- ios/RNSScreenStackAnimator.mm
Fixes #2550
Empirical research shows that UIKit uses `interruptibleAnimatorForTransition:` method on `UIViewAnimatedTransitioning` (our `RNSStackAnimator`)
for navigation item animation. This allowed us customizing navigation item timing curve & animation style, however it has caused unexpected content jumps (see #2550 or video below :point_down:).
> [!important]
> This PR reverts changes to navigation item animation introduced with v4. I guess it could be considered breaking unless it weren't a bit broken => I'm treating this as a necessary fix 
> & will try to bring back "new behaviour" soon, once we figure why `interruptibleAnimatorForTransition:` causes such bugs.
https://github.com/user-attachments/assets/000fa79d-b01a-4261-941b-c5922e0d17f6
After the changes this looks as follows: …
> fix(iOS): restore old header animation to prevent content jump

- guides/CONTRIBUTING.md
- package.json
We recommended to run `yarn prepare` in `react-navigation` submodule, which is not existend (for some time now I believe).
Updated the `yarn submodules` script & fixed the contributing guide.
Clone fresh repo & follow contributing guide - it should work now.
> chore: fix misleading contributing guide

- apps/src/tests/TestModalNavigation.tsx
- ios/RNSScreenStack.mm
Fixes #2525
View hierarchy for modal with header looks kinda like this:
`UITransitionView` -> `Screen` -> `Stack` (`UINavigationController`) -> `Screen` -> content
calling `[_controller dismissViewControllerAnimated:YES completion:nil]` on the `Stack` :point_up:, according to [documentation](https://developer.apple.com/documentation/uikit/uiviewcontroller/dismiss(animated:completion:)?language=objc)
should dismiss the view controller itself and any view controllers presented from that view controller. However in practive it dismisses not only itself and "above" modal, but also a single modal "below". I'm not sure
why it is the case. Removing this line of code introduces a bug: during development, when multiple modals are opened and you reload the react-native, the modals could be left in …
> fix(iOS, Paper): prevent double modal dismissal

- apps/src/tests/TestFreeze.tsx
- src/components/Screen.tsx
- src/components/ScreenStack.tsx
- src/components/ScreenStackItem.tsx
- src/types.tsx
Fixed https://github.com/software-mansion/react-native-screens/issues/2557. We have to take preloaded screens into account when freezing screens. Till now, the assumption was that the newest screens are the ones rendered, right now top children can be the preloaded ones, so we have to filter them from calculating the size of frozen screens. We could also think of freezing the preloaded screens, wdyt about it @satya164 ?
TestFreeze now includes preloading of screens, even more than 1 to see that the current one still gets the updates.
> fix: take preload into account when freezing children

- package.json
Add a newly introduced field `ios.componentProvider` to the `codegen` configuration to create an association map between JS components and their native implementations. 
See more information here: https://github.com/software-mansion/react-native-svg/pull/2572
- added `codegenConfig.ios.componentProvider` field to package.json
```objc
Class<RCTComponentViewProtocol> RCTThirdPartyFabricComponentsProvider(const char *name) {
static std::unordered_map<std::string, Class (*)(void)> sFabricComponentsClassMap = {
// ...
{"RNSFullWindowOverlay", RNSFullWindowOverlayCls}, // 3
{"RNSModalScreen", RNSModalScreenCls}, // 3
{"RNSScreenContainer", RNSScreenContainerCls}, // 3
{"RNSScreenContentWrapper", RNSScreenContentWrapperCls}, // 3
{"RNSScreenFooter", RNSScreenFooterCls}, // 3
{"RNSScreen", …
```
> feat: add codegen `ios.componentProvider` to package.json

- package.json
#2567 introduced `ios.componentProvider` field to package definition - and that's fine, but we're pointing to wrong names there. 
Updated the names to existing symbol names. 
This caused runtime errors when running the app on 0.77. I need this commit for the #2581 (0.77 support)
> fix: point to existing symbol names in `ios.componentProvider`

- android/src/main/java/com/swmansion/rnscreens/RNScreensPackage.kt
This is required for RN 0.77 apparently. TurboReactPackage is deprecated on new arch. No idea why.
I am not sure about backwards compatibility either, sorry.
Feel free to close this PR if this isn't backwards compatible.
> feat: Use `BaseReactPackage` instead of `TurboReactPackage`

- android/build.gradle
Fixes #2463 
I haven't been able to reproduce the issue, however multiple people reported & confirmed it
Thanks @vadzimk for [pointing these out](https://github.com/software-mansion/react-native-screens/issues/2463#issuecomment-2573632504).
When adding support for 0.76.0 we overlooked that we relied on RN library structure (and naming) not only in CMake build but also in Gradle configuration.
I've looked up whether reanimated team did this - and [they did](https://github.com/software-mansion/react-native-reanimated/pull/6499/files#diff-1c0b83a843e69ff75029daed5b4befe9f46d71042a974e7defe9ded23456e0fd) & we will follow their lead here.
Added `libfbjni` & `libreactnative` to exclude list so that these are subject of `duplicated dependency` error.
WIP
> fix(Android): patch potential issues with Android build since RN lib-merge in 0.76

- android/build.gradle
- android/src/main/AndroidManifest.xml
See the discussion:
https://github.com/software-mansion/react-native-screens/discussions/2597#discussioncomment-11759520
Removed the package declaration from Android Manifest.
Passing build should be enough.
> fix(Android): fix warning by removing package declaration from AndroidManifest

- .github/workflows/ios-build-test-fabric.yml
- .github/workflows/ios-build-test.yml
- .github/workflows/ios-e2e-test.yml
Apparently there are some issues with newer xcode versions on GitHub CI
Following [gesture-handler lead](https://github.com/software-mansion/react-native-gesture-handler/pull/3319/) here.
Set `xcode-version` to `16.1` temporarily in our CI workflow definitions.
hopefully iOS-related workflows pass
> chore(CI): fix part 2 - set xcode-version to 16.1

- android/src/fabric/java/com/swmansion/rnscreens/FabricEnabledHeaderSubviewViewGroup.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderSubview.kt
- android/src/paper/java/com/swmansion/rnscreens/FabricEnabledHeaderSubviewViewGroup.kt
- scripts/codegen-utils.js
- **Add FabricEnabledHeaderSubviewViewGroup to arch-check balcklist**
- **Fix naming**
> refactor(Android): rename `FabricEnabledHeaderSubviewGroup` -> `FabricEnabledHeaderSubviewViewGroup` + fix arch-consistency check

- ios/RNSScreenStackHeaderConfig.mm
I've made mistake in #2466 - the aforementioned protocol does not exist on Paper.
Use ifdef directive to prevent build errors.
iOS + old-arch should just build.
> fix(iOS): make `RCTMountingTransactionObserving` implementation new-arch only

- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- apps/src/tests/Test2282.tsx
This PR removes the workaround introduced in series of PRs (listed chronologically here):
1. https://github.com/software-mansion/react-native-screens/pull/2307
2. https://github.com/software-mansion/react-native-screens/pull/2383
3. https://github.com/software-mansion/react-native-screens/pull/2495
4. https://github.com/software-mansion/react-native-screens/pull/2531
For detailed description of error mechanism and broader discussion please refer to: 
1. [my comment on #2495](https://github.com/software-mansion/react-native-screens/pull/2495#issuecomment-2478915818),
2. [my fix to RN core](https://github.com/facebook/react-native/pull/47634)
tldr: When popping screen on Fabric we marked the views as "transitioning" and this led to view being effectively miscounted 
during removal by view …
> fix: remove workaround for removing clipped subviews

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- package.json
> release: 4.6.0-beta.0

- ios/RNSScreenStack.mm
> fix: Fix RN 78 compatibility (`mutation.parentTag`)

- ios/RNSScreenStackHeaderConfig.mm
In #2466 I've introduced `RCTMountingTransactionObserving` for `RNSScreenStackHeaderConfig` component.
Now we can use this to reduce amount of calls to `updateViewControllerIfNeeded` (causing layout passes) when adding subviews.
I'm not changing the `unmount` path of the code as we have some more additional logic there which requires some more 
careful consideration. 
This also aligns us with Paper implementation. Note that it has been only implemented this way, because at the implementation time there was no way
to run this code on transaction completion.
`- [RNSScreenStackHeaderConfig updateViewControllerIfNeeded]` is now called only once per transaction when adding subviews to header config.
Test432, TestHeaderTitle, Test2552 - see that there are no regressions. 
> [!note]
During …
> refactor(iOS): update view controller once per transaction when adding header subviews

- src/types.tsx
Closes #2633
Enhanced description of `formSheet` presentation style with information that nested stack rendering is not yet supported on Android.
> chore(types): update information on nested stack rendering support

- android/src/main/jni/rnscreens.h
- apps/src/shared/PressableWithFeedback.tsx
- apps/src/tests/Test2466.tsx
- apps/src/tests/Test2631.tsx
- apps/src/tests/index.ts
- common/cpp/react/renderer/components/rnscreens/RNSFullWindowOverlayComponentDescriptor.h
- common/cpp/react/renderer/components/rnscreens/RNSFullWindowOverlayShadowNode.cpp
- common/cpp/react/renderer/components/rnscreens/RNSFullWindowOverlayShadowNode.h
- common/cpp/react/renderer/components/rnscreens/RNSFullWindowOverlayState.h
- ios/RNSFullWindowOverlay.mm
- src/fabric/FullWindowOverlayNativeComponent.ts
Fixes #2631
I've given extensive description of both the issue ~and potential solution~ in #2631 issue discussion
* https://github.com/software-mansion/react-native-screens/issues/2631
In particular important parts are:
* https://github.com/software-mansion/react-native-screens/issues/2631#issuecomment-2606993563
* https://github.com/software-mansion/react-native-screens/issues/2631#issuecomment-2607054015
I settled down on zeroing origin of the `FullWindowOverlay` frame in HostTree & setting `ShadowNodeTraits::RootNodeKind` for the custom shadow node of `FullWindowOverlay` component in the ShadowTree. This is much cleaner than managing the state & content offset manually. 
`FullWindowOverlay` has now custom component descriptor, shadow node & shadow node state (its empty). The shadow …
> fix(iOS,Fabric): fix invalid position of FullWindowOverlay in certain scenarios

- package.json
- yarn.lock
Had issues editing top level project files as eslint language server would report missing dependency.
Installing it.
Added dev depenency on `eslint-plugin-ft-flow` for the library.
N/A
> chore: fix code editing (add dev dependency on eslint-plugin-ft-flow

- android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt
- apps/src/tests/Test2167.tsx
- apps/src/tests/index.ts
Fixes #2167
The exact error mechanism is **really** convoluted. The gist of it however, and the issue cause lies in the fact
that our drawing / container updating logic worked under implicit (and unspoken of) assumption that draw reordering would not be
applied for the transaction attaching very first screen in the stack. Everything worked correctly until #2019 caused `needsDrawReordeing`
to return `true` **always when `Build.VERSION.SDK_INT > 33`** - and that means pretty much **always** in new apps. Previously it returned `false`, 
in particular for the very first screen on stack because no one really sets `stackAnimation` for the very first screen, since [it will have no animation anyway](https://github.com/software-mansion/react-native-screens/blob/c0b5586b7e645ed1d22143b5f84e0dd65dcd0 …
> fix(Android): fix draw ordering in transparent modal & stack nested in tabs interaction

- package.json
Recently I've added new directory `android/src/versioned` with several source code files in #2660, however I've 
forgotten to include this directory in npm whitelist files, so they didn't get included in latest release (4.7.0-beta.2).
Fixing this in this PR.
Verified with `npm pack --dry-run` that these files are now included.
> fix: add missing files to whitelist in package.json

- .gitignore
Since Kotlin compiler 2.0 it seems that error logs are saved in `android/.kotlin` directory.
> chore(repo): exclude kotlin compiler log files from repo

- ios/RNSScreenContentWrapper.mm
In #2670 I've added a check that logged RN error in case `contentWrapper.reactSuperview` is not a `RNSScreenView`. 
Now I got reports (but no reproduction :/) from two independent sources that this error is triggered pretty often,
which is unexpected from my perspective. I blindly blame view flattening / usage of legacy navigators but can not be sure.
This PR is an attempt to patch this behaviour.
contentWrapper now searches whole view ancestor chain before logging an error.
No reproducer :/
> fix(iOS): look through whole ancestor chain when looking for screenview from content wrapper

- android/src/fabric/java/com/swmansion/rnscreens/FabricEnabledHeaderSubviewViewGroup.kt
Small oversight (:sweat-smile:) but we have infinite state update loop in header subview caused by not comparing 
current value to previous one (check out code changes, it will be obvious).
We have similar checks in `FabricEnabledViewGroup` & `FabricEnabledHeaderConfigViewGroup`.
Added a check that prevents the loop.
> fix(Android,Fabric): inifinite state update loop in header subview

- src/types.tsx
This is a small discrepancy between platforms, which might be patched in next major if needed (created ticket on internal board)
Closes #2697 (see discussion)
Updated types of `sheetAllowedDetents`.
N/A
> chore(docs): add note that `fitToContents` includes small bottom padding on iOS

- android/build.gradle
Starting from Android 15 devices can use 16KB page size instead of 4KB. Apps that take advantage of this require additional linker flag.
This PR adds aforementioned flag so that apps that use Screens don't crash.
>[!NOTE]
> More info can be found [here](https://developer.android.com/guide/practices/page-sizes)
I've tested it while working on the same change in [Reanimated](https://github.com/software-mansion/react-native-reanimated/pull/7037). After adding this flag into screens app stopped crashing.
I've also tested it on `FabricExample` in Screens on AVD with 16KB page size. I've had some problems with this example app, but after adding this flag it stopped crashing on start (it still show some errors about undefined function though, but I believe the problem lies in my setup).
> [Android] Add support for 16KB page size

- android/src/main/jni/CMakeLists.txt
Variable names prefixed with `$` are heavily utilised in codegened code. This leads to a wall of warnings popping up during every Android build. This PR aims to suppress these warnings.
Added `-Wno-dollar-in-identifier-extension` compile time flag to `react_codegen_rnscreens` target.
Clean caches & build fresh Android project with react-native screens.
> chore: suppress `-Wdollar-in-identifier-extension` compile time warning

- common/cpp/react/renderer/components/rnscreens/RNSScreenStackHeaderSubviewComponentDescriptor.h
Closes #2709
Relative import to subdirectory causes issues when using frameworks. 
Fresh project should now build.
> fix(iOS): missing import when using frameworks on ios

- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenContainerManagerInterface.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenContentWrapperManagerInterface.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenFooterManagerInterface.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerInterface.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderConfigManagerInterface.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderSubviewManagerInterface.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenStackManagerInterface.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSSearchBarManagerInterface.java
Seems that these have changed. 
Updated codegened files for old architecture by running `yarn sync-architectures`.
> [!caution]
I think that these changes also break compatibility on old architecture.
Let's see whether Paper build works now on CI...
> fix(Android,Paper): regenerate codegened files for old architecture

- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt
- android/src/main/java/com/swmansion/rnscreens/bottomsheet/DimmingViewManager.kt
- apps/src/tests/TestFormSheet.tsx
Shout out to @kligarski for spotting this out!
I've introduced a regression in 4.7.0 when refactoring sheet animation - basically it always animated to the resolved `maxAlpha`
for given sheet dimming view & did not take into account `sheetLargestUndimmedDetentIndex` prop, effectively disabling this prop.
This affects both architectures.
When configuring enter animation we now take the prop into account.
`TestFormSheet`
> fix(Android): fix sheet transition when there is no dimming applied

- scripts/codegen-utils.js
We do not need to apply workarounds for versions of react native below 72 for a long time now.
Removed the workaround code.
Paper should build on whole supported version range (currently 0.76 - 0.78).
> chore: remove unused workaround for RN 72 in interface-sync script

- ios/utils/RNSDefines.h
It seems that '-' characters in import names are swapped for '_' when using dynamic frameworks,
therefore we need to check not only for `React-RCTAppDelegate` but also for `React_RCTAppDelegate`.
Build with `USE_FRAMEWORKS=dynamic` now passes.
> fix(iOS,Fabric): fix MUTATION_PARENT_TAG definition when using dynamic frameworks

- android/build.gradle
- android/src/main/AndroidManifest.xml
Add fixes connected with changing RN to `react-native@0.77.1` before release.
- https://github.com/software-mansion/react-native-screens/pull/2602
- https://github.com/software-mansion/react-native-screens/pull/2603
- https://github.com/software-mansion/react-native-screens/pull/2608
Run example apps from the repo, run new app that uses RN 0.77.1 and this version of RNS.
> fix(Android): apply fixes for RN 0.77.1 before release

- apps/src/tests/TestFormSheet.tsx
- ios/RNSScreen.mm
- ios/RNSScreenContentWrapper.h
- ios/RNSScreenContentWrapper.mm
- ios/utils/RNSDefines.h
Given numerous feature requests & the frequent need to have header above the scrollview in sheet this PR adds this possibility. 
Please see [`TestFormSheet`](https://github.com/software-mansion/react-native-screens/blob/main/apps/src/tests/TestFormSheet.tsx) for example implementation.
Note that this PR enables header by handling special case when there is **exactly one** view rendered directly under sheet at index 0 (and scroll view on index 1). Again - see example ☝🏻 
We're now detecting special case inside content wrapper: scroll view at index 0 or header at 0 & scrollview at 1. We then adjust the layout manually. If these cases are not detected we fallback to previous behaviour.
Enhanced `TestFormSheet` to allow for testing this.
> feat(iOS): add experimental support for scrollview header when using formsheet

- src/components/ScreenStackItem.tsx
- src/native-stack/views/NativeStackView.tsx
Fixing the styles applied to the content in screens with `formSheet` presentation.
Currently when using `flex: 1` on the content of the sheet it might cause the content to disappear. This PR mitigates that. 
When not in `fitToContents` mode we apply `flex: 1` to content wrapper. 
`TestFormSheet` - notice that the contents has `flex: 1` and it displays correctly.
> fix(Android): missing content when using flex for formsheet contents

- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.kt
Fixes #2745 
Use `TextUtils` to compare the value of `view.text` and `toolbar.title`. `text` and `title` are `CharSequence`, there are no guarantee that they will be the same type, therefore the `==` comparison could fail.
For example, `Toolbar` could be styled natively in the project, therefore the value of its `TextView` child could be `SpannableString`, while title could be still just a `String`.
> fix(Android): findTitleTextViewInToolbar couldn't find the correct view in certain cases

- README.md
README update before release of 3.37.0.
- add 3.37.0+ to Paper section with support for RN 0.76+
> docs: update supported RN versions in README before release

- src/components/Screen.tsx
- src/components/ScreenStackItem.tsx
- src/native-stack/views/NativeStackView.tsx
I've made a small change in v5 code in #2748, however due to my overlook it introduced a regression in native-stack v5.
Since it is a quick fix I'm patching it. 
Basically I've parsed & transformed `sheetAllowedDetents` value in `RouteView`, **before** passing it to `MaybeNestedStack`, where
I've checked for `sheetAllowedDetents === 'fitToContents'`, which could not be true, because in such case it has been transformed to `[-1]`
literal in `RouteView`.
Only the latest 4.10.0-beta.0 & beta.1 versions are affected.
Removed `sheetAllowedDetents` prop value transformation in `RouteView` since `Screen` component handles it nicely internally.
`TestFormSheet`, but you need to run it using `createNativeStackNavigator` from `react-native-screens/native-stack`.
Don't forget to change the …
> fix(Android,native-stack): fix check for `sheetAllowedDetents` value & apply appropriate styles

- android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt
- android/src/main/java/com/swmansion/rnscreens/utils/FragmentTransactionKt.kt
Notoriously when skimming through this method I find it hard to follow & promise my self I'll clean it up.
Took a year, but finally did it. 
- **Move animation logic out to extension method**
- **Remove redundant comments**
- **Kotlinize fragments of ScreenStack.onUpdate function**
- **Rename it -> transaction**
- **Continue Kotlinizing `ScreenStack.onUpdate`**
- **Comments & whitespace**
- **Kotlinize newTop & visibleBottom finding**
- **Simplify if conditions**
- **Move logic that is not dependant on transaction out of it scope block**
- **Avoid allocation of whole new list while mapping**
Tested this carefully on multiple tests: 
1. TestFormSheet (navigation from & to transparent screens)
2. Nested stacks & bottom tabs in Example 
3. Test881
4. TestPreload
> refactor(Android): kotlinize `ScreenStack.onUpdate` method

- Example/metro.config.js
- FabricExample/metro.config.js
- TVOSExample/metro.config.js
> [!caution]
> ~TODO:  Needs to be rebased on top of main, dropping changes from #2736~ done
I've explained the issue in code comments: metro by default picks up source files from 
`@react-navigation/xxx/lib` instead of ones from `@react-navigation/xxx/src`. 
This makes playing with `@react-navigation` & testing it harder (even when one just need to add some logs)...
This PR adds a resolver, which explicitly resolves `@react-navigation/xxx` packages imports to the `@react-navigation/xxx/src/*` implementation. 
This PR also makes sure the metro block-list works correctly.
No extra tests needed - just example apps should build & load.
You can now add a `console.log` into react-navigation submodule code & it will work!
> chore(examples): adjust metro config to allow for easier modify-test loop with react-navigation submodule

- apps/Example.tsx
In `Example.tsx`, we run `enableFreeze()` but it will be overwritten by `enableFreeze(true)` in `App.tsx` as the call from `App.tsx` is run after `Example.tsx`.
In case changing this setting is necessary for testing, it should be changed in top-level file of the app, in our case it is the `App.tsx`.
I left out `enableFreeze` wrapped in `useEffect` in `Test2229.tsx` as it will be called when running the test.
- remove `enableFreeze()` from `Example.tsx`
> chore: remove unnecessary enableFreeze from Example.tsx

- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackViewManager.kt
- android/src/main/java/com/swmansion/rnscreens/ext/ViewExt.kt
- apps/src/tests/TestFormSheet.tsx
Closes #2773
Android, for some reason, draws exiting views first. If there are multiple exiting views it also reverses their drawing order. 
In case of non-transparent screens we already have a workaround for that - we change the order or drawing last two screens when needed.
`formSheet` presentation introduced whole new layer of complexity - due to transparency there are cases where multiple **visible** screens are dismissed at once, resulting in jarring visual effects (see recording titled "before" below 👇🏻 ) 
| --- | --- |
| <video src="https://github.com/user-attachments/assets/01290c1f-d1dc-4668-ada3-70b2fe10e17c" alt="before" /> | <video src="https://github.com/user-attachments/assets/9b8566c0-91fd-41d5-8af8-50e01611a702" alt="before" /> |
We now handle case of …
> fix(Android): fix drawing order when dismissing multiple stacked sheets

- Example/ios/Podfile.lock
- Example/package.json
- Example/yarn.lock
Currently, e2e fails because Example uses reanimated v4 which does not support old architecture.
Seems that 3.17.1 has some problems also -> we need to wait for newer version.
Installed reanimated 3.17.1 in `Example` app.
Hopefully e2e tests on CI pass.
> chore(CI): install reanimated 3.17.1 in `Example`

- android/src/fabric/java/com/swmansion/rnscreens/FabricEnabledHeaderConfigViewGroup.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfigShadowNode.kt
- android/src/main/java/com/swmansion/rnscreens/utils/PaddingBundle.kt
- android/src/paper/java/com/swmansion/rnscreens/FabricEnabledHeaderConfigViewGroup.kt
Fixes #2758
#2466 removed old workaround for header config blocking gestures - we just set top: `-100%` 
to place the headerconfig in the top of the screen effectively preventing blocking. 
#2466 removed these styles & frame correction is now applied directly in shadow node. This is done fine
on Fabric, however the solution was not replicated on Paper.
Beside padding information we now send native toolbar height to header config shadow node on Paper.
This information is used there to offset the header config position by this value.
Should solve the problem.
| - | - |
| <img src="https://github.com/user-attachments/assets/640cad09-584d-4983-af92-11ae68d49f9f" alt="before" /> | <img src="https://github.com/user-attachments/assets/de15190e-e999-495f-8a6d-abf7f375d468" …
> fix(Android,Paper): header config blocks gestures close to the top of the screen

- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt
- android/src/main/java/com/swmansion/rnscreens/bottomsheet/SheetDelegate.kt
On each fragment reattachment we reconfigure the behaviour, but we do not keep the state.
Each time we use `sheetInitialDetentIndex` instead of the last stable detent index. 
This PR moves sheet configuration to `SheetDelegate` to declutter `ScreenStackFragment` & uses appropriate value during configuration.
Lifecycle of the `SheetDelegate` is tied to the fragment, therefore on fragment **recreation** (not *reattachment*) the state still will be lost.
> [!note]
There still is no animation when navigating from `formSheet` to `push` in the same stack, but it is separate issue (already WIP to handle this).
| -- | -- |
| <video src="https://github.com/user-attachments/assets/e42b00db-bd72-4265-8f5e-9c5bbf0425dd" alt="before" /> | <video …
> fix(Android): keep `formSheet` selected detent index after fragment reattachment

- .github/workflows/android-e2e-test.yml
Add missing AVD dependency.
- add missing AVD dependency to android-e2e-test (Paper) workflow.
Run CI for Paper Android.
> fix(CI): add missing AVD dependency to Paper Android e2e workflow

- FabricExample/e2e/examplesTests/events.e2e.ts
Changed order of events in Fabric iOS events e2e test.
The order of events in this test differs from the Paper version of the same test. When screen is removed after using iOS native back button, native side notifies JS via:
1. onDismissed => in reaction to this event, a navigation action is dispatched, which causes emission of beforeRemove event;
2. onDisappear => in reaction to this event, transitionEnd with closing=true is emitted.
On Fabric, these events are handled in the same order as the order of notifications from the native side. On Paper, this is not the case - onDismissed is executed after two transitionEnd events are already handled. onDismissed is dispatched asynchronously from the native side (it is wrapped in `dispatch_async`!) and this probably delays handling it on JS …
> fix(CI): change order of events in Fabric iOS events e2e test

- android/src/fabric/java/com/swmansion/rnscreens/FabricEnabledViewGroup.kt
- android/src/fabric/java/com/swmansion/rnscreens/NativeProxy.kt
- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackViewManager.kt
- apps/src/tests/Test2223.tsx
- apps/src/tests/TestFormSheet.tsx
- common/cpp/react/renderer/components/rnscreens/RNSModalScreenShadowNode.cpp
- cpp/RNSScreenRemovalListener.cpp
- src/components/Screen.tsx
This PR relates to new architecture only.
Currently, the pressables on form sheet lose focus on `move` action. This is the same problem we had with `Pressables` in screen & header on new architecture. 
See: https://github.com/software-mansion/react-native-screens/pull/2466
Basically the information about sheet position is different between `ShadowTree` (ST) and `HostTree` (HT), which leads to losing focus due to how pressables
are now handled on new architecture.
**Simplified description** of basically what happens when you click a pressable on new arch is as follows (Android):
1. The gesture is detected after the host platform dispatches touch event (touch events on Android are dispatched in top-down manner) [(link)](https://github.com/facebook/react-native/blob/d6ca25b0c1a0aeed3507ec3c2f …
> fix(Android,Fabric): pressables losing focus on screens with `formSheet` presentation

- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- android/src/main/java/com/swmansion/rnscreens/bottomsheet/SheetDelegate.kt
- apps/src/tests/Test2789.tsx
- apps/src/tests/TestRepro.tsx
- apps/src/tests/index.ts
When fragment is reattached (on navigation back) `onCreateView` is called which tries to configure the form sheet (that has `fitToContents` set).
On view recreation the subtree is not laid out (the flag is cleared) & therefore current code fails.
We now utilise the fact, that the Screen's subtree is retained by react-native and the components are not recreated themselves -> old height is stored in the member variable. 
We reuse it. 
Added Test2789
> fix(Android): `formSheet` with `fitToContents` does not have correct height after goBack

- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.kt
- android/src/versioned/pointerevents/77/com/swmansion/rnscreens/PointerEventsBoxNoneImpl.kt
- android/src/versioned/pointerevents/latest/com/swmansion/rnscreens/PointerEventsBoxNoneImpl.kt
Closes #2794
We set `visibility = GONE` for the header config in HostTree (HT), however this only prevents the Android framework from setting header config frame,
and does not prevent `ReactNative` from setting non-zero frame. When it has non-zero frame, react recognizes it as a touch target.
I've implemented `ReactPointerEventsView` (returning `box-none`) making sure that RN won't treat it as touch target.
I considered another approach - setting the frame to zero or not letting react native to set the frame on the view - it also works, 
however requires cumbersome implementation on Android API level < 29, since `suppressLayout` method is available since 29.
On lower API levels you can not really ignore the frame - you can call `layout` with 0 width in `onLayout` of the header config... …
> fix(Android): implement ReactPointerEventsView to prevent header config from intercepting touches

- guides/GUIDE_FOR_LIBRARY_AUTHORS.md
- ios/RNSScreen.mm
Brings back `stackPresentation: 'modal'`'s size on iOS 18.0+.
Since the release of iOS 18, screens with `stackPresentation: 'modal'` changed size on devices with a bigger screen, such as an iPad - they became much smaller, which impacted applications of the library's users (see issue https://github.com/software-mansion/react-native-screens/issues/2549). This happens because `UIModalPresentationAutomatic`, which is used by `react-native-screens` for modal on iOS, has been changed with the release of iOS 18. `UIModalPresentationAutomatic` is now mapped to `UIModalPresentationFormSheet` for iOS >=18 and `UIModalPresentationPageSheet` for earlier versions (this was the default before).
For more context please see PR https://github.com/software-mansion/react-native-screens/pull/2793 but the …
> fix(iOS): use prefersPageSizing for modal on iOS 18.0+

- ios/RNSScreenStackHeaderConfig.h
- ios/RNSScreenStackHeaderConfig.mm
This method is very hard to read & it is very scary to refactor
since as far as I remember, sometimes even call order matters here.
Therefore, I've decided to split the refactoring process into many small PRs.
This PR improves local variable naming & extracts LTR handling to separate method.
Nothing should change. LTR works as earlier. Can be tested in Example by toggling RTL mode (there is a button for it).
> refactor(iOS): cleanup no. 1 in `RNSScreenStackHeaderConfig.updateViewController:withConfig:animated:`

- FabricExample/ios/Podfile.lock
- RNScreens.podspec
This is not a breaking change, because we support `react-native` 0.76+ anyway, and it has iOS min 
deployment target [set to 15.1](https://github.com/react-native-community/discussions-and-proposals/discussions/812)
This is needed because I work with @maciejstosio on an issue with `backButtonDisplayMode` & it has been introduced 
in iOS 14.0. The workaround I've found works only on iOS >= 14.0, therefore it would be nice to not have to 
add any ifdefs in source code. 
Bumped the min. supported iOS version to 15.1 from 11.0.
I've left the new-arch-condition in the podspec code, despite the fact that it is not needed, 
so that it is clear where do we change things when it becomes needed.
tvOS version is left unchanged for now (most likely it should also be updated!).
The app should build …
> chore: update iOS min supported version to 15.1

- android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderSubview.kt
When setting subviews via `setOptions` from `useEffect` hook in a
component, the first frame received might be computed by native
layout & completely invalid (zero height). RN layout is the source of a
subview **size** (not origin). When we send such update with zero height
Yoga might (or might not, depending on exact update timing in relation
to other ongoing commits / layouts) set the subview height to 0!
This causes the subview to become invisible & we want to avoid that.
This had not been a problem before https://github.com/software-mansion/react-native-screens/pull/2696, because we would filter out
this kind of frame in the `setSize` guard in the
`ComponentDescriptor.adopt` method of the `HeaderSubview`. https://github.com/software-mansion/react-native-screens/pull/2696 allowed
for …
> fix(Android,Fabric): prevent header subview disappearance when using `setOptions`

- apps/Example.tsx
Adds sorting of test screens in the menu to example apps.
- add sorting of test screens before rendering example app menu
Open example app.
> chore: sort test screens by test number

- guides/GUIDE_FOR_LIBRARY_AUTHORS.md
- ios/RNSScreenStackHeaderConfig.mm
- native-stack/README.md
- src/native-stack/types.tsx
- src/types.tsx
See: https://github.com/react-navigation/react-navigation/pull/12500 
for issue description with videos.
We can use the backbuttondisplaymode to hide the backbuttontitle avoiding setting the title to `nil`
and therefore preventing the UIKit buggy back button icon animation.
@maciekstosio:
We agreed to leave `backTitleVisible`, so the API doesn't change in a minor version. The expected behavior is that `backTitleVisible: false` will work as "kill switch" and ignore other back button properties. When `backTitleVisible: true` other properties will work (including backButtonDisplayMode), but note that iOS omits `backButtonDisplayMode` when custom back button is provided (so when any of  `backTitleFontSize`, `backTitleFontFamily`, `headerBackButtonMenuEnabled`, `headerBackTitle` is used). …
> fix(iOS): prevent back button icon from "jumping" during pop animation when display mode minimal is set

- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenFragment.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenFragmentWrapper.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenModalFragment.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt
Makes it more straightforward to get translucency information from fragment.
- **Expose `isTranslucent` on `ScreenFragmentWrapper` & rename `Screen.isTransparent`**
- **Add comments**
- **Add comments 2**
- **Use newly exposed method**
- **Update ScreenModalFragment**
Nothing changes in behaviour.
> refactor(Android): add `isTranslucent` to `ScreenFragmentWrapper` & align method naming on `Screen`

- FabricExample/Gemfile.lock
- FabricExample/e2e/examplesTests/tests.e2e.ts
- FabricExample/ios/Podfile.lock
- apps/src/shared/Square.tsx
- apps/src/tests/Test432.tsx
- apps/src/tests/index.ts
Check which example screens from issues/PRs can be used in e2e testing for tests `Test42, ..., Test528` and implement them if possible for Fabric. In the future, each non-skipped test will be in a seperate PR.
Skipped because we can’t really check what is the orientation of the screen with Detox.
Skipped because we can’t test flickering with Detox.
Skipped because example differs from the problem mentioned in https://github.com/software-mansion/react-native-screens/issues/263. Even when I recreated the issue, it still occurs. [This comment from the PR](https://github.com/software-mansion/react-native-screens/issues/263#issuecomment-930127450) explains why it is the case. 
Skipped because we can’t test autofill with Detox. The test also uses outdated prop name.
Skipped because the test …
> test(e2e,Fabric): add e2e tests for issue/PR examples 42..528

- Example/ios/Podfile.lock
- Example/package.json
- Example/yarn.lock
- FabricExample/ios/Podfile.lock
- FabricExample/package.json
- FabricExample/yarn.lock
- apps/src/screens/BottomTabsAndStack.tsx
- package.json
- yarn.lock
Fixes CI on both platforms.
- change Example to use tab bar button test ID option available in react-navigation 6 (previous one was correct for react-navigation 7 but example apps use version 6)
- bump to `react-native-reanimated@3.17.2` in order to fix the issue with Android CI (https://github.com/software-mansion/react-native-reanimated/pull/7196)
CI
> fix(CI): update Example, bump reanimated

- src/components/ScreenContentWrapper.windows.tsx
- src/components/ScreenFooter.windows.tsx
- src/utils.ts
- windows/RNScreens/ModalScreenViewManager.cpp
- windows/RNScreens/ModalScreenViewManager.h
- windows/RNScreens/RNScreens.vcxproj
- windows/RNScreens/RNScreens.vcxproj.filters
- windows/RNScreens/ReactPackageProvider.cpp
- windows/RNScreens/Screen.cpp
- windows/RNScreens/Screen.h
- windows/RNScreens/ScreenStackHeaderConfig.cpp
- windows/RNScreens/ScreenStackHeaderConfig.h
- windows/RNScreens/ScreenStackHeaderConfigViewManager.cpp
- windows/RNScreens/ScreenStackHeaderConfigViewManager.h
- windows/RNScreens/ScreenStackHeaderSubview.cpp
- windows/RNScreens/ScreenStackHeaderSubview.h
- windows/RNScreens/ScreenStackHeaderSubviewViewManager.cpp
- windows/RNScreens/ScreenStackHeaderSubviewViewManager.h
- windows/RNScreens/ScreenViewManager.cpp
- windows/RNScreens/SearchBar.cpp
- windows/RNScreens/SearchBar.h
- windows/RNScreens/SearchBarViewManager.cpp
- windows/RNScreens/SearchBarViewManager.h
Fixes problems with building and crashes in Windows apps. Some components are still WIP and we'll finish work on them in the future.
Resolves https://github.com/software-mansion/react-native-screens/issues/2541.
- add Windows-specific implementations of `ScreenContentWrapper` and `ScreenFooter`,
- start work on stack header and subviews, searchbar,  stack animations - these components are not implemented yet
- change minimum version of `WindowsTargetPlatform` to match `WinUI` requirements,
Create new `react-native-windows` app with components from `react-native-screens`, build and run (it might be necessary to run `npx react-native run-windows` twice in order to install all required packages).
> fix(Windows): fix building and crashing issues

- ios/RNSScreenStack.mm
Following up:
* https://github.com/software-mansion/react-native-screens/pull/2249#issuecomment-2252594635
* [internal ticket](https://github.com/orgs/software-mansion/projects/3/views/1?pane=issue&itemId=72358100)
Added a code comment explaining that there are scenarios where `self.tag` might not have
valid value during component removal from screen stack.
N/A
> chore(iOS): add code comment explaining validity of a tag value

- apps/src/tests/Test2538.tsx
- apps/src/tests/index.ts
- ios/RNSScreen.mm
Fixes #2538
From time to time the **snapshot** of exiting screen would receive bad frame from the OS during the transition
resulting in the visual bug depicted in #2538 and on video down below :point_down:.
Basically what happens is described by logs present on the recording below.
In JS initiated back transition we exchange the `screenView` with its snapshot &
the snapshot **sometimes** receives UIKit-originated frame with origin at `(0, 0)`.
I guess it happens only sporadically, because there is some race condition, between
animation & layout depending on whether the navigation bar is still attached in the model
tree or not.
There is no issue in natively initiated back transition.
https://github.com/user-attachments/assets/d9d90cac-4507-44ff-bda1-619b71b5da56
I've decided to go with …
> fix(iOS,Fabric): fix sporadic exiting screen content jump on goBack action

- guides/GUIDE_FOR_LIBRARY_AUTHORS.md
- native-stack/README.md
- src/types.tsx
Small changes in docs.
- add deprecation messages to navigation/status bar related props deprecated in https://github.com/software-mansion/react-native-screens/pull/2638 in `GUIDE_FOR_LIBRARY_AUTHORS.md`
- fix typo in `src/types.tsx`
- update information about `formSheet` in `GUIDE_FOR_LIBRARY_AUTHORS.md`
> docs: update information in native-stack's README and guide for library authors

- FabricExample/e2e/issuesTests/Test593.e2e.ts
- apps/src/tests/Test593.tsx
- apps/src/tests/index.ts
Create e2e test for `Test593`.
Test created. Test screen changed to allow using `default` and `none` stack animations. Events and their order is different than in related PRs (https://github.com/software-mansion/react-native-screens/pull/593, https://github.com/software-mansion/react-native-screens/pull/941) but it matches behavior from `Events` test screen.
- add e2e test for `Test593`
- add comment in `apps/src/tests/index.ts`
CI
> test(e2e, Fabric): add e2e test for issue/PR example 593

- FabricExample/e2e/issuesTests/Test640.e2e.ts
- apps/src/tests/Test640.js
- apps/src/tests/index.ts
Check which example screens from issues/PRs can be used in e2e testing for tests `Test619, ..., Test640` and implement them if possible for Fabric. 
Skipped because we can't check components "jumping".
Skipped because the change in PR https://github.com/software-mansion/react-native-screens/pull/624 is connected to internal JS prop. The test screen seems to be repurposed.
Test created. It checks if `RefreshControl` works correctly with `modal` (refresh instead of the modal closing).
- add `Test640`
CI
> test(e2e, Fabric): add e2e tests for issue/PR examples 619..640 

- .github/workflows/windows-build-test.yml
Select `react-native version` for test project based on `react-native-windows` latest version.
Sometimes, when new `react-native` version is released but `react-native-windows` is not yet available for this version, CI might fail because of the version mismatch. Now we fetch latest version of `react-native-windows` from NPM in format `x.yy.zz` and we use `x.yy` to determine latest supported version of `react-native`. Then we use it to initialize new `react-native` project.
- modify Windows CI
Windows CI
> test(Windows): select react-native version for test project based on react-native-windows latest version

- ios/RNSFullWindowOverlay.h
- ios/RNSFullWindowOverlay.mm
- src/components/FullWindowOverlay.tsx
- src/fabric/FullWindowOverlayNativeComponent.ts
The prop defaults to `true` due to backward compatibility reasons.
I believe this should be changed with major version change.
There is no need to update Android interfaces, because we render plain `View` there in place of `FullWindowOverlay`.
The prop is `unstable` since I haven't decided yet on whether
I want to expose completely new prop or make
`RNSFullWindowOverlayContainer` use value of
`RNSFullWindowOverlay.accessibilityViewIsModal`.
This would be possible, because it is regular prop on `View`
component. See: https://reactnative.dev/docs/view#accessibilityviewismodal-ios
Currently I went with new prop and not repurposing `accessibilityViewIsModal` on `RNSFullWindowOverlay` since I'm not that familiar with the accessibility API & want to avoid focus request collisions etc. & in case …
> feat(iOS): add `unstable_accessibilityContainerViewIsModal` prop for `FullWindowOverlay`

- apps/src/tests/Test2855.tsx
- apps/src/tests/index.ts
- common/cpp/react/renderer/components/rnscreens/RNSScreenShadowNode.cpp
- ios/RNSScreen.mm
- ios/RNSScreenStackHeaderConfig.mm
Fixes #2855
The issue is obvious, I'm staggered that we have not caught it much earlier. 
When `headerconfig.translucent == true` we lay out the `RNSScreenView` underneath the navigation bar & keep sending non-zero content offset to screen shadow node.
Now, when `headerconfig.translucent == true` we send `contentOffsetY == 0`.
Added `Test2855`. Also should be reproducible on `Test2466` when you set `headerTranslucent: true` on the screen with pressables.
> fix(iOS,Fabric): `TouchableOpacity` does not work on screens with `headerTranslucent: true` on notchless iOS devices with older OS versions

- RNScreens.podspec
15.1 is the lowest supported version from `react-native-tvos@0.76` onwards.
https://github.com/react-native-tvos/react-native-tvos?tab=readme-ov-file#general-support-for-tv
- **Bump deployment target for tvOS to 15.1**
N/A
This should not affect the users, unless they're not applying to our compatibility matrix.
> feat(tvOS): bump min. deployment target to 15.1

- ios/RNSScreenStackHeaderConfig.mm
Followup to https://github.com/software-mansion/react-native-screens/pull/2862 after 
https://github.com/software-mansion/react-native-screens/pull/2863 is merged. 
- **Cleanup in RNSScreenStackHeaderConfig**
Build
> refactor(iOS): remove code unused on tvOS & iOS >= 15.1

- ios/RNSScreenStackHeaderConfig.mm
I plan to split this into multiple PRs to simplify process of catching potential regressions.
Move all code responsible for back item configuration to separate methods,
so that reading `updateViewController:withConfig:animated:` becomes easier to read.
I did some sanity checks, seems to work as earlier.
> refactor(iOS): move back item configuration to separate method

- Example/package.json
- Example/yarn.lock
- FabricExample/package.json
- FabricExample/yarn.lock
- package.json
- src/components/Screen.tsx
- src/components/ScreenStackHeaderConfig.tsx
- src/components/helpers/edge-to-edge.tsx
- yarn.lock
> [!note]
> note by @kkafar: 
> Please note that I merge this as unstable behaviour, since I might want to remove the dependency & code once we land https://github.com/facebook/react-native/pull/47554 in core or endup with only edge-to-edge supported by Android.
This follow a discussion started [on the react-navigation repository](https://github.com/react-navigation/react-navigation/pull/12217).
The future of Android is [edge-to-edge](https://developer.android.com/about/versions/15/behavior-changes-15#edge-to-edge), and to make the React Native developer experience seamless in this regard, the ecosystem needs to transition from “opaque system bars by default” to “edge-to-edge by default.”
To prevent library authors from implementing their own edge-to-edge solutions—which could interfere …
> feat(Android,**unstable**): integration with `react-native-edge-to-edge`

- FabricExample/e2e/issuesTests/Test645.e2e.ts
- apps/src/tests/Test645.js
- apps/src/tests/index.ts
Check which example screens from issues/PRs can be used in e2e testing for tests `Test642, Test645` and implement them if possible for Fabric. 
Skipped because we can't check status bar visibility/style.
Test created, only on iOS (`headerLargeTitle` is supported only on iOS). It checks if `headerLargeTitle` isn't collapsed when changing screens. I changed `Test645` screen to use `ScrollView` because it was used in original issue.
- add `Test645`
- change regular `View` to `ScrollView` in test screen `Test645`
CI
> test(e2e, Fabric): add e2e tests for issue/PR examples 642..645

- common/cpp/react/renderer/components/rnscreens/RNSScreenStackHeaderConfigState.h
- src/components/ScreenStackHeaderConfig.tsx
- src/components/ScreenStackHeaderConfig.web.tsx
No idea why `ScreenStackHeaderSearchBarView` is typed this way, however it does not accept the 
props it declares on type level. This is plain `RCTView` / `RCTViewComponentView` (depending on architecture).
`SearchBar` does accept `SearchBarProps`.
- **Style changes in headerconfig state**
- **Simplify typing on ScreenStackHeaderConfigSubview**
- **Fix typing for `ScreenStackHeaderSearchBarView`**
N/A; Type fix. Hopefully we do not break anything, however if someone passed props to this component 
they did not have any effect anyway.
> fix: `ScreenStackHeaderSearchBarView` invalid props type

- src/components/SearchBar.tsx
Renaming param to avoid name collisions.
N/A
> refactor: fix warning in `SearchBar` code by renaming param

- android/src/main/java/com/swmansion/rnscreens/CustomToolbar.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.kt
We noticed you folks were using `ChoreographerCompat` from ReactNative which has been removed in RN 0.80
(it was deprecated for a while).
You should instead use `android.view.Choreographer`
> [0.80] Do not use ChoreographerCompat

- src/components/ScreenStackHeaderConfig.web.tsx
Follow up to #2833, review: https://github.com/software-mansion/react-native-screens/pull/2883#pullrequestreview-2786094325
`ViewProps` already do have children, there is no need to specify it for the second time. 
Web should work as before.
> refactor(web): cleanup types in ScreenStackHeaderConfig

- .github/workflows/npm-screens-publish-nightly.yml
This fixes `Build nightly and publish on npm` workflow.
Removes obsolete workflow steps. They were checking against the file that no longer exists.
> chore(CI): fix workflow commands

- FabricExample/e2e/issuesTests/Test649.e2e.ts
- apps/src/tests/Test649.js
- apps/src/tests/index.ts
Check which example screens from issues/PRs can be used in e2e testing for tests `Test648, Test649` and implement them if possible for Fabric. 
Skipped because we can't check new animation in any meaningful way.
Test created, only on iOS (`headerLargeTitle` is supported only on iOS). It checks if `headerLargeTitle` isn't collapsed when coming back from a screen without `headerLargeTitle`. I changed `Test649` screen to match original issue.
- add `Test649`
- change header to normal size on Second screen in `Test649` to match original issue
CI
> test(e2e, Fabric): add e2e tests for issue/PR examples 648..649

- FabricExample/e2e/issuesTests/Test654.e2e.ts
- apps/Example.tsx
- apps/src/shared/SettingsSwitch.tsx
- apps/src/tests/Test654.js
- apps/src/tests/index.ts
Create e2e test for `Test654`.
Test created, only on iOS. It checks that native back button is rendered correctly in RTL mode.
- add testID to RTL mode switch in Example screen
- add e2e test for `Test654`
- add comment in `apps/src/tests/index.ts`
CI
> test(e2e, Fabric): add e2e test for issue/PR example 654

- .github/workflows/npm-screens-publish-nightly.yml
- scripts/create-npm-package.sh
Fixing issues making the CI not work!
* fixed relative paths to `set-version` script from `create-npm-package` script
* removed job steps of `npm-screens-publish-nightly` workflow, since we do not generate `build.log` file at any point; we're also not including any `node_module` files into a release due to `whitelist` placed in `package.json`.
Let's see whether CI passes
> fix(CI): publish nightly - incorrect relative paths to scripts & missing build.log

- FabricExample/e2e/issuesTests/Test658.e2e.ts
- apps/src/tests/Test658.js
- apps/src/tests/index.ts
Create e2e test for `Test658`.
Test created. It checks that opening multiple modals/transparent modals works correctly.
- modify `Test658` screen to allow testing:
- change `dangerouslyGetState()` to `getState()` ([details](https://reactnavigation.org/docs/6.x/upgrading-from-5.x/#dropped-dangerously-from-dangerouslygetparent-and-dangerouslygetstate))
- move buttons from under status bar
- add `Text` with screen number
- add testIDs
- add e2e test for `Test658`
- add comment in `apps/src/tests/index.ts`
CI
> test(e2e, Fabric): add e2e test for issue/PR example 658

- FabricExample/e2e/issuesTests/Test2877.e2e.ts
- apps/src/tests/Test2877.tsx
- apps/src/tests/index.ts
- ios/RNSScreen.mm
Allows `fitToContents` sheet's height to adapt to dynamic content on iOS.
`contentWrapper:(RNSScreenContentWrapper *)contentWrapper receivedReactFrame:(CGRect)reactFrame` receives many frames, some of them contain the same dimensions. Calling `[self setAllowedDetentsForSheet:sheetController to:detents animate:YES]` mutliple times, even with the same `detents`, causes visual glitches (dimming behing formSheet on iPhone/iPad and header on iPad have very odd-looking animations).
Before, we would set `_didSetSheetAllowedDetentsOnController` to `YES` after setting detents for the first time and then ignore all incoming frames - including those with new height after content changed its height. Now, we remember frame height we received, and when we receive a new frame, we compare new height to …
> feat(iOS): make `fitToContents` sheet height react to dynamic content 

- ios/RNSFullWindowOverlay.mm
- ios/RNSScreen.mm
- ios/RNSScreenContainer.mm
- ios/RNSScreenStackHeaderConfig.mm
- ios/RNSScreenStackHeaderSubview.mm
Some pragmas were paired incorrectly (BEGIN & BEGIN instead of BEGIN & END) & for some reason, if there is whitespace 
between `RNS_IGNORE_SUPER_CALL_BEGIN` and first method below it, XCode won't include that method in method list (triggered by Ctrl+6), similarly 
"goto definition" won't work...
Fixed above :point_up:
N/A
> chore(iOS): fix XCode symbol discovery for methods surrounded with `RNS_IGNORE_SUPER_CALL_BEGIN`

- apps/src/tests/Test2714.tsx
- apps/src/tests/index.ts
- common/cpp/react/renderer/components/rnscreens/RNSScreenStackHeaderConfigComponentDescriptor.h
- common/cpp/react/renderer/components/rnscreens/RNSScreenStackHeaderConfigState.h
- common/cpp/react/renderer/components/rnscreens/RNSScreenStackHeaderSubviewComponentDescriptor.h
- ios/RNSScreenStackHeaderConfig.h
- ios/RNSScreenStackHeaderConfig.mm
- ios/RNSScreenStackHeaderSubview.h
- ios/RNSScreenStackHeaderSubview.mm
Regression most likely introduced in 4.5.0 by #2466.
Fixes #2714
Fixes #2815
Supersedes #2845
This is a ugly hack to workaround issue with dynamic content change.
When the size of this shadow node contents (children) change due to JS
update, e.g. new icon is added, if the size is set for the yogaNode
corresponding to this shadow node, the enforced size will be used
and the size won't be updated by Yoga to reflect the contents size
change -> host tree won't get layout metrics update -> we won't trigger native
layout -> the views in header will be positioned incorrectly.
> [!important]
> This PR handles iOS only, however there is **similar** issue on Android. The issue can be reproduced on the same test example. Android will be handled in separate PR.
In this approach I've settled with:
1. …
> fix(Fabric,iOS): header subviews do not support dynamic content changes

- common/cpp/react/renderer/components/rnscreens/RNSScreenStackHeaderSubviewComponentDescriptor.h
Fixes https://github.com/software-mansion/react-native-screens/issues/2714 on Android
Fixes https://github.com/software-mansion/react-native-screens/issues/2815 on Android
See #2905 for detailed description.
Removed call to `RNSScreenStaceaderSubviewShadowNode.setSize` in corresponding component descriptor.
It seems that we do not need to enforce node size from HostTree. Setting appropriate content offset is enough for pressables to function correctly (assuming that native layout **does not change size of any subview**). I currently can't come up with any scenario where this would happen. 
I've tested:
> fix(Fabric,Android): header subviews do not support dynamic content changes

- android/build.gradle
- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt
- apps/src/tests/Test2895.tsx
- apps/src/tests/index.ts
On API 36, formSheet that contains input with autoFocus would sometimes slide from the top. 
Even though `react-native-screens` used `com.google.android.material:material:1.6.1`, `InsetsAnimationCallback` (which is not present in `1.6.1`) is called (it probably comes from `com.google.android.material:material:1.12.0` dependency in `react-native-edge-to-edge`). This callback interferes with our formSheet entering/closing animations:
1. Values used to calculate start and end position in `InsetsAnimationCallback`'s `onPrepare` and `onStart` are usually incorrect. This has become a significant issue since API 36: for some reason, animation created in `ScreenStackFragment`'s `onCreateAnimator` is sometimes incorrecly accounted for in calculating `startTranslationY`. The value becomes negative …
> fix(Android): fix formSheet sliding from top when it contains input with autofocus

- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt
- android/src/main/java/com/swmansion/rnscreens/utils/EdgeToEdge.kt
- android/src/main/java/com/swmansion/rnscreens/utils/EdgeToEdgePackageDetector.kt
Deprecate native props and methods related to status/navigation bars that will be no longer relevant after edge-to-edge is enforced (they were deprecated already in this PR: https://github.com/software-mansion/react-native-screens/pull/2638).
- deprecate deprecate status/navigation bar edge to edge related props in native code
- add EdgeToEdge detection utility
- prevent adding `ScreenWindowTraits`' `windowInsetsListener` to `InsetsObserverProxy` if edge-to-edge is enabled
> feat(Android): deprecate status/navigation bar edge to edge related props in native code

- android/src/main/cpp/jni-adapter.cpp
- android/src/main/java/com/swmansion/rnscreens/ScreensModule.kt
Right now, when removing React Native instance in brownfield apps, the `ScreensModule` cpp side is kept in memory until the whole app is killed. This code removes global ref when invalidating the module too. It fixes memleaks e.g. in Expensify App.
You'd need brownfield app so no repro attached. Try remove and add RN instance to native android app a couple of times, then do a heap dump in AS and check for `ScreensModule` instances with 0 depth in its references.
> fix: remove global ref when invalidating module

- FabricExample/e2e/issuesTests/Test691.e2e.ts
- apps/src/tests/Test691.js
- apps/src/tests/index.ts
Check which example screens from issues/PRs can be used in e2e testing for tests `Test662, Test691` and implement them if possible for Fabric. 
Skipped because we can't check new animation in any meaningful way.
Test created, only on iOS (original issue was related to iOS modal behavior - on Android `presentation: 'modal'` screens are regular screens so their behavior differs). It checks if modal remains open after changing the tab.
- add `Test691` e2e test
- add testIDs to `Test691` test screen
CI
> test(e2e, Fabric): add e2e tests for issue/PR examples 662..691

- apps/Example.tsx
- apps/src/shared/Alert.tsx
- apps/src/shared/Dialog.tsx
- apps/src/shared/PressableWithFeedback.tsx
- apps/src/shared/SettingsInput.tsx
- apps/src/shared/SettingsMultiInput.tsx
- apps/src/shared/SettingsPicker.tsx
- apps/src/shared/SettingsSwitch.tsx
- apps/src/shared/Snack.tsx
- apps/src/shared/Square.tsx
- apps/src/shared/ThemedView.tsx
- apps/src/shared/styling/Colors.ts
- apps/src/shared/styling/adapter/react-navigation/index.ts
- apps/src/shared/styling/adapter/react-navigation/useColorPallette.tsx
Adding shared, reusable color values here. I get a bit frustrated when I have to comeup with colors each time I made an example 
& for some reason `ColorValue` does not have typing for color-literals. 
I've stolen the values from reanimated docs (they use swm color palette), thought it might look nicely & consistent.
I would recommend using these in any future examples.
:point_up:
N/A
> chore(example): add shared, reusable color values

- FabricExample/e2e/issuesTests/Test2926.e2e.ts
- apps/src/tests/Test2926.tsx
- apps/src/tests/index.ts
- ios/RNSScreenStackHeaderConfig.mm
Search bar on iOS would not disappear after setting `headerSearchBarOptions` to `undefined`. It seems like this issue was present [for some time now](https://github.com/software-mansion/react-native-screens/pull/758#issuecomment-852534970) but somehow it wasn't reported in a seperate issue.
- set `navItem.searchController` to `nil` if there is no `RNSScreenStackHeaderSubviewTypeSearchBar` anymore
- add `Test2926` test screen and e2e test
Open `Test2926` in Example app, try to hide the search bar.
> fix(iOS): allow to hide the search bar

- FabricExample/e2e/issuesTests/Test726.e2e.ts
- apps/src/tests/Test726.js
- apps/src/tests/index.ts
Check which example screens from issues/PRs can be used in e2e testing for tests `Test702, ..., Test726` and implement them if possible for Fabric. 
Skipped because we can't check animation in any meaningful way.
Skipped because we can't check font weight.
Skipped because the issue is still present (`transitionStart/End` events are not fired when leaving the screen due to a call from the JS side; the decision was that [this will not be fixed](https://github.com/software-mansion/react-native-screens/issues/713#issuecomment-732209901) if there is no important use case for it).
Test created, only on iOS (original issue was related to iOS). It checks if the app freezes after going back from screen with autofocus input. It is important to note that the issue was reopened with similar, but not …
> test(e2e, Fabric): add e2e tests for issue/PR examples 702..726

- android/src/main/java/com/swmansion/rnscreens/InsetsObserverProxy.kt
- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt
- android/src/main/java/com/swmansion/rnscreens/bottomsheet/SheetDelegate.kt
- android/src/main/java/com/swmansion/rnscreens/ext/FragmentExt.kt
Sometimes, formSheet that contains input with autoFocus would not account for the keyboard and would remain behind it. This is because `SheetDelegate` is set as a `OnApplyWindowInsetsListener` when fragment is resumed - this happens after finishing formSheet entering animations (animators impact fragment lifecycle). Sometimes, IME insets were applied before this handler was set. Now, we can use `WindowInsetsAnimationCallback` added in [this PR](https://github.com/software-mansion/react-native-screens/pull/2909). Its `onPrepare` method is called before `onApplyWindowInsets` therefore making it possible to set `OnApplyWindowInsetsListener` in time.
- change `insetsObserverProxy`'s `listeners` to `HashSet` (we might try to add the same listener multiple times)
- override `onPrepare` method …
> fix(Android): fix formSheet not adjusting for keyboard when it contains input with autofocus

- FabricExample/e2e/issuesTests/Test2543.e2e.ts
- apps/src/tests/Test2543.tsx
- apps/src/tests/index.ts
- ios/RNSScreen.mm
Changing detents on iOS form sheets would not work correctly if `sheetInitialDetent` was set to value other than `0`. For some reason, initial detent was set on **every** update instead of being set only once.
Fixes https://github.com/software-mansion/react-native-screens/issues/2543.
- add `_hasInitialDetentSet` flag and use it to determine whether to set initial detent
- add `Test2543` test screen and e2e test
| --- | --- |
| <video src="https://github.com/user-attachments/assets/626b4dc8-52ac-454d-a223-d311c0a7a08d" /> | <video src="https://github.com/user-attachments/assets/f7ca38ca-c0b5-4455-b04e-384621bfecbd" /> |
First example works on both videos, second one only after fix.
Run example app, open `Test2543`.
> fix(iOS): fix detents not changing if sheetInitialDetent > 0

- android/src/main/java/com/swmansion/rnscreens/InsetsObserver.kt
- android/src/main/java/com/swmansion/rnscreens/Screen.kt
Review notes for #2938. Please note that I've described each change in commit details.
- **refactor insets managment for sheets**
- **Update android/src/main/java/com/swmansion/rnscreens/InsetsObserver.kt**
- **Remove secondary constructor & add context as first parameter**
- **Update callsite**
- **Make use of ctor param instead of introducing additional variable**
- **Rename systemListener -> externalListener**
- **Add a comment explaining semantics of `Screen.setOnApplyWindowInsetsListener`**
- **Renmae setOnApplyWindowListener -> setExternalOnApplyWindowInsetsListener**
- **Rename rollingInsets -> currentInsets & assert nullability**
- **Add comment explaining what is being returned there**
> review of 2938

- apps/src/tests/Test2949.tsx
- apps/src/tests/index.ts
- src/components/helpers/edge-to-edge.tsx
Fixes #2948
Fixes an issue where system bar styles set using `SystemBars.setStyle` function from `react-native-edge-to-edge` would be overridden by default values set in `react-native-screens`. Those should only work when we define system bar styles via screen options but in https://github.com/software-mansion/react-native-screens/pull/2464 that integrated `react-native-edge-to-edge` with `react-native-screens`, we would always set `statusBarTranslucent` and `navigationBarTranslucent` props when in edge to edge ([code here](https://github.com/software-mansion/react-native-screens/pull/2464/files#diff-d51c072177510e603797455a4c3c14a049d0cfdbd39132fb53a6c187de8b7789R30-R31)), which would set `didSetStatusBarAppearance`/`didSetNavigationBarAppearance` and in result, make `screens` use …
> fix(Android): remove setting system bar translucent props from JS if in edge to edge

- FabricExample/e2e/issuesTests/Test791.e2e.ts
- apps/src/tests/Test791.tsx
- apps/src/tests/index.ts
Check which example screens from issues/PRs can be used in e2e testing for tests `Test761, ..., Test791` and implement them if possible for Fabric. 
Skipped because we can't check animation.
Skipped because we can't check animation.
Skipped because we can't use native swipe back gesture with Detox.
Test created, only on iOS (original issue was about crashes on iOS). It tests if the app crashes when you push multiple screens quickly behind modal.
- add `Test791` e2e test
- modify`Test791` test screen (add explicit `presentation: 'card'` for push screen, add testIDs)
CI
> test(e2e, Fabric): add e2e tests for issue/PR examples 761..791

- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerDelegate.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerInterface.java
- ios/RNSScreen.h
- ios/RNSScreen.mm
- ios/RNSScreenStack.h
- ios/RNSScreenStack.mm
- src/components/Screen.tsx
- src/components/ScreenStackItem.tsx
- src/fabric/ModalScreenNativeComponent.ts
- src/fabric/ScreenNativeComponent.ts
- src/types.tsx
Add support for `screenId` prop on native side. At the moment we use this value only in JS code.
It was brought to my attention, however, that other libs that wanna integrate might want that
to be exposed also on native side. 
Added `screenId` prop & exposed it on both platforms.
Any example & add a breakpoint at setter method.
> feat: add support for `screenId` prop allowing for native screen recognition

- apps/src/tests/Test2125.tsx
- apps/src/tests/index.ts
- ios/RNSScreen.mm
When trying to use a transparent full-screen `Modal` from `react-native` after attempting to close a screen that uses `usePreventRemove` hook, sometimes the `Modal` would not attatch to `rootViewController` but to `RNSScreen` - this would cause a visual bug and prevent any interaction with the modal.
This is connected to how we handle `preventNativeDismiss`, introduced in https://github.com/software-mansion/react-native-screens/pull/1773. We create an `interactionController` for the transition and after a small delay, we asynchronously dispatch a cancellation of the transition. 
When `react-native`'s Modal tries to present itself, the host component calls `presentViewController` on its controller (`RNSScreen`). Normally, `RNSScreen` forwards the request up to its ancestor because …
> fix(iOS): handle presenting custom modal when attempting to exit screen with preventNativeDismiss 

- apps/src/tests/TestSplitView/SplitViewBaseApp.tsx
- ios/RNSEnums.h
- ios/conversion/RNSConversions-SplitView.mm
- ios/conversion/RNSConversions.h
- ios/gamma/split-view/RNSSplitViewHostComponentView.h
- ios/gamma/split-view/RNSSplitViewHostComponentView.mm
- src/components/gamma/SplitViewHost.tsx
- src/fabric/gamma/SplitViewHostNativeComponent.ts
Closes https://github.com/software-mansion/react-native-screens-labs/issues/223
This property specifies the display mode which will be preferred to use in SplitView, when the layout requirements are met.
Possible DisplayMode values:
- `secondaryOnly` - only the secondary column is displayed
- `oneBesideSecondary` - a sidebar is displayed side-by-side with the secondary column
- `twoBesideSecondary` - two sidebars are displayed side-by-side with the secondary column
- `oneOverSecondary` - a one sidebar is displayed over the secondary column
- `twoOverSecondary` - two sidebars are displayed over the secondary column
- `twoDisplaceSecondary` - two sidebars are displacind the secondary column, moving it partially offscreen
- `automatic` - leaving the choice to OS (default)
- Added prop …
> feat(iOS, SplitView): Add support for preferredDisplayMode prop

- apps/src/tests/TestSplitView/SplitViewBaseApp.tsx
- ios/gamma/split-view/RNSSplitViewHostComponentView.h
- ios/gamma/split-view/RNSSplitViewHostComponentView.mm
- src/components/gamma/SplitViewHost.tsx
- src/fabric/gamma/SplitViewHostNativeComponent.ts
SplitView installs its own GestureRecognizer for changing the display mode. There's a method `presentsWithGesture` which can disable this GestureRecognizer. In this PR I am adding a setter for this API from the JS native component.
- Updated example
- Added native setter
- Updated JS native component definition
Updated `SplitViewBaseApp`
https://github.com/user-attachments/assets/a5cf2bd3-0183-4258-89bf-34c84b7ed589
Closes https://github.com/software-mansion/react-native-screens-labs/issues/230
> feat(iOS, SplitView): Add support for presentsWithGesture prop

- ios/gamma/split-view/RNSSplitViewHostComponentView.h
- ios/gamma/split-view/RNSSplitViewHostComponentView.mm
- src/components/gamma/SplitViewHost.tsx
- src/fabric/gamma/SplitViewHostNativeComponent.ts
Closes https://github.com/software-mansion/react-native-screens-labs/issues/231 
Adding setter for showsSecondaryOnlyButton which adds native button for toggling display mode to `secondaryOnly`.
- In the pure native app, when I wanted to change this value dynamically, update for button visibility was applied after another interaction, like swiping one of columns.
- Added native setter
- Updated native component in JS
- Updated app
Added this prop to `SplitViewBaseApp`
> feat(iOS, SplitView): Add support for showsSecondaryOnlyButton

- android/src/main/java/com/swmansion/rnscreens/gamma/tabs/TabScreen.kt
- android/src/main/java/com/swmansion/rnscreens/gamma/tabs/TabScreenViewManager.kt
- android/src/main/java/com/swmansion/rnscreens/gamma/tabs/TabsHost.kt
- apps/src/tests/TestBottomTabs/index.tsx
- src/components/BottomTabsScreen.tsx
- src/fabric/BottomTabsScreenNativeComponent.ts
This PR adds visibility prop for android badge. It changes the logic in a way that it required to add `tabBarItemBadgeVisible: true` alongside the number. The idea here is: this way we can allow to show small badges that don't have value (see below). 
See `TestBottomTabs/index.tsx`
> feat(Android, Tabs): add badge visibility prop for android bottom navigation

- ios/bottom-tabs/RNSBottomTabsScreenComponentView.mm
Fixes missing badge values on iOS Paper.
Closes https://github.com/software-mansion/react-native-screens-labs/issues/279.
- update badge value in tab bar item when setting prop
Run TestBottomTabs and verify if badges are visible.
> fix(iOS, Paper, Tabs): fix badge value on iOS Paper

- ios/bottom-tabs/RNSBottomTabsScreenComponentView.mm
Fixes https://github.com/software-mansion/react-native-screens-labs/issues/213.
Moved from https://github.com/software-mansion/react-native-screens-labs/pull/253.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/dedd187a-fe56-47bd-be5d-6d7aceaba199" /> | <video src="https://github.com/user-attachments/assets/c1791562-dd33-49bd-9902-73ab217738ac" /> |
In order to avoid the glitch, we set background color of tab screens to white. In the future, we need to find a better workaround that will account for color of the content.
> [!IMPORTANT]
> Please note that there is another visual glitch with the background from the first tab remaining visible behing the tab bar while transition is ongoing. This also happens on native SwiftUI iOS 26 beta 3 app so …
> fix(iOS, Tabs): add temporary workaround to avoid UIScrollEdgeEffect glitch on iOS 26

- package.json
- yarn.lock
This PR removes outdated clang-format npm package to make git hooks and formatting commands use native clang-format. The npm package is outdated and doesn't work on Apple Silicon Macs.
Should we update the pipeline, and/or automate installation of some alternatives?
Any comments are welcome.
> chore(CI): Remove clang-format

- apps/src/tests/TestSplitView/SplitViewBaseApp.tsx
- ios/gamma/split-view/RNSSplitViewAppearanceCoordinator.mm
- ios/gamma/split-view/RNSSplitViewHostComponentView.h
- ios/gamma/split-view/RNSSplitViewHostComponentView.mm
- src/components/gamma/SplitViewScreen.tsx
- src/fabric/gamma/SplitViewHostNativeComponent.ts
For all primary and supplementary columns (but from iOS 26 - also for secondary and inspector), we can manage their widths, passing width in px for following APIs:
- preferred[COLUMN]ColumnWidth
- maximum[COLUMN]ColumnWidth
- minimum[COLUMN]ColumnWidth
Closes https://github.com/software-mansion/react-native-screens-labs/issues/234 
- defined JS types
- added native setters
- updated app
Example with primary and supplementary columns with fixed preferred width set to 250
Updated demo app
> feat(iOS, SplitView): Add support for setting column widths

- android/src/main/java/com/swmansion/rnscreens/gamma/tabs/TabsHostViewManager.kt
- android/src/paper/java/com/facebook/react/viewmanagers/RNSBottomTabsManagerDelegate.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSBottomTabsManagerInterface.java
- apps/src/shared/gamma/containers/bottom-tabs/BottomTabsContainer.tsx
- ios/RNSEnums.h
- ios/bottom-tabs/RNSBottomTabsHostComponentView.h
- ios/bottom-tabs/RNSBottomTabsHostComponentView.mm
- ios/conversion/RNSConversions-BottomTabs.mm
- ios/conversion/RNSConversions.h
- src/components/BottomTabs.tsx
- src/components/BottomTabsScreen.tsx
- src/fabric/BottomTabsNativeComponent.ts
Adds support for `tabBarMinimizeBehavior`.
Closes https://github.com/software-mansion/react-native-screens-labs/issues/178.
Moved from https://github.com/software-mansion/react-native-screens-labs/pull/214.
- add support for `tabBarMinimizeBehavior`
Add `tabBarMinimizeBehavior` for `BottomTabs` component, e.g. `onScrollDown` and check behavior with ScrollView.
> feat(iOS, Tabs): add support for tabBarMinimizeBehavior

- android/src/main/java/com/swmansion/rnscreens/gamma/tabs/TabsHost.kt
I find it notoriously hard to read, therefore decided to refactor it a
bit.
Just put the decision, whether to detach previous tab into the transaction configuration block.
Bottom tabs implementation `TestBottomTabs` should work exactly the same.
> refactor(Android): rewrite tab update logic

- ios/RNSEnums.h
- ios/bottom-tabs/RCTConvert+RNSBottomTabs.mm
- ios/bottom-tabs/RNSBottomTabsHostComponentView.mm
- ios/bottom-tabs/RNSBottomTabsHostComponentViewManager.mm
- ios/conversion/RNSConversions-BottomTabs.mm
- ios/conversion/RNSConversions.h
Adds support for `tabBarMinimizeBehavior` on Paper.
Closes https://github.com/software-mansion/react-native-screens-labs/issues/308.
- add `RNSTabBarMinimizeBehavior` for Paper to allow the same prop setting logic as Fabric
- add conversions
- export property
Run TestBottomTabs on Paper, open Tab3, scroll down. On iOS 26, tab bar should hide. On iOS versions prior to 26, there should be a warning in the logs.
> feat(iOS, Paper, Tabs): add support for tabBarMinimizeBehavior on Paper

- android/src/main/java/com/swmansion/rnscreens/gamma/tabs/TabScreenViewManager.kt
- android/src/main/java/com/swmansion/rnscreens/gamma/tabs/TabsHostViewManager.kt
Fixes https://github.com/software-mansion/react-native-screens-labs/issues/287
This PR fixes not working styles by adding missing paper annotations
|Fabric|Paper|
|-|-|
|<video src="https://github.com/user-attachments/assets/b6790b07-f1dd-4262-850f-20857d5be5a9"/>|<video src="https://github.com/user-attachments/assets/be25c370-de26-4524-9a28-571a50d886fe"/>| 
See `TestBottomTabs/index.tsx`
> fix(Android, Tabs): add missing paper annotations 

- ios/gamma/split-view/RNSSplitViewAppearanceCoordinator.mm
- ios/gamma/split-view/RNSSplitViewHostComponentView.h
- ios/gamma/split-view/RNSSplitViewHostComponentView.mm
- src/fabric/gamma/SplitViewHostNativeComponent.ts
In this PR I'm covering UISplitViewController APIs `preferred[ColumnType]ColumnWidthFraction`. As we discussed internally, we should try to cover it as the same prop for both fraction and points. This is slightly different from the Apple approach which has both versions separated, maintaining two props: `preferred[ColumnType]ColumnWidth` and `preferred[ColumnType]ColumnWidthFraction`.
In our case, if the value passed is between 0 and 1 - we're interpreting it as a fraction and for any value greater than 1, we're using points.
Closes: https://github.com/software-mansion/react-native-screens-labs/issues/296 
- Updated `preferredColumnWidth` definitions to cover floats.
- Updated appearance coordinator to cover fractions.
- Updated prop definition in the host component. …
> feat(iOS, SplitView): Add support for fraction for columns widths

- ios/RCTConvert+RNScreens.mm
- ios/RNSConvert.h
- ios/RNSConvert.mm
- ios/RNSEnums.h
- ios/RNSScreenStackHeaderConfig.mm
- ios/bottom-tabs/RNSBottomTabsHostComponentView.h
- ios/bottom-tabs/RNSBottomTabsHostComponentView.mm
- ios/bottom-tabs/RNSBottomTabsHostComponentViewManager.mm
- ios/bottom-tabs/RNSBottomTabsScreenComponentView.h
- ios/bottom-tabs/RNSBottomTabsScreenComponentView.mm
- ios/bottom-tabs/RNSBottomTabsScreenComponentViewManager.mm
- ios/bottom-tabs/RNSTabBarAppearanceCoordinator.mm
- ios/bottom-tabs/RNSTabBarAppearanceProvider.h
- ios/conversion/RNSConversions-BottomTabs.mm
- ios/conversion/RNSConversions.h
- src/fabric/BottomTabsNativeComponent.ts
- src/fabric/BottomTabsScreenNativeComponent.ts
Adds support for `default` blur effect value.
Previously, `tabBarBlurEffect: 'none'` would enable default UIKit blur effect but this made disabling blur effect impossible. That's why we decided to add separate option for default value. Now, `none` disables the blur completely.
I decided to create new enum for blur styles instead of using previous one in order not to introduce any breaking changes for old stack implementation. When it gets removed, new enum can become the only one.
> [!IMPORTANT]
> UIKit's API allows setting appearance for host and tab bar items. This however seems problematic - deciding which and how properties are inherited. We think that this should be handled by the users of the library and `react-native-screens` should expose common appearance props only via screen …
> feat(iOS, Tabs): add support for `default` blur effect value

- common/cpp/react/renderer/components/rnscreens/RNSScreenShadowNode.cpp
- ios/RNSScreen.mm
When upgrading `react-native-screens` to `4.13.x` the app starts to output debug logs from `react-native-screens`:
```
[App.debug.dylib] ScreenView [0] setFrame: {{0, 0}, {0, 0}}
[App.debug.dylib] ScreenView [102] setBounds: {{0, 0}, {440, 956}}
[App.debug.dylib] ScreenView [102] setFrame: {{0, 0}, {440, 956}}
```
They seem to have been introduces in this change: https://github.com/software-mansion/react-native-screens/commit/896c2c6ef83941afb9d1146d5c7e510623e5fc64
This PR fixes #3066 🥳 
- Removed NSLog statements from `iOS/RNSScreen.mm`
- Removed NSLog statements from `ios/bottom-tabs/*`
It seems to just be NSlog-statements left in the code by mistake. Reply if you need a reproduction app.
> fix: Remove newly added logs from user land

- ios/bottom-tabs/RNSBottomTabsHostComponentView.h
- ios/bottom-tabs/RNSBottomTabsHostComponentView.mm
Exposing `UITabBarController`.
Note: this change means that we need further changes described here: https://github.com/software-mansion/react-native-screens-labs/issues/156
- Exposing `UITabBarController`.
Tested that controller is publicly accessible.
> feat(iOS, Tabs): Expose RNSTabBarController

- apps/Example.tsx
Currently, we write tests as issue reproductions which we name Test<issue number> - one for each issue, and more general tests/examples which we name as Test<descriptive name>. In order to have the former sorted correctly, we need to stick to the scheme and not have anything non-digit after issue number.
We can change the sorting logic to make it possible to define Test123_1 and Test123_2.
Implementation of sort function that understands names like Test123_1
> feat(Example): Fix sorting for multiple tests with same issue number

- android/src/main/java/com/swmansion/rnscreens/gamma/tabs/TabsHostViewManager.kt
- src/components/bottom-tabs/BottomTabs.types.ts
- src/components/bottom-tabs/BottomTabsScreen.types.ts
Continuation of https://github.com/software-mansion/react-native-screens/pull/3048
Adds docs for props in BottomTabs and BottomTabsScreen for Android.
Hover over `apps/src/shared/gamma/containers/bottom-tabs/BottomTabsContainer.tsx` to see the results
> chore(Android, Tabs): document props for android

- ios/bottom-tabs/RNSTabBarAppearanceCoordinator.mm
Fixes https://github.com/software-mansion/react-native-screens-labs/issues/323.
Before this fix, you couldn't modify font if you did not change size as well.
- separate color and other font attributes to different if statements
- check all relevant font props in condition
- change nullability of text attributes
- change check (count > 0 instead of nil-check)
Run TestBottomTabs, change font props other than font size. Props should apply to the text.
> fix(iOS, Tabs): fix condition for applying text attributes in Appearance Coordinator

- android/src/main/java/com/swmansion/rnscreens/Screen.kt
- android/src/main/java/com/swmansion/rnscreens/ScreenContainer.kt
- android/src/main/java/com/swmansion/rnscreens/gamma/common/FragmentProviding.kt
- android/src/main/java/com/swmansion/rnscreens/gamma/helpers/FragmentManagerHelper.kt
- android/src/main/java/com/swmansion/rnscreens/gamma/tabs/TabScreen.kt
Currently only nesting a stack inside tabs is supported & not the other way around. 
This PR changes that. 
`Screen` now implements `FragmentProviding`, which allows the `TabHost` to use it
as a source for child fragment manager.
<details>
<summary>Code example</summary>
```javascript
import React from 'react';
import { Screen, ScreenStack, enableFreeze } from 'react-native-screens';
import ConfigWrapperContext, {
type Configuration,
DEFAULT_GLOBAL_CONFIGURATION,
} from '../../shared/gamma/containers/bottom-tabs/ConfigWrapperContext';
import {
BottomTabsContainer,
type TabConfiguration,
} from '../../shared/gamma/containers/bottom-tabs/BottomTabsContainer';
import { Tab1, Tab2, Tab3, Tab4 } from './tabs';
import Colors from '../../shared/styling/Colors';
import { StyleSheet } from …
```
> fix(Android,Tabs): allow for nesting tabs inside v4 stack

- ios/bottom-tabs/RNSBottomTabsHostComponentView.mm
- ios/bottom-tabs/RNSBottomTabsScreenComponentView.h
- ios/bottom-tabs/RNSBottomTabsScreenComponentView.mm
Closes: https://github.com/software-mansion/react-native-screens-labs/issues/156 (the task was originally created for SplitView, but I extended it to cover BottomTabs - if you feel that I should attach a separate task - please leave it as a comment)
Problem:
- Controller has a strong reference to an associated component via `.view` property.
- In our case, Component keeps a strong reference to the controller.
- This creates a retain cycle, which we're not breaking anywhere at the moment.
Solution:
BottomTabs host keeps references to all subviews of type BottomTabsScreen all the time (tabs might be hidden, but they won't disappear). It means that we can consider Host as an owner of the BottomTabsScreens' lifecycles. If the host is about to be unmounted from the view hierarchy, we can …
> fix(iOS, Tabs): Break retain cycle for bottom tabs screen

- src/components/bottom-tabs/BottomTabsScreen.types.ts
Add missing `tabBarItemBadgeBackgroundColor` docs for Android.
> docs(Tabs): add tabBarItemBadgeBackgroundColor prop docs for Android

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- RNScreens.podspec
I need to use sources that are hidden inside the gamma directory in the other components, like the old native stack. In this PR I'm adding a compilation flag which may help in hiding some symbols when gamma is disabled.
- Added `RNS_GAMMA_ENABLED` compilation flag
- Updated Podfiles
Compiled FabricExample and Example with changes from: https://github.com/software-mansion/react-native-screens/pull/3097
> chore(iOS): Add compilation flag for gamma sources

- android/src/main/jni/CMakeLists.txt
The function has been introduced with RN 0.80 and later modified in
https://github.com/facebook/react-native/commit/c059ae1b77.
The #c059ae1b77 added RN_SERIALIZABLE_STATE compile time definition,
which helps to resolve an ridiculous crash / hang we had. To give some
context - the crash occured in codegened C++ code in
`RNSScreenProps::~RNSScreenProps` (yes, this is a compiler generated
default dtor) or in other dtors, depending on exact timing. It is still
unknown exactly what was the error mechanism, but most likely due to
some timing / concurrency related issues dtor attempted to free some
memory that was no longer mapped to a process or something. Anyway,
setting this flag resolves the problem.
Additionally, this is also a way-to-go in terms of setting compile
options required by RN …
> fix(Android): prevent frequent crash in `RNSScreenProps::~RNSScreenProps` by setting `RN_SERIALIZABLE_STATE` compile flag

- android/build.gradle
- android/src/main/java/com/swmansion/rnscreens/gamma/helpers/ViewIdHelpers.kt
- android/src/main/java/com/swmansion/rnscreens/gamma/tabs/TabsHost.kt
- android/src/paper/java/com/facebook/react/viewmanagers/RNSSearchBarManagerDelegate.java
`TabsHost.id` collied with `ReactSurfaceView.id`, because RN 0.81
started to number the root views from 1, instead of 11 as it was before.
This caused issues, becuase `FragmentTransaction.add(containerViewId:
Int, ...)` requires us to pass the `containerViewId`, which it then uses
to find a view in hierarchy with that id & it mounts added fragment's
view there. If collision occurs, Android Framework mounts the fragment
directly under `ReactSurfaceView` instead of our `TabsHost`.
Proposed workaround does the following:
1. ~it passes int value of react native minor version down from gradle
script to build config, so that it is accessible in platform code.
AFAIK there is no dedicated API as of 0.81 for this, therefore we
need a workaround.~ We start counting from 3, it should work no matter …
> fix(Android): prevent view tag of `TabsHost` colliding with `ReactSurfaceView`

- ios/bottom-tabs/RNSTabBarControllerDelegate.mm
- ios/bottom-tabs/RNSTabsScreenViewController.mm
**This only works for not-controlled mode**
An error is thrown right now when user clicks on the more tab (It shows when more then 5 tabs are added)
1. Handle UIMoreNavigationController (private API). We can check for it using `moreNavigationController` from `UITabBarController`
2. Hide the NavigationBar from more controller, so it does not break designs in the tab screens
This is a recording from integration into `expo-router`
https://github.com/user-attachments/assets/ad0fa8e0-53ea-4a49-9ff7-b90bad45a5c7
Add this code to `apps/src/tests/TestBottomTabs/index.tsx`. Click on the more tab.
```tsx
{
tabScreenProps: {
tabKey: 'Tab5',
icon: {
sfSymbolName: '0.circle',
},
selectedIcon: {
sfSymbolName: '0.circle.fill',
},
iconResourceName: 'sym_action_chat', // Android specific
title: 'Tab5', …
```
> fix(iOS, Tabs): Fix more controller handling

- common/cpp/react/renderer/components/rnscreens/RNSScreenShadowNode.cpp
- common/cpp/react/renderer/components/rnscreens/RNSScreenStackHeaderSubviewState.h
- common/cpp/react/renderer/components/rnscreens/RNSScreenState.h
- ios/RNSScreen.mm
Follow-up to https://github.com/software-mansion/react-native-screens/pull/3134.
It turns out that different versions of `clang-format` produce different output. Maybe we should have a look at our formatting pipeline.
- formatting via `yarn format` with `clang-format@20.1.8`
N/A
> chore: run formatter with updated `clang-format`

- ios/RNSScreen.mm
Removes manual gesture cancel for modal dismiss on Fabric.
Fixes https://github.com/software-mansion/react-native-screens-labs/issues/360.
The logic for cancelling gesture when modal will be dismissed has been added in https://github.com/software-mansion/react-native-screens/pull/1485. 
On iOS 26 + Fabric, this code causes a crash (gesture update comes after resetting `_activeTouches` array, inconsistency is detected).
The logic seems redundant now as the case described in the comment works without it on Fabric. I suspect this might've been patched in [this commit in `react-native`](https://github.com/facebook/react-native/commit/379d9d4918886e002d70dd30fff29f8e6a8cf48f).
On Paper, it is still necesssary. During testing, I noticed another bug - you can "catch" another pressable during …
> fix(iOS, Stack v4): crash on modal dismiss gesture with Pressable

- ios/RNSScreenStack.mm
(Duplicated in code comment)
iOS 26 introduces new gesture recognizer which replaces our RNSPanGestureRecognizer. The problem is that we are not able to handle it here for various reasons:
* the new recognizer comes with its own delegate and our current approach is to wire all recognizers to RNSScreenStackView; to be 100% sure we don't break the logic, we would have to decorate its delegate and call it after our code, which would break other recognizers that the stack view is the delegate for
* when RNSScreenStackView.setupGestureHandler method is called, the recognizer hasn't been loaded yet and there is no other place to configure in a not "hacky" way
* the official docs warn us to not use it for anything other than "setting up failure requirements with it"
* we expose …
> fix(iOS): Disable interactiveContentPopGestureRecognizer

- src/fabric/FullWindowOverlayNativeComponent.ts
- src/fabric/ModalScreenNativeComponent.ts
- src/fabric/ScreenContainerNativeComponent.ts
- src/fabric/ScreenContentWrapperNativeComponent.ts
- src/fabric/ScreenFooterNativeComponent.ts
- src/fabric/ScreenNativeComponent.ts
- src/fabric/ScreenNavigationContainerNativeComponent.ts
- src/fabric/ScreenStackHeaderConfigNativeComponent.ts
- src/fabric/ScreenStackHeaderSubviewNativeComponent.ts
- src/fabric/ScreenStackNativeComponent.ts
- src/fabric/bottom-tabs/BottomTabsNativeComponent.ts
- src/fabric/bottom-tabs/BottomTabsScreenNativeComponent.ts
- src/fabric/gamma/ScreenStackHostNativeComponent.ts
- src/fabric/gamma/SplitViewHostNativeComponent.ts
- src/fabric/gamma/SplitViewScreenNativeComponent.ts
- src/fabric/gamma/StackScreenNativeComponent.ts
After running `yarn lint-js` I noticed that deep imports are replaced. Related to: https://reactnative.dev/blog/2025/06/12/react-native-0.80#javascript-deep-imports-deprecation  
- Updated imports after running linter
N/A
> chore: Update imports after 0.81 upgrade

- android/build.gradle
- android/src/main/java/com/swmansion/rnscreens/gamma/tabs/TabScreenViewManager.kt
- android/src/paper/java/com/facebook/react/viewmanagers/RNSBottomTabsScreenManagerDelegate.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSBottomTabsScreenManagerInterface.java
- apps/assets/svg/cart.svg
- apps/src/tests/TestBottomTabs/index.tsx
- src/components/bottom-tabs/BottomTabsScreen.tsx
- src/components/bottom-tabs/BottomTabsScreen.types.ts
- src/fabric/bottom-tabs/BottomTabsScreenNativeComponent.ts
Adding a basic support for loading bottom-tabs icon from assets. This provides an alternative way to `iconResourceName`  for setting icon for the specific tab.
- Adding `coil`: https://coil-kt.github.io/coil/ - a library that handles image loading.
- Adding basic ImageRequest - ImageBuilder integration
- Exposing a prop for setting icon from JS sources.
Adding `iconResource` prop to `TestBottomTabs`.
> feat(android, Tabs): Loading bottom tab icons from external source

- apps/App.tsx
- apps/src/tests/TestBottomTabs/index.tsx
- ios/bottom-tabs/RNSBottomTabsScreenComponentView.mm
- ios/bottom-tabs/RNSTabBarAppearanceCoordinator.mm
This PR addresses some problems related to `systemItem`:
1. on startup, tab bar item with `systemItem` but without custom icon would not show the default icon (it was overriden by nil SFSymbol),
2. when using custom icon with `systemItem` and then removing the custom icon, the default icon for `systemItem` would not be restored,
3. if badge value was updated as the same time as `systemItem` was set, the value of the badge would not be updated (due to badge value being updated _before_ `systemItem`).
Fixes https://github.com/software-mansion/react-native-screens-labs/issues/380.
- move updates to `tabBarItem` to separate method after setting props
https://github.com/user-attachments/assets/d5b197d0-d29c-4587-8cfa-5c9ed96734e6
https://github.com/user-attachments/assets/96c71b0b-6c89-4677-a72 …
> fix(iOS, Tabs): refactor setting systemItem

- ios/gamma/split-view/RNSSplitViewScreenComponentView.mm
- ios/gamma/split-view/RNSSplitViewScreenController.swift
- ios/gamma/split-view/RNSSplitViewScreenShadowStateProxy.h
- ios/gamma/split-view/RNSSplitViewScreenShadowStateProxy.mm
Retrospective review for #3073.
* moved all the state related to view size transitioning do dedicated file-private type `ViewSizeTransitionState`,
* renamed `isTransitionInProgress -> isViewSizeTransitionInProgress`,
* renamed `stopAnimation` -> `cleanupViewSizeTransitionState`,
* removed `applyTransitioningShadowState(...)` & `applyStaticShadowStateRelativeToAncestor(...)` methods & moved the appropriate logic to shadow state proxy. 
See #3073
> refactor: review of #3073 - rename few methods, move update logic to shadow state proxy

- android/src/paper/java/com/facebook/react/viewmanagers/RNSSearchBarManagerDelegate.java
- guides/GUIDE_FOR_LIBRARY_AUTHORS.md
- ios/RNSSearchBar.mm
- src/fabric/SearchBarNativeComponent.ts
Fixes default values for `obscureBackground` and `hideNavigationBar` props in `RNSSearchBar`.
Even though that `react-navigation`'s docs state that `obscureBackground`'s default is `true`, this hasn't been the case. On both architectures, setter for the prop would not run (on Fabric, due to `false` being the default value for boolean; on Paper due to not running the setter if prop was `undefined`), resulting in native behavior:
```obj-c
/* On iOS, default is NO for apps linked on iOS 15.0 and later, YES otherwise.
On tvOS, default is NO when contained in UISearchContainerViewController, YES otherwise.
*/
@property (nonatomic, assign) BOOL obscuresBackgroundDuringPresentation API_AVAILABLE(ios(9.1));
```
Unfortunately, if we want to use `bool` for this prop, we need to decide which option …
> fix(iOS, Stack v4): ensure consistent defaults for `obscureBackground` and `hideNavigationBar`

- ios/RNSEnums.h
- ios/RNSScreen.mm
- ios/RNSScreenStackHeaderConfig.mm
- ios/RNSSearchBar.mm
- ios/utils/RNSBackBarButtonItem.mm
Removes outdated runtime SDK version checks + `API_AVAILABLE` macro usages for iOS < 15.1.
Closes https://github.com/software-mansion/react-native-screens-labs/issues/392.
- remove outdated usages of `@available`
- remove outdated usages of `API_AVAILABLE`
Verify that project builds correctly.
> chore(iOS): remove outdated SDK version checks (iOS < 15.1)

- ios/RNSScreenStackHeaderConfig.mm
Removes workaround introduced in https://github.com/software-mansion/react-native-screens/pull/3111.
Unfortunately, not only it doesn't fix all bugs related to the issue (e.g. https://github.com/software-mansion/react-native-screens-labs/issues/408) but also introduces new one as well (ScrollView not adapting to smaller height).
We also want to keep `ContentWrapper` in the same size as the content of the screen in order to correctly handle `fitToContents` in formSheets.
That's why we decided to remove the workaround, even though the bug with `edgesForExtendedLayout` hasn't been fixed yet (iOS 26 beta 6).
Current workaround is to use `react-native-safe-area-context` library. Wrap your screen's content in:
```tsx
<SafeAreaProvider>
<SafeAreaView edges={['top']}>
{/* content */} …
```
> fix(iOS 26, Stack v4): remove workaround for content under header in modal

- ios/RNSScreenStack.h
- ios/RNSScreenStack.mm
- ios/bridging/Swift-Bridging.h
- ios/gamma/split-view/RNSSplitViewScreenComponentView.h
- ios/gamma/split-view/RNSSplitViewScreenComponentView.mm
- ios/gamma/split-view/RNSSplitViewScreenController.swift
- ios/gamma/split-view/compat/RNSFrameCorrectionProvider.h
- ios/gamma/split-view/compat/RNSFrameCorrector.mm
Retrospective review of #3097
- **Give register & unregister functions more descriptive names**
* -[RNSSplitViewScreenComponentView registerForFrameUpdates:] -> -[RNSSplitViewScreenComponentView registerForFrameCorrection:]
* -[RNSSplitViewScreenComponentView unregisterFromFrameUpdates:] -> -[RNSSplitViewScreenComponentView unregisterFromFrameCorrection:]
I think this has more sense, as this isn't a regular frame update but
rather a correction related to `FrameCORRECTOR` &
`FrameCORRECTIONProvider`.
- **Add missing stars in multiline comment**
- **Refactor the logic according to review**
* Make `RNSSplitViewScreenComponentView` implement
`RNSFrameCorrectionProvider`, as it does provide the correct frame for
the navigation controller,
* update method signatures in …
> refactor: review 3097 - make split screen controller & component the frame correction provider

- .github/workflows/npm-screens-publish-nightly.yml
Recently npm enabled an option to use OIDC for publishing package artifacts from Github Actions: https://github.blog/changelog/2025-07-31-npm-trusted-publishing-with-oidc-is-generally-available/
This PR follows the configuration instructions, namely:
1) We add "permissions" for "id-token" which permits the action to retrieve and temporarily store the OIDC token
2) We update npm version to latest in order to use a version that supports OIDC
3) We delete the env variable for the NPM access token we used before. Now the token is provided by OIDC mechanism
4) We're keeping provenance flag for NPM publish despite the fact it is forced when OIDC is enabled
The remaining part of the configuration is already setup on the NPM site and we should expect this workflow to "just work" after the …
> chore: Configure OIDC for nightly builds

- experimental/package.json
- package.json
Issue: https://github.com/software-mansion/react-native-screens-labs/issues/443
Currently, we "publish" our experimental APIs through main `index` file.
We just annotate them with [appropriate comments], counting that people will notice. 
Example: [ `BottomTabs` component definition ](https://github.com/software-mansion/react-native-screens/blob/86b8fefc23637493ae76becea480c5f2eed81de2/src/components/bottom-tabs/BottomTabs.tsx#L19-L22)
Example: [ `BottomTabs` component reexport in `index` ](https://github.com/software-mansion/react-native-screens/blob/86b8fefc23637493ae76becea480c5f2eed81de2/src/index.tsx#L62-L65)
This is a poor solution & we should do at least a bit better. 
Create `react-native-screens/experimental` package, just as there is `react-native-screens/private`,
and export …
> chore: create `react-native-screens/experimental` submodule

- android/src/main/java/com/swmansion/rnscreens/gamma/tabs/TabsHostAppearanceApplicator.kt
Fixes tab bar item label flashing on tab change when in `labeled` `tabBarItemLabelVisibilityMode`.
Closes https://github.com/software-mansion/react-native-screens-labs/issues/481.
Setting `title/icon` causes the menu item to refresh. In `MenuItemImpl`, we see `onItemsChanged` callback being run:
```java
@Override
public MenuItem setTitle(CharSequence title) {
mTitle = title;
mMenu.onItemsChanged(false); // <--
if (mSubMenu != null) {
mSubMenu.setHeaderTitle(title);
}
return this;
}
```
This results in other update-related methods being run but I did not investigate this much further as I'm not sure if this is necessary - limiting prop updates to only when the value has changed is desirable either way.
- set `MenuItem`'s title and icon only when there was a change to the prop
| before | …
> fix(Android, Tabs): tab label flashing on tab change in `labeled` visbility mode

- apps/src/tests/TestSafeAreaViewIOS/bottom-tabs/BottomTabsComponent.tsx
- apps/src/tests/TestSafeAreaViewIOS/bottom-tabs/ConfigTab.tsx
This PR uncomments the config that had no effect when BottomTabs props were hardcoded in BottomTabsContainer before https://github.com/software-mansion/react-native-screens/pull/3246.
Uncommented tabBarMinimizeBehavior in `TestSafeAreaViewIOS` so it can be configured.
Use `TestSafeAreaViewIOS`, uncomment `BottomTabsSAVExample` from `index.tsx`
> chore: Uncomment tabBarMinimizeBehavior config in TestSafeAreaViewIOS

- android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerDelegate.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNSScreenManagerInterface.java
- guides/GUIDE_FOR_LIBRARY_AUTHORS.md
- ios/RNSConvert.h
- ios/RNSConvert.mm
- ios/RNSScreen.h
- ios/RNSScreen.mm
- ios/RNSScreenStack.mm
- ios/RNSScreenStackAnimator.mm
- src/components/Screen.tsx
- src/fabric/ModalScreenNativeComponent.ts
- src/fabric/ScreenNativeComponent.ts
- src/types.tsx
Resolves [[iOS] Bring back fullScreenSwipeEnabled on iOS 26](https://github.com/software-mansion/react-native-screens-labs/issues/466).
This PR brings back `fullScreenSwipeEnabled` prop on iOS 26. The type of the prop is changed internally to OptionalBoolean with default value differing between versions.
Use `Test3093`
> feat(iOS): Bring back fullScreenSwipeEnabled prop

- ios/RNSScreen.mm
#3212 introduced a bug when scrolling the view would trigger a scroll edge effect prop change. This happened because there was one place that didn't clear the flag that the prop was already set.
The `_shouldUpdateScrollEdgeEffects` flag is now being cleared in RNSScreen.finalizeUpdates.
| Before | After |
| --- | --- |
| <video src="https://github.com/user-attachments/assets/236e0317-b22d-45be-9513-081c57dadff8" /> | <video src="https://github.com/user-attachments/assets/753af5bd-7653-458e-8ca4-880ee728c468" /> |
Use Test3212.
> fix(iOS): Clear _shouldUpdateScrollEdgeEffects flag in RNSScreen.finalizeUpdates
